# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adair County",
        "state_fips": "21",
        "county_fips": "21001",
        "population": 18903,
        "land_area_sq_mi": 405.292,
        "centroid": [
          37.107461,
          -85.27965
        ],
        "county_seat": null
      },
      {
        "county_name": "Allen County",
        "state_fips": "21",
        "county_fips": "21003",
        "population": 20588,
        "land_area_sq_mi": 343.724,
        "centroid": [
          36.750241,
          -86.210149
        ],
        "county_seat": null
      },
      {
        "county_name": "Anderson County",
        "state_fips": "21",
        "county_fips": "21005",
        "population": 23852,
        "land_area_sq_mi": 202.26,
        "centroid": [
          38.02799,
          -84.925693
        ],
        "county_seat": null
      },
      {
        "county_name": "Ballard County",
        "state_fips": "21",
        "county_fips": "21007",
        "population": 7728,
        "land_area_sq_mi": 247.095,
        "centroid": [
          37.043623,
          -88.976992
        ],
        "county_seat": null
      },
      {
        "county_name": "Barren County",
        "state_fips": "21",
        "county_fips": "21009",
        "population": 44485,
        "land_area_sq_mi": 487.365,
        "centroid": [
          36.995285,
          -85.932182
        ],
        "county_seat": null
      },
      {
        "county_name": "Bath County",
        "state_fips": "21",
        "county_fips": "21011",
        "population": 12750,
        "land_area_sq_mi": 277.992,
        "centroid": [
          38.138475,
          -83.7406
        ],
        "county_seat": null
      },
      {
        "county_name": "Bell County",
        "state_fips": "21",
        "county_fips": "21013",
        "population": 24097,
        "land_area_sq_mi": 358.999,
        "centroid": [
          36.680825,
          -83.70439
        ],
        "county_seat": null
      },
      {
        "county_name": "Boone County",
        "state_fips": "21",
        "county_fips": "21015",
        "population": 135968,
        "land_area_sq_mi": 246.268,
        "centroid": [
          38.984893,
          -84.678985
        ],
        "county_seat": null
      },
      {
        "county_name": "Bourbon County",
        "state_fips": "21",
        "county_fips": "21017",
        "population": 20252,
        "land_area_sq_mi": 289.75,
        "centroid": [
          38.203999,
          -84.246703
        ],
        "county_seat": null
      },
      {
        "county_name": "Boyd County",
        "state_fips": "21",
        "county_fips": "21019",
        "population": 48261,
        "land_area_sq_mi": 159.866,
        "centroid": [
          38.432179,
          -82.666251
        ],
        "county_seat": null
      },
      {
        "county_name": "Boyle County",
        "state_fips": "21",
        "county_fips": "21021",
        "population": 30614,
        "land_area_sq_mi": 180.336,
        "centroid": [
          37.637853,
          -84.796823
        ],
        "county_seat": null
      },
      {
        "county_name": "Bracken County",
        "state_fips": "21",
        "county_fips": "21023",
        "population": 8400,
        "land_area_sq_mi": 202.665,
        "centroid": [
          38.701217,
          -84.072685
        ],
        "county_seat": null
      },
      {
        "county_name": "Breathitt County",
        "state_fips": "21",
        "county_fips": "21025",
        "population": 13718,
        "land_area_sq_mi": 492.422,
        "centroid": [
          37.518699,
          -83.377385
        ],
        "county_seat": null
      },
      {
        "county_name": "Breckinridge County",
        "state_fips": "21",
        "county_fips": "21027",
        "population": 20432,
        "land_area_sq_mi": 569.725,
        "centroid": [
          37.769799,
          -86.408122
        ],
        "county_seat": null
      },
      {
        "county_name": "Bullitt County",
        "state_fips": "21",
        "county_fips": "21029",
        "population": 82217,
        "land_area_sq_mi": 297.085,
        "centroid": [
          38.023787,
          -85.651771
        ],
        "county_seat": null
      },
      {
        "county_name": "Butler County",
        "state_fips": "21",
        "county_fips": "21031",
        "population": 12371,
        "land_area_sq_mi": 426.112,
        "centroid": [
          37.217537,
          -86.677714
        ],
        "county_seat": null
      },
      {
        "county_name": "Caldwell County",
        "state_fips": "21",
        "county_fips": "21033",
        "population": 12649,
        "land_area_sq_mi": 344.835,
        "centroid": [
          37.125484,
          -87.878812
        ],
        "county_seat": null
      },
      {
        "county_name": "Calloway County",
        "state_fips": "21",
        "county_fips": "21035",
        "population": 37103,
        "land_area_sq_mi": 384.862,
        "centroid": [
          36.621007,
          -88.30609
        ],
        "county_seat": null
      },
      {
        "county_name": "Campbell County",
        "state_fips": "21",
        "county_fips": "21037",
        "population": 93076,
        "land_area_sq_mi": 151.32,
        "centroid": [
          39.032376,
          -84.439251
        ],
        "county_seat": null
      },
      {
        "county_name": "Carlisle County",
        "state_fips": "21",
        "county_fips": "21039",
        "population": 4826,
        "land_area_sq_mi": 189.463,
        "centroid": [
          36.855639,
          -88.946346
        ],
        "county_seat": null
      },
      {
        "county_name": "Carroll County",
        "state_fips": "21",
        "county_fips": "21041",
        "population": 10810,
        "land_area_sq_mi": 128.7,
        "centroid": [
          38.669245,
          -85.140741
        ],
        "county_seat": null
      },
      {
        "county_name": "Carter County",
        "state_fips": "21",
        "county_fips": "21043",
        "population": 26627,
        "land_area_sq_mi": 409.497,
        "centroid": [
          38.314087,
          -83.034886
        ],
        "county_seat": null
      },
      {
        "county_name": "Casey County",
        "state_fips": "21",
        "county_fips": "21045",
        "population": 15941,
        "land_area_sq_mi": 444.258,
        "centroid": [
          37.301616,
          -84.925995
        ],
        "county_seat": null
      },
      {
        "county_name": "Christian County",
        "state_fips": "21",
        "county_fips": "21047",
        "population": 72748,
        "land_area_sq_mi": 717.66,
        "centroid": [
          36.80904,
          -87.477832
        ],
        "county_seat": null
      },
      {
        "county_name": "Clark County",
        "state_fips": "21",
        "county_fips": "21049",
        "population": 36972,
        "land_area_sq_mi": 252.482,
        "centroid": [
          37.986421,
          -84.182808
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "21",
        "county_fips": "21051",
        "population": 20345,
        "land_area_sq_mi": 469.296,
        "centroid": [
          37.168974,
          -83.750091
        ],
        "county_seat": null
      },
      {
        "county_name": "Clinton County",
        "state_fips": "21",
        "county_fips": "21053",
        "population": 9253,
        "land_area_sq_mi": 197.063,
        "centroid": [
          36.715915,
          -85.13447
        ],
        "county_seat": null
      },
      {
        "county_name": "Crittenden County",
        "state_fips": "21",
        "county_fips": "21055",
        "population": 8990,
        "land_area_sq_mi": 359.566,
        "centroid": [
          37.33223,
          -88.095012
        ],
        "county_seat": null
      },
      {
        "county_name": "Cumberland County",
        "state_fips": "21",
        "county_fips": "21057",
        "population": 5888,
        "land_area_sq_mi": 305.147,
        "centroid": [
          36.782421,
          -85.389733
        ],
        "county_seat": null
      },
      {
        "county_name": "Daviess County",
        "state_fips": "21",
        "county_fips": "21059",
        "population": 103312,
        "land_area_sq_mi": 458.398,
        "centroid": [
          37.747426,
          -87.095079
        ],
        "county_seat": null
      },
      {
        "county_name": "Edmonson County",
        "state_fips": "21",
        "county_fips": "21061",
        "population": 12126,
        "land_area_sq_mi": 302.806,
        "centroid": [
          37.192292,
          -86.253259
        ],
        "county_seat": null
      },
      {
        "county_name": "Elliott County",
        "state_fips": "21",
        "county_fips": "21063",
        "population": 7354,
        "land_area_sq_mi": 234.321,
        "centroid": [
          38.122978,
          -83.108689
        ],
        "county_seat": null
      },
      {
        "county_name": "Estill County",
        "state_fips": "21",
        "county_fips": "21065",
        "population": 14163,
        "land_area_sq_mi": 253.081,
        "centroid": [
          37.707053,
          -83.991846
        ],
        "county_seat": null
      },
      {
        "county_name": "Fayette County",
        "state_fips": "21",
        "county_fips": "21067",
        "population": 322570,
        "land_area_sq_mi": 283.854,
        "centroid": [
          38.020293,
          -84.49441
        ],
        "county_seat": null
      },
      {
        "county_name": "Fleming County",
        "state_fips": "21",
        "county_fips": "21069",
        "population": 15082,
        "land_area_sq_mi": 348.672,
        "centroid": [
          38.388852,
          -83.709683
        ],
        "county_seat": null
      },
      {
        "county_name": "Floyd County",
        "state_fips": "21",
        "county_fips": "21071",
        "population": 35942,
        "land_area_sq_mi": 393.3,
        "centroid": [
          37.558551,
          -82.7396
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "21",
        "county_fips": "21073",
        "population": 51541,
        "land_area_sq_mi": 207.91,
        "centroid": [
          38.195361,
          -84.867165
        ],
        "county_seat": null
      },
      {
        "county_name": "Fulton County",
        "state_fips": "21",
        "county_fips": "21075",
        "population": 6515,
        "land_area_sq_mi": 205.932,
        "centroid": [
          36.538105,
          -89.037115
        ],
        "county_seat": null
      },
      {
        "county_name": "Gallatin County",
        "state_fips": "21",
        "county_fips": "21077",
        "population": 8690,
        "land_area_sq_mi": 98.282,
        "centroid": [
          38.764935,
          -84.841609
        ],
        "county_seat": null
      },
      {
        "county_name": "Garrard County",
        "state_fips": "21",
        "county_fips": "21079",
        "population": 16953,
        "land_area_sq_mi": 229.925,
        "centroid": [
          37.650333,
          -84.575237
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "21",
        "county_fips": "21081",
        "population": 24941,
        "land_area_sq_mi": 257.976,
        "centroid": [
          38.689224,
          -84.602905
        ],
        "county_seat": null
      },
      {
        "county_name": "Graves County",
        "state_fips": "21",
        "county_fips": "21083",
        "population": 36649,
        "land_area_sq_mi": 551.757,
        "centroid": [
          36.742207,
          -88.650736
        ],
        "county_seat": null
      },
      {
        "county_name": "Grayson County",
        "state_fips": "21",
        "county_fips": "21085",
        "population": 26420,
        "land_area_sq_mi": 499.536,
        "centroid": [
          37.471252,
          -86.30457
        ],
        "county_seat": null
      },
      {
        "county_name": "Green County",
        "state_fips": "21",
        "county_fips": "21087",
        "population": 11107,
        "land_area_sq_mi": 285.963,
        "centroid": [
          37.265986,
          -85.538884
        ],
        "county_seat": null
      },
      {
        "county_name": "Greenup County",
        "state_fips": "21",
        "county_fips": "21089",
        "population": 35962,
        "land_area_sq_mi": 344.455,
        "centroid": [
          38.55436,
          -82.809161
        ],
        "county_seat": null
      },
      {
        "county_name": "Hancock County",
        "state_fips": "21",
        "county_fips": "21091",
        "population": 9095,
        "land_area_sq_mi": 187.675,
        "centroid": [
          37.868547,
          -86.805118
        ],
        "county_seat": null
      },
      {
        "county_name": "Hardin County",
        "state_fips": "21",
        "county_fips": "21093",
        "population": 110702,
        "land_area_sq_mi": 623.904,
        "centroid": [
          37.743564,
          -85.915853
        ],
        "county_seat": null
      },
      {
        "county_name": "Harlan County",
        "state_fips": "21",
        "county_fips": "21095",
        "population": 26831,
        "land_area_sq_mi": 465.83,
        "centroid": [
          36.866097,
          -83.2338
        ],
        "county_seat": null
      },
      {
        "county_name": "Harrison County",
        "state_fips": "21",
        "county_fips": "21097",
        "population": 18692,
        "land_area_sq_mi": 306.458,
        "centroid": [
          38.414072,
          -84.314294
        ],
        "county_seat": null
      },
      {
        "county_name": "Hart County",
        "state_fips": "21",
        "county_fips": "21099",
        "population": 19288,
        "land_area_sq_mi": 412.67,
        "centroid": [
          37.280435,
          -85.88777
        ],
        "county_seat": null
      },
      {
        "county_name": "Henderson County",
        "state_fips": "21",
        "county_fips": "21101",
        "population": 44793,
        "land_area_sq_mi": 436.361,
        "centroid": [
          37.817983,
          -87.564508
        ],
        "county_seat": null
      },
      {
        "county_name": "Henry County",
        "state_fips": "21",
        "county_fips": "21103",
        "population": 15678,
        "land_area_sq_mi": 286.251,
        "centroid": [
          38.4314,
          -85.180752
        ],
        "county_seat": null
      },
      {
        "county_name": "Hickman County",
        "state_fips": "21",
        "county_fips": "21105",
        "population": 4521,
        "land_area_sq_mi": 242.331,
        "centroid": [
          36.664413,
          -88.956556
        ],
        "county_seat": null
      },
      {
        "county_name": "Hopkins County",
        "state_fips": "21",
        "county_fips": "21107",
        "population": 45423,
        "land_area_sq_mi": 542.187,
        "centroid": [
          37.308856,
          -87.52201
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "21",
        "county_fips": "21109",
        "population": 12955,
        "land_area_sq_mi": 345.227,
        "centroid": [
          37.400575,
          -83.992381
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "21",
        "county_fips": "21111",
        "population": 782969,
        "land_area_sq_mi": 380.83,
        "centroid": [
          38.201451,
          -85.686227
        ],
        "county_seat": null
      },
      {
        "county_name": "Jessamine County",
        "state_fips": "21",
        "county_fips": "21113",
        "population": 52991,
        "land_area_sq_mi": 172.113,
        "centroid": [
          37.886869,
          -84.585371
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnson County",
        "state_fips": "21",
        "county_fips": "21115",
        "population": 22680,
        "land_area_sq_mi": 261.966,
        "centroid": [
          37.830575,
          -82.817074
        ],
        "county_seat": null
      },
      {
        "county_name": "Kenton County",
        "state_fips": "21",
        "county_fips": "21117",
        "population": 169064,
        "land_area_sq_mi": 160.374,
        "centroid": [
          39.011065,
          -84.549073
        ],
        "county_seat": null
      },
      {
        "county_name": "Knott County",
        "state_fips": "21",
        "county_fips": "21119",
        "population": 14251,
        "land_area_sq_mi": 351.524,
        "centroid": [
          37.328988,
          -82.942351
        ],
        "county_seat": null
      },
      {
        "county_name": "Knox County",
        "state_fips": "21",
        "county_fips": "21121",
        "population": 30193,
        "land_area_sq_mi": 386.33,
        "centroid": [
          36.902733,
          -83.921054
        ],
        "county_seat": null
      },
      {
        "county_name": "Larue County",
        "state_fips": "21",
        "county_fips": "21123",
        "population": 14867,
        "land_area_sq_mi": 261.04,
        "centroid": [
          37.542807,
          -85.723159
        ],
        "county_seat": null
      },
      {
        "county_name": "Laurel County",
        "state_fips": "21",
        "county_fips": "21125",
        "population": 62613,
        "land_area_sq_mi": 433.703,
        "centroid": [
          37.091997,
          -84.087505
        ],
        "county_seat": null
      },
      {
        "county_name": "Lawrence County",
        "state_fips": "21",
        "county_fips": "21127",
        "population": 16293,
        "land_area_sq_mi": 415.598,
        "centroid": [
          38.081027,
          -82.677508
        ],
        "county_seat": null
      },
      {
        "county_name": "Lee County",
        "state_fips": "21",
        "county_fips": "21129",
        "population": 7395,
        "land_area_sq_mi": 208.821,
        "centroid": [
          37.590698,
          -83.702693
        ],
        "county_seat": null
      },
      {
        "county_name": "Leslie County",
        "state_fips": "21",
        "county_fips": "21131",
        "population": 10513,
        "land_area_sq_mi": 400.878,
        "centroid": [
          37.115702,
          -83.376004
        ],
        "county_seat": null
      },
      {
        "county_name": "Letcher County",
        "state_fips": "21",
        "county_fips": "21133",
        "population": 21548,
        "land_area_sq_mi": 337.934,
        "centroid": [
          37.146816,
          -82.807202
        ],
        "county_seat": null
      },
      {
        "county_name": "Lewis County",
        "state_fips": "21",
        "county_fips": "21135",
        "population": 13080,
        "land_area_sq_mi": 482.858,
        "centroid": [
          38.564104,
          -83.350474
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "21",
        "county_fips": "21137",
        "population": 24275,
        "land_area_sq_mi": 332.904,
        "centroid": [
          37.473364,
          -84.670402
        ],
        "county_seat": null
      },
      {
        "county_name": "Livingston County",
        "state_fips": "21",
        "county_fips": "21139",
        "population": 8888,
        "land_area_sq_mi": 312.96,
        "centroid": [
          37.133064,
          -88.351386
        ],
        "county_seat": null
      },
      {
        "county_name": "Logan County",
        "state_fips": "21",
        "county_fips": "21141",
        "population": 27432,
        "land_area_sq_mi": 552.216,
        "centroid": [
          36.859958,
          -86.862831
        ],
        "county_seat": null
      },
      {
        "county_name": "Lyon County",
        "state_fips": "21",
        "county_fips": "21143",
        "population": 8680,
        "land_area_sq_mi": 213.785,
        "centroid": [
          37.065485,
          -88.079475
        ],
        "county_seat": null
      },
      {
        "county_name": "McCracken County",
        "state_fips": "21",
        "county_fips": "21145",
        "population": 67875,
        "land_area_sq_mi": 248.786,
        "centroid": [
          37.0493,
          -88.649871
        ],
        "county_seat": null
      },
      {
        "county_name": "McCreary County",
        "state_fips": "21",
        "county_fips": "21147",
        "population": 16888,
        "land_area_sq_mi": 426.709,
        "centroid": [
          36.713019,
          -84.447417
        ],
        "county_seat": null
      },
      {
        "county_name": "McLean County",
        "state_fips": "21",
        "county_fips": "21149",
        "population": 9152,
        "land_area_sq_mi": 252.525,
        "centroid": [
          37.51554,
          -87.221398
        ],
        "county_seat": null
      },
      {
        "county_name": "Madison County",
        "state_fips": "21",
        "county_fips": "21151",
        "population": 92701,
        "land_area_sq_mi": 437.934,
        "centroid": [
          37.70685,
          -84.286707
        ],
        "county_seat": null
      },
      {
        "county_name": "Magoffin County",
        "state_fips": "21",
        "county_fips": "21153",
        "population": 11637,
        "land_area_sq_mi": 308.443,
        "centroid": [
          37.733397,
          -83.057067
        ],
        "county_seat": null
      },
      {
        "county_name": "Marion County",
        "state_fips": "21",
        "county_fips": "21155",
        "population": 19581,
        "land_area_sq_mi": 343.551,
        "centroid": [
          37.570127,
          -85.28442
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "21",
        "county_fips": "21157",
        "population": 31659,
        "land_area_sq_mi": 302.126,
        "centroid": [
          36.897003,
          -88.34
        ],
        "county_seat": null
      },
      {
        "county_name": "Martin County",
        "state_fips": "21",
        "county_fips": "21159",
        "population": 11287,
        "land_area_sq_mi": 229.644,
        "centroid": [
          37.835468,
          -82.516965
        ],
        "county_seat": null
      },
      {
        "county_name": "Mason County",
        "state_fips": "21",
        "county_fips": "21161",
        "population": 17120,
        "land_area_sq_mi": 240.127,
        "centroid": [
          38.616511,
          -83.789096
        ],
        "county_seat": null
      },
      {
        "county_name": "Meade County",
        "state_fips": "21",
        "county_fips": "21163",
        "population": 30003,
        "land_area_sq_mi": 305.463,
        "centroid": [
          37.934417,
          -86.134606
        ],
        "county_seat": null
      },
      {
        "county_name": "Menifee County",
        "state_fips": "21",
        "county_fips": "21165",
        "population": 6113,
        "land_area_sq_mi": 203.538,
        "centroid": [
          37.945275,
          -83.595979
        ],
        "county_seat": null
      },
      {
        "county_name": "Mercer County",
        "state_fips": "21",
        "county_fips": "21167",
        "population": 22641,
        "land_area_sq_mi": 249.383,
        "centroid": [
          37.785035,
          -84.84891
        ],
        "county_seat": null
      },
      {
        "county_name": "Metcalfe County",
        "state_fips": "21",
        "county_fips": "21169",
        "population": 10286,
        "land_area_sq_mi": 289.651,
        "centroid": [
          36.990976,
          -85.64095
        ],
        "county_seat": null
      },
      {
        "county_name": "Monroe County",
        "state_fips": "21",
        "county_fips": "21171",
        "population": 11338,
        "land_area_sq_mi": 329.475,
        "centroid": [
          36.707799,
          -85.723364
        ],
        "county_seat": null
      },
      {
        "county_name": "Montgomery County",
        "state_fips": "21",
        "county_fips": "21173",
        "population": 28114,
        "land_area_sq_mi": 197.376,
        "centroid": [
          38.037988,
          -83.918227
        ],
        "county_seat": null
      },
      {
        "county_name": "Morgan County",
        "state_fips": "21",
        "county_fips": "21175",
        "population": 13726,
        "land_area_sq_mi": 381.104,
        "centroid": [
          37.914473,
          -83.268972
        ],
        "county_seat": null
      },
      {
        "county_name": "Muhlenberg County",
        "state_fips": "21",
        "county_fips": "21177",
        "population": 30928,
        "land_area_sq_mi": 467.28,
        "centroid": [
          37.238076,
          -87.146244
        ],
        "county_seat": null
      },
      {
        "county_name": "Nelson County",
        "state_fips": "21",
        "county_fips": "21179",
        "population": 46738,
        "land_area_sq_mi": 418.686,
        "centroid": [
          37.820783,
          -85.4595
        ],
        "county_seat": null
      },
      {
        "county_name": "Nicholas County",
        "state_fips": "21",
        "county_fips": "21181",
        "population": 7537,
        "land_area_sq_mi": 195.306,
        "centroid": [
          38.324558,
          -84.022987
        ],
        "county_seat": null
      },
      {
        "county_name": "Ohio County",
        "state_fips": "21",
        "county_fips": "21183",
        "population": 23772,
        "land_area_sq_mi": 587.095,
        "centroid": [
          37.464465,
          -86.864757
        ],
        "county_seat": null
      },
      {
        "county_name": "Oldham County",
        "state_fips": "21",
        "county_fips": "21185",
        "population": 67607,
        "land_area_sq_mi": 187.294,
        "centroid": [
          38.372614,
          -85.459227
        ],
        "county_seat": null
      },
      {
        "county_name": "Owen County",
        "state_fips": "21",
        "county_fips": "21187",
        "population": 11278,
        "land_area_sq_mi": 350.487,
        "centroid": [
          38.530989,
          -84.831041
        ],
        "county_seat": null
      },
      {
        "county_name": "Owsley County",
        "state_fips": "21",
        "county_fips": "21189",
        "population": 4051,
        "land_area_sq_mi": 197.402,
        "centroid": [
          37.45244,
          -83.68482
        ],
        "county_seat": null
      },
      {
        "county_name": "Pendleton County",
        "state_fips": "21",
        "county_fips": "21191",
        "population": 14644,
        "land_area_sq_mi": 277.148,
        "centroid": [
          38.715312,
          -84.359242
        ],
        "county_seat": null
      },
      {
        "county_name": "Perry County",
        "state_fips": "21",
        "county_fips": "21193",
        "population": 28473,
        "land_area_sq_mi": 339.724,
        "centroid": [
          37.258818,
          -83.200329
        ],
        "county_seat": null
      },
      {
        "county_name": "Pike County",
        "state_fips": "21",
        "county_fips": "21195",
        "population": 58669,
        "land_area_sq_mi": 786.222,
        "centroid": [
          37.463914,
          -82.427235
        ],
        "county_seat": null
      },
      {
        "county_name": "Powell County",
        "state_fips": "21",
        "county_fips": "21197",
        "population": 13129,
        "land_area_sq_mi": 178.962,
        "centroid": [
          37.850736,
          -83.880539
        ],
        "county_seat": null
      },
      {
        "county_name": "Pulaski County",
        "state_fips": "21",
        "county_fips": "21199",
        "population": 65034,
        "land_area_sq_mi": 658.1,
        "centroid": [
          37.092197,
          -84.614379
        ],
        "county_seat": null
      },
      {
        "county_name": "Robertson County",
        "state_fips": "21",
        "county_fips": "21201",
        "population": 2193,
        "land_area_sq_mi": 99.591,
        "centroid": [
          38.520923,
          -84.051005
        ],
        "county_seat": null
      },
      {
        "county_name": "Rockcastle County",
        "state_fips": "21",
        "county_fips": "21203",
        "population": 16037,
        "land_area_sq_mi": 316.567,
        "centroid": [
          37.380897,
          -84.351176
        ],
        "county_seat": null
      },
      {
        "county_name": "Rowan County",
        "state_fips": "21",
        "county_fips": "21205",
        "population": 24662,
        "land_area_sq_mi": 279.881,
        "centroid": [
          38.194754,
          -83.444323
        ],
        "county_seat": null
      },
      {
        "county_name": "Russell County",
        "state_fips": "21",
        "county_fips": "21207",
        "population": 17991,
        "land_area_sq_mi": 253.26,
        "centroid": [
          37.030799,
          -85.058512
        ],
        "county_seat": null
      },
      {
        "county_name": "Scott County",
        "state_fips": "21",
        "county_fips": "21209",
        "population": 57155,
        "land_area_sq_mi": 282.194,
        "centroid": [
          38.230636,
          -84.568282
        ],
        "county_seat": null
      },
      {
        "county_name": "Shelby County",
        "state_fips": "21",
        "county_fips": "21211",
        "population": 48065,
        "land_area_sq_mi": 379.79,
        "centroid": [
          38.212966,
          -85.232221
        ],
        "county_seat": null
      },
      {
        "county_name": "Simpson County",
        "state_fips": "21",
        "county_fips": "21213",
        "population": 19594,
        "land_area_sq_mi": 234.175,
        "centroid": [
          36.732484,
          -86.571947
        ],
        "county_seat": null
      },
      {
        "county_name": "Spencer County",
        "state_fips": "21",
        "county_fips": "21215",
        "population": 19490,
        "land_area_sq_mi": 186.671,
        "centroid": [
          38.06313,
          -85.350311
        ],
        "county_seat": null
      },
      {
        "county_name": "Taylor County",
        "state_fips": "21",
        "county_fips": "21217",
        "population": 26023,
        "land_area_sq_mi": 266.414,
        "centroid": [
          37.350286,
          -85.342524
        ],
        "county_seat": null
      },
      {
        "county_name": "Todd County",
        "state_fips": "21",
        "county_fips": "21219",
        "population": 12243,
        "land_area_sq_mi": 374.513,
        "centroid": [
          36.812095,
          -87.173233
        ],
        "county_seat": null
      },
      {
        "county_name": "Trigg County",
        "state_fips": "21",
        "county_fips": "21221",
        "population": 14061,
        "land_area_sq_mi": 441.433,
        "centroid": [
          36.845549,
          -87.834907
        ],
        "county_seat": null
      },
      {
        "county_name": "Trimble County",
        "state_fips": "21",
        "county_fips": "21223",
        "population": 8474,
        "land_area_sq_mi": 147.771,
        "centroid": [
          38.61932,
          -85.33207
        ],
        "county_seat": null
      },
      {
        "county_name": "Union County",
        "state_fips": "21",
        "county_fips": "21225",
        "population": 13668,
        "land_area_sq_mi": 342.878,
        "centroid": [
          37.652277,
          -87.929907
        ],
        "county_seat": null
      },
      {
        "county_name": "Warren County",
        "state_fips": "21",
        "county_fips": "21227",
        "population": 134554,
        "land_area_sq_mi": 541.73,
        "centroid": [
          36.966984,
          -86.435814
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "21",
        "county_fips": "21229",
        "population": 12027,
        "land_area_sq_mi": 297.284,
        "centroid": [
          37.738166,
          -85.192752
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "21",
        "county_fips": "21231",
        "population": 19555,
        "land_area_sq_mi": 458.043,
        "centroid": [
          36.838184,
          -84.845965
        ],
        "county_seat": null
      },
      {
        "county_name": "Webster County",
        "state_fips": "21",
        "county_fips": "21233",
        "population": 13017,
        "land_area_sq_mi": 332.026,
        "centroid": [
          37.502386,
          -87.68192
        ],
        "county_seat": null
      },
      {
        "county_name": "Whitley County",
        "state_fips": "21",
        "county_fips": "21235",
        "population": 36712,
        "land_area_sq_mi": 437.922,
        "centroid": [
          36.814087,
          -84.141533
        ],
        "county_seat": null
      },
      {
        "county_name": "Wolfe County",
        "state_fips": "21",
        "county_fips": "21237",
        "population": 6562,
        "land_area_sq_mi": 222.159,
        "centroid": [
          37.739826,
          -83.509721
        ],
        "county_seat": null
      },
      {
        "county_name": "Woodford County",
        "state_fips": "21",
        "county_fips": "21239",
        "population": 26871,
        "land_area_sq_mi": 189.573,
        "centroid": [
          38.048373,
          -84.726705
        ],
        "county_seat": null
      }
    ]
