# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Allegany County",
        "state_fips": "24",
        "county_fips": "24001",
        "population": 68106,
        "land_area_sq_mi": 422.199,
        "centroid": [
          39.628458,
          -78.820665
        ],
        "county_seat": null
      },
      {
        "county_name": "Anne Arundel County",
        "state_fips": "24",
        "county_fips": "24003",
        "population": 588261,
        "land_area_sq_mi": 414.806,
        "centroid": [
          39.071038,
          -76.604417
        ],
        "county_seat": null
      },
      {
        "county_name": "Baltimore County",
        "state_fips": "24",
        "county_fips": "24005",
        "population": 854535,
        "land_area_sq_mi": 598.358,
        "centroid": [
          39.368834,
          -76.620325
        ],
        "county_seat": null
      },
      {
        "county_name": "Calvert County",
        "state_fips": "24",
        "county_fips": "24009",
        "population": 92783,
        "land_area_sq_mi": 213.19,
        "centroid": [
          38.551108,
          -76.54407
        ],
        "county_seat": null
      },
      {
        "county_name": "Caroline County",
        "state_fips": "24",
        "county_fips": "24011",
        "population": 33293,
        "land_area_sq_mi": 319.442,
        "centroid": [
          38.873476,
          -75.830203
        ],
        "county_seat": null
      },
      {
        "county_name": "Carroll County",
        "state_fips": "24",
        "county_fips": "24013",
        "population": 172891,
        "land_area_sq_mi": 447.615,
        "centroid": [
          39.526206,
          -76.993056
        ],
        "county_seat": null
      },
      {
        "county_name": "Cecil County",
        "state_fips": "24",
        "county_fips": "24015",
        "population": 103725,
        "land_area_sq_mi": 346.3,
        "centroid": [
          39.614177,
          -75.936285
        ],
        "county_seat": null
      },
      {
        "county_name": "Charles County",
        "state_fips": "24",
        "county_fips": "24017",
        "population": 166617,
        "land_area_sq_mi": 457.819,
        "centroid": [
          38.58147,
          -76.951519
        ],
        "county_seat": null
      },
      {
        "county_name": "Dorchester County",
        "state_fips": "24",
        "county_fips": "24019",
        "population": 32531,
        "land_area_sq_mi": 540.765,
        "centroid": [
          38.571271,
          -76.011658
        ],
        "county_seat": null
      },
      {
        "county_name": "Frederick County",
        "state_fips": "24",
        "county_fips": "24021",
        "population": 271717,
        "land_area_sq_mi": 660.625,
        "centroid": [
          39.427679,
          -77.400605
        ],
        "county_seat": null
      },
      {
        "county_name": "Garrett County",
        "state_fips": "24",
        "county_fips": "24023",
        "population": 28806,
        "land_area_sq_mi": 649.077,
        "centroid": [
          39.51324,
          -79.305826
        ],
        "county_seat": null
      },
      {
        "county_name": "Harford County",
        "state_fips": "24",
        "county_fips": "24025",
        "population": 260924,
        "land_area_sq_mi": 437.125,
        "centroid": [
          39.520613,
          -76.309261
        ],
        "county_seat": null
      },
      {
        "county_name": "Howard County",
        "state_fips": "24",
        "county_fips": "24027",
        "population": 332317,
        "land_area_sq_mi": 250.95,
        "centroid": [
          39.217658,
          -76.854298
        ],
        "county_seat": null
      },
      {
        "county_name": "Kent County",
        "state_fips": "24",
        "county_fips": "24029",
        "population": 19198,
        "land_area_sq_mi": 276.939,
        "centroid": [
          39.244676,
          -76.05767
        ],
        "county_seat": null
      },
      {
        "county_name": "Montgomery County",
        "state_fips": "24",
        "county_fips": "24031",
        "population": 1062061,
        "land_area_sq_mi": 493.145,
        "centroid": [
          39.087069,
          -77.124126
        ],
        "county_seat": null
      },
      {
        "county_name": "Prince George's County",
        "state_fips": "24",
        "county_fips": "24033",
        "population": 967201,
        "land_area_sq_mi": 482.595,
        "centroid": [
          38.909313,
          -76.888689
        ],
        "county_seat": null
      },
      {
        "county_name": "Queen Anne's County",
        "state_fips": "24",
        "county_fips": "24035",
        "population": 49874,
        "land_area_sq_mi": 371.669,
        "centroid": [
          39.021381,
          -76.149985
        ],
        "county_seat": null
      },
      {
        "county_name": "St. Mary's County",
        "state_fips": "24",
        "county_fips": "24037",
        "population": 113777,
        "land_area_sq_mi": 358.564,
        "centroid": [
          38.307223,
          -76.577954
        ],
        "county_seat": null
      },
      {
        "county_name": "Somerset County",
        "state_fips": "24",
        "county_fips": "24039",
        "population": 24620,
        "land_area_sq_mi": 319.749,
        "centroid": [
          38.13306,
          -75.742151
        ],
        "county_seat": null
      },
      {
        "county_name": "Talbot County",
        "state_fips": "24",
        "county_fips": "24041",
        "population": 37526,
        "land_area_sq_mi": 268.556,
        "centroid": [
          38.7685,
          -76.098027
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "24",
        "county_fips": "24043",
        "population": 154705,
        "land_area_sq_mi": 457.784,
        "centroid": [
          39.618688,
          -77.73148
        ],
        "county_seat": null
      },
      {
        "county_name": "Wicomico County",
        "state_fips": "24",
        "county_fips": "24045",
        "population": 103588,
        "land_area_sq_mi": 374.427,
        "centroid": [
          38.372255,
          -75.593756
        ],
        "county_seat": null
      },
      {
        "county_name": "Worcester County",
        "state_fips": "24",
        "county_fips": "24047",
        "population": 52460,
        "land_area_sq_mi": 468.298,
        "centroid": [
          38.30361,
          -75.234513
        ],
        "county_seat": null
      },
      {
        "county_name": "Baltimore County",
        "state_fips": "24",
        "county_fips": "24510",
        "population": 585708,
        "land_area_sq_mi": 80.946,
        "centroid": [
          39.314378,
          -76.618104
        ],
        "county_seat": null
      }
    ]
