# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "District of Columbia County",
        "state_fips": "11",
        "county_fips": "11001",
        "population": 689545,
        "land_area_sq_mi": 61.126,
        "centroid": [
          38.910168,
          -77.013993
        ],
        "county_seat": null
      }
    ]
