# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Anderson County",
        "state_fips": "47",
        "county_fips": "47001",
        "population": 77123,
        "land_area_sq_mi": 337.206,
        "centroid": [
          36.081238,
          -84.178765
        ],
        "county_seat": null
      },
      {
        "county_name": "Bedford County",
        "state_fips": "47",
        "county_fips": "47003",
        "population": 50237,
        "land_area_sq_mi": 473.639,
        "centroid": [
          35.512233,
          -86.465018
        ],
        "county_seat": null
      },
      {
        "county_name": "Benton County",
        "state_fips": "47",
        "county_fips": "47005",
        "population": 15864,
        "land_area_sq_mi": 394.306,
        "centroid": [
          36.070898,
          -88.090044
        ],
        "county_seat": null
      },
      {
        "county_name": "Bledsoe County",
        "state_fips": "47",
        "county_fips": "47007",
        "population": 14913,
        "land_area_sq_mi": 406.555,
        "centroid": [
          35.621511,
          -85.200314
        ],
        "county_seat": null
      },
      {
        "county_name": "Blount County",
        "state_fips": "47",
        "county_fips": "47009",
        "population": 135280,
        "land_area_sq_mi": 558.844,
        "centroid": [
          35.753197,
          -83.973461
        ],
        "county_seat": null
      },
      {
        "county_name": "Bradley County",
        "state_fips": "47",
        "county_fips": "47011",
        "population": 108620,
        "land_area_sq_mi": 328.762,
        "centroid": [
          35.167425,
          -84.859688
        ],
        "county_seat": null
      },
      {
        "county_name": "Campbell County",
        "state_fips": "47",
        "county_fips": "47013",
        "population": 39272,
        "land_area_sq_mi": 480.19,
        "centroid": [
          36.381486,
          -84.125957
        ],
        "county_seat": null
      },
      {
        "county_name": "Cannon County",
        "state_fips": "47",
        "county_fips": "47015",
        "population": 14506,
        "land_area_sq_mi": 265.635,
        "centroid": [
          35.799353,
          -86.063976
        ],
        "county_seat": null
      },
      {
        "county_name": "Carroll County",
        "state_fips": "47",
        "county_fips": "47017",
        "population": 28440,
        "land_area_sq_mi": 597.658,
        "centroid": [
          36.018877,
          -88.464218
        ],
        "county_seat": null
      },
      {
        "county_name": "Carter County",
        "state_fips": "47",
        "county_fips": "47019",
        "population": 56356,
        "land_area_sq_mi": 341.258,
        "centroid": [
          36.31899,
          -82.203404
        ],
        "county_seat": null
      },
      {
        "county_name": "Cheatham County",
        "state_fips": "47",
        "county_fips": "47021",
        "population": 41072,
        "land_area_sq_mi": 302.498,
        "centroid": [
          36.272282,
          -87.063519
        ],
        "county_seat": null
      },
      {
        "county_name": "Chester County",
        "state_fips": "47",
        "county_fips": "47023",
        "population": 17341,
        "land_area_sq_mi": 285.736,
        "centroid": [
          35.438266,
          -88.62251
        ],
        "county_seat": null
      },
      {
        "county_name": "Claiborne County",
        "state_fips": "47",
        "county_fips": "47025",
        "population": 32043,
        "land_area_sq_mi": 434.604,
        "centroid": [
          36.4887,
          -83.639849
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "47",
        "county_fips": "47027",
        "population": 7581,
        "land_area_sq_mi": 236.529,
        "centroid": [
          36.552828,
          -85.562901
        ],
        "county_seat": null
      },
      {
        "county_name": "Cocke County",
        "state_fips": "47",
        "county_fips": "47029",
        "population": 35999,
        "land_area_sq_mi": 436.135,
        "centroid": [
          35.947274,
          -83.174047
        ],
        "county_seat": null
      },
      {
        "county_name": "Coffee County",
        "state_fips": "47",
        "county_fips": "47031",
        "population": 57889,
        "land_area_sq_mi": 428.964,
        "centroid": [
          35.454229,
          -86.124582
        ],
        "county_seat": null
      },
      {
        "county_name": "Crockett County",
        "state_fips": "47",
        "county_fips": "47033",
        "population": 13911,
        "land_area_sq_mi": 265.528,
        "centroid": [
          35.787543,
          -89.120017
        ],
        "county_seat": null
      },
      {
        "county_name": "Cumberland County",
        "state_fips": "47",
        "county_fips": "47035",
        "population": 61145,
        "land_area_sq_mi": 681.309,
        "centroid": [
          35.955637,
          -85.017779
        ],
        "county_seat": null
      },
      {
        "county_name": "Davidson County",
        "state_fips": "47",
        "county_fips": "47037",
        "population": 715884,
        "land_area_sq_mi": 503.481,
        "centroid": [
          36.137771,
          -86.744752
        ],
        "county_seat": null
      },
      {
        "county_name": "Decatur County",
        "state_fips": "47",
        "county_fips": "47039",
        "population": 11435,
        "land_area_sq_mi": 333.879,
        "centroid": [
          35.606176,
          -88.123327
        ],
        "county_seat": null
      },
      {
        "county_name": "DeKalb County",
        "state_fips": "47",
        "county_fips": "47041",
        "population": 20080,
        "land_area_sq_mi": 304.432,
        "centroid": [
          35.967047,
          -85.836916
        ],
        "county_seat": null
      },
      {
        "county_name": "Dickson County",
        "state_fips": "47",
        "county_fips": "47043",
        "population": 54315,
        "land_area_sq_mi": 489.899,
        "centroid": [
          36.104233,
          -87.343938
        ],
        "county_seat": null
      },
      {
        "county_name": "Dyer County",
        "state_fips": "47",
        "county_fips": "47045",
        "population": 36801,
        "land_area_sq_mi": 512.351,
        "centroid": [
          36.059417,
          -89.358361
        ],
        "county_seat": null
      },
      {
        "county_name": "Fayette County",
        "state_fips": "47",
        "county_fips": "47047",
        "population": 41990,
        "land_area_sq_mi": 704.124,
        "centroid": [
          35.201116,
          -89.479763
        ],
        "county_seat": null
      },
      {
        "county_name": "Fentress County",
        "state_fips": "47",
        "county_fips": "47049",
        "population": 18489,
        "land_area_sq_mi": 498.607,
        "centroid": [
          36.363232,
          -84.936669
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "47",
        "county_fips": "47051",
        "population": 42774,
        "land_area_sq_mi": 550.573,
        "centroid": [
          35.208173,
          -86.116159
        ],
        "county_seat": null
      },
      {
        "county_name": "Gibson County",
        "state_fips": "47",
        "county_fips": "47053",
        "population": 50429,
        "land_area_sq_mi": 602.745,
        "centroid": [
          35.932264,
          -88.870969
        ],
        "county_seat": null
      },
      {
        "county_name": "Giles County",
        "state_fips": "47",
        "county_fips": "47055",
        "population": 30346,
        "land_area_sq_mi": 610.931,
        "centroid": [
          35.192203,
          -87.030448
        ],
        "county_seat": null
      },
      {
        "county_name": "Grainger County",
        "state_fips": "47",
        "county_fips": "47057",
        "population": 23527,
        "land_area_sq_mi": 280.587,
        "centroid": [
          36.266188,
          -83.48663
        ],
        "county_seat": null
      },
      {
        "county_name": "Greene County",
        "state_fips": "47",
        "county_fips": "47059",
        "population": 70152,
        "land_area_sq_mi": 622.169,
        "centroid": [
          36.17748,
          -82.832594
        ],
        "county_seat": null
      },
      {
        "county_name": "Grundy County",
        "state_fips": "47",
        "county_fips": "47061",
        "population": 13529,
        "land_area_sq_mi": 360.444,
        "centroid": [
          35.343196,
          -85.722272
        ],
        "county_seat": null
      },
      {
        "county_name": "Hamblen County",
        "state_fips": "47",
        "county_fips": "47063",
        "population": 64499,
        "land_area_sq_mi": 161.188,
        "centroid": [
          36.215549,
          -83.297502
        ],
        "county_seat": null
      },
      {
        "county_name": "Hamilton County",
        "state_fips": "47",
        "county_fips": "47065",
        "population": 366207,
        "land_area_sq_mi": 542.164,
        "centroid": [
          35.093764,
          -85.201806
        ],
        "county_seat": null
      },
      {
        "county_name": "Hancock County",
        "state_fips": "47",
        "county_fips": "47067",
        "population": 6662,
        "land_area_sq_mi": 222.324,
        "centroid": [
          36.517225,
          -83.231102
        ],
        "county_seat": null
      },
      {
        "county_name": "Hardeman County",
        "state_fips": "47",
        "county_fips": "47069",
        "population": 25462,
        "land_area_sq_mi": 667.768,
        "centroid": [
          35.222929,
          -89.018519
        ],
        "county_seat": null
      },
      {
        "county_name": "Hardin County",
        "state_fips": "47",
        "county_fips": "47071",
        "population": 26831,
        "land_area_sq_mi": 577.487,
        "centroid": [
          35.198544,
          -88.225953
        ],
        "county_seat": null
      },
      {
        "county_name": "Hawkins County",
        "state_fips": "47",
        "county_fips": "47073",
        "population": 56721,
        "land_area_sq_mi": 487.056,
        "centroid": [
          36.463,
          -82.874023
        ],
        "county_seat": null
      },
      {
        "county_name": "Haywood County",
        "state_fips": "47",
        "county_fips": "47075",
        "population": 17864,
        "land_area_sq_mi": 533.107,
        "centroid": [
          35.586198,
          -89.267733
        ],
        "county_seat": null
      },
      {
        "county_name": "Henderson County",
        "state_fips": "47",
        "county_fips": "47077",
        "population": 27842,
        "land_area_sq_mi": 520.009,
        "centroid": [
          35.647965,
          -88.402891
        ],
        "county_seat": null
      },
      {
        "county_name": "Henry County",
        "state_fips": "47",
        "county_fips": "47079",
        "population": 32199,
        "land_area_sq_mi": 561.902,
        "centroid": [
          36.319829,
          -88.291369
        ],
        "county_seat": null
      },
      {
        "county_name": "Hickman County",
        "state_fips": "47",
        "county_fips": "47081",
        "population": 24925,
        "land_area_sq_mi": 612.483,
        "centroid": [
          35.85471,
          -87.405499
        ],
        "county_seat": null
      },
      {
        "county_name": "Houston County",
        "state_fips": "47",
        "county_fips": "47083",
        "population": 8283,
        "land_area_sq_mi": 200.294,
        "centroid": [
          36.304161,
          -87.704274
        ],
        "county_seat": null
      },
      {
        "county_name": "Humphreys County",
        "state_fips": "47",
        "county_fips": "47085",
        "population": 18990,
        "land_area_sq_mi": 530.763,
        "centroid": [
          36.071211,
          -87.77509
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "47",
        "county_fips": "47087",
        "population": 11617,
        "land_area_sq_mi": 308.81,
        "centroid": [
          36.327984,
          -85.629403
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "47",
        "county_fips": "47089",
        "population": 54683,
        "land_area_sq_mi": 275.155,
        "centroid": [
          36.064823,
          -83.453077
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnson County",
        "state_fips": "47",
        "county_fips": "47091",
        "population": 17948,
        "land_area_sq_mi": 298.44,
        "centroid": [
          36.450066,
          -81.844689
        ],
        "county_seat": null
      },
      {
        "county_name": "Knox County",
        "state_fips": "47",
        "county_fips": "47093",
        "population": 478971,
        "land_area_sq_mi": 508.325,
        "centroid": [
          35.971886,
          -83.991621
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake County",
        "state_fips": "47",
        "county_fips": "47095",
        "population": 7005,
        "land_area_sq_mi": 165.785,
        "centroid": [
          36.356402,
          -89.467221
        ],
        "county_seat": null
      },
      {
        "county_name": "Lauderdale County",
        "state_fips": "47",
        "county_fips": "47097",
        "population": 25143,
        "land_area_sq_mi": 471.895,
        "centroid": [
          35.765131,
          -89.537383
        ],
        "county_seat": null
      },
      {
        "county_name": "Lawrence County",
        "state_fips": "47",
        "county_fips": "47099",
        "population": 44159,
        "land_area_sq_mi": 617.13,
        "centroid": [
          35.237607,
          -87.353601
        ],
        "county_seat": null
      },
      {
        "county_name": "Lewis County",
        "state_fips": "47",
        "county_fips": "47101",
        "population": 12582,
        "land_area_sq_mi": 282.092,
        "centroid": [
          35.533225,
          -87.521716
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "47",
        "county_fips": "47103",
        "population": 35319,
        "land_area_sq_mi": 570.342,
        "centroid": [
          35.105199,
          -86.57174
        ],
        "county_seat": null
      },
      {
        "county_name": "Loudon County",
        "state_fips": "47",
        "county_fips": "47105",
        "population": 54886,
        "land_area_sq_mi": 229.272,
        "centroid": [
          35.760641,
          -84.284282
        ],
        "county_seat": null
      },
      {
        "county_name": "McMinn County",
        "state_fips": "47",
        "county_fips": "47107",
        "population": 53276,
        "land_area_sq_mi": 430.117,
        "centroid": [
          35.426045,
          -84.598722
        ],
        "county_seat": null
      },
      {
        "county_name": "McNairy County",
        "state_fips": "47",
        "county_fips": "47109",
        "population": 25866,
        "land_area_sq_mi": 562.845,
        "centroid": [
          35.176963,
          -88.537496
        ],
        "county_seat": null
      },
      {
        "county_name": "Macon County",
        "state_fips": "47",
        "county_fips": "47111",
        "population": 25216,
        "land_area_sq_mi": 307.144,
        "centroid": [
          36.535265,
          -86.025628
        ],
        "county_seat": null
      },
      {
        "county_name": "Madison County",
        "state_fips": "47",
        "county_fips": "47113",
        "population": 98823,
        "land_area_sq_mi": 557.174,
        "centroid": [
          35.653504,
          -88.824487
        ],
        "county_seat": null
      },
      {
        "county_name": "Marion County",
        "state_fips": "47",
        "county_fips": "47115",
        "population": 28837,
        "land_area_sq_mi": 502.179,
        "centroid": [
          35.10952,
          -85.608797
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "47",
        "county_fips": "47117",
        "population": 34318,
        "land_area_sq_mi": 375.462,
        "centroid": [
          35.496732,
          -86.770825
        ],
        "county_seat": null
      },
      {
        "county_name": "Maury County",
        "state_fips": "47",
        "county_fips": "47119",
        "population": 100974,
        "land_area_sq_mi": 613.083,
        "centroid": [
          35.635591,
          -87.029196
        ],
        "county_seat": null
      },
      {
        "county_name": "Meigs County",
        "state_fips": "47",
        "county_fips": "47121",
        "population": 12758,
        "land_area_sq_mi": 195.135,
        "centroid": [
          35.502098,
          -84.816211
        ],
        "county_seat": null
      },
      {
        "county_name": "Monroe County",
        "state_fips": "47",
        "county_fips": "47123",
        "population": 46250,
        "land_area_sq_mi": 635.774,
        "centroid": [
          35.518372,
          -84.354235
        ],
        "county_seat": null
      },
      {
        "county_name": "Montgomery County",
        "state_fips": "47",
        "county_fips": "47125",
        "population": 220069,
        "land_area_sq_mi": 539.169,
        "centroid": [
          36.557126,
          -87.345978
        ],
        "county_seat": null
      },
      {
        "county_name": "Moore County",
        "state_fips": "47",
        "county_fips": "47127",
        "population": 6461,
        "land_area_sq_mi": 129.223,
        "centroid": [
          35.296438,
          -86.340442
        ],
        "county_seat": null
      },
      {
        "county_name": "Morgan County",
        "state_fips": "47",
        "county_fips": "47129",
        "population": 21035,
        "land_area_sq_mi": 522.18,
        "centroid": [
          36.098366,
          -84.593205
        ],
        "county_seat": null
      },
      {
        "county_name": "Obion County",
        "state_fips": "47",
        "county_fips": "47131",
        "population": 30787,
        "land_area_sq_mi": 544.848,
        "centroid": [
          36.397163,
          -89.07991
        ],
        "county_seat": null
      },
      {
        "county_name": "Overton County",
        "state_fips": "47",
        "county_fips": "47133",
        "population": 22511,
        "land_area_sq_mi": 433.488,
        "centroid": [
          36.344912,
          -85.324939
        ],
        "county_seat": null
      },
      {
        "county_name": "Perry County",
        "state_fips": "47",
        "county_fips": "47135",
        "population": 8366,
        "land_area_sq_mi": 414.765,
        "centroid": [
          35.653842,
          -87.859297
        ],
        "county_seat": null
      },
      {
        "county_name": "Pickett County",
        "state_fips": "47",
        "county_fips": "47137",
        "population": 5001,
        "land_area_sq_mi": 162.97,
        "centroid": [
          36.565622,
          -85.141318
        ],
        "county_seat": null
      },
      {
        "county_name": "Polk County",
        "state_fips": "47",
        "county_fips": "47139",
        "population": 17544,
        "land_area_sq_mi": 434.605,
        "centroid": [
          35.125195,
          -84.568406
        ],
        "county_seat": null
      },
      {
        "county_name": "Putnam County",
        "state_fips": "47",
        "county_fips": "47141",
        "population": 79854,
        "land_area_sq_mi": 401.106,
        "centroid": [
          36.163157,
          -85.503795
        ],
        "county_seat": null
      },
      {
        "county_name": "Rhea County",
        "state_fips": "47",
        "county_fips": "47143",
        "population": 32870,
        "land_area_sq_mi": 315.473,
        "centroid": [
          35.556758,
          -84.954393
        ],
        "county_seat": null
      },
      {
        "county_name": "Roane County",
        "state_fips": "47",
        "county_fips": "47145",
        "population": 53404,
        "land_area_sq_mi": 360.768,
        "centroid": [
          35.881148,
          -84.52216
        ],
        "county_seat": null
      },
      {
        "county_name": "Robertson County",
        "state_fips": "47",
        "county_fips": "47147",
        "population": 72803,
        "land_area_sq_mi": 476.336,
        "centroid": [
          36.48456,
          -86.830273
        ],
        "county_seat": null
      },
      {
        "county_name": "Rutherford County",
        "state_fips": "47",
        "county_fips": "47149",
        "population": 341486,
        "land_area_sq_mi": 619.267,
        "centroid": [
          35.888267,
          -86.450266
        ],
        "county_seat": null
      },
      {
        "county_name": "Scott County",
        "state_fips": "47",
        "county_fips": "47151",
        "population": 21850,
        "land_area_sq_mi": 532.301,
        "centroid": [
          36.45447,
          -84.508258
        ],
        "county_seat": null
      },
      {
        "county_name": "Sequatchie County",
        "state_fips": "47",
        "county_fips": "47153",
        "population": 15826,
        "land_area_sq_mi": 265.851,
        "centroid": [
          35.355415,
          -85.391417
        ],
        "county_seat": null
      },
      {
        "county_name": "Sevier County",
        "state_fips": "47",
        "county_fips": "47155",
        "population": 98380,
        "land_area_sq_mi": 592.518,
        "centroid": [
          35.864247,
          -83.58249
        ],
        "county_seat": null
      },
      {
        "county_name": "Shelby County",
        "state_fips": "47",
        "county_fips": "47157",
        "population": 929744,
        "land_area_sq_mi": 752.764,
        "centroid": [
          35.131029,
          -89.886356
        ],
        "county_seat": null
      },
      {
        "county_name": "Smith County",
        "state_fips": "47",
        "county_fips": "47159",
        "population": 19904,
        "land_area_sq_mi": 314.278,
        "centroid": [
          36.241313,
          -85.968175
        ],
        "county_seat": null
      },
      {
        "county_name": "Stewart County",
        "state_fips": "47",
        "county_fips": "47161",
        "population": 13657,
        "land_area_sq_mi": 459.776,
        "centroid": [
          36.493716,
          -87.800108
        ],
        "county_seat": null
      },
      {
        "county_name": "Sullivan County",
        "state_fips": "47",
        "county_fips": "47163",
        "population": 158163,
        "land_area_sq_mi": 413.544,
        "centroid": [
          36.529913,
          -82.397127
        ],
        "county_seat": null
      },
      {
        "county_name": "Sumner County",
        "state_fips": "47",
        "county_fips": "47165",
        "population": 196281,
        "land_area_sq_mi": 529.454,
        "centroid": [
          36.396228,
          -86.536038
        ],
        "county_seat": null
      },
      {
        "county_name": "Tipton County",
        "state_fips": "47",
        "county_fips": "47167",
        "population": 60970,
        "land_area_sq_mi": 455.611,
        "centroid": [
          35.47587,
          -89.750299
        ],
        "county_seat": null
      },
      {
        "county_name": "Trousdale County",
        "state_fips": "47",
        "county_fips": "47169",
        "population": 11615,
        "land_area_sq_mi": 114.342,
        "centroid": [
          36.386235,
          -86.153351
        ],
        "county_seat": null
      },
      {
        "county_name": "Unicoi County",
        "state_fips": "47",
        "county_fips": "47171",
        "population": 17928,
        "land_area_sq_mi": 186.064,
        "centroid": [
          36.151274,
          -82.394706
        ],
        "county_seat": null
      },
      {
        "county_name": "Union County",
        "state_fips": "47",
        "county_fips": "47173",
        "population": 19802,
        "land_area_sq_mi": 223.583,
        "centroid": [
          36.245311,
          -83.815954
        ],
        "county_seat": null
      },
      {
        "county_name": "Van Buren County",
        "state_fips": "47",
        "county_fips": "47175",
        "population": 6168,
        "land_area_sq_mi": 273.415,
        "centroid": [
          35.711516,
          -85.454611
        ],
        "county_seat": null
      },
      {
        "county_name": "Warren County",
        "state_fips": "47",
        "county_fips": "47177",
        "population": 40953,
        "land_area_sq_mi": 432.673,
        "centroid": [
          35.695188,
          -85.794787
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "47",
        "county_fips": "47179",
        "population": 133001,
        "land_area_sq_mi": 326.548,
        "centroid": [
          36.325615,
          -82.433815
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "47",
        "county_fips": "47181",
        "population": 16232,
        "land_area_sq_mi": 734.109,
        "centroid": [
          35.258132,
          -87.790328
        ],
        "county_seat": null
      },
      {
        "county_name": "Weakley County",
        "state_fips": "47",
        "county_fips": "47183",
        "population": 32902,
        "land_area_sq_mi": 580.353,
        "centroid": [
          36.292493,
          -88.773817
        ],
        "county_seat": null
      },
      {
        "county_name": "White County",
        "state_fips": "47",
        "county_fips": "47185",
        "population": 27351,
        "land_area_sq_mi": 376.678,
        "centroid": [
          35.941573,
          -85.488902
        ],
        "county_seat": null
      },
      {
        "county_name": "Williamson County",
        "state_fips": "47",
        "county_fips": "47187",
        "population": 247726,
        "land_area_sq_mi": 582.911,
        "centroid": [
          35.912269,
          -86.846241
        ],
        "county_seat": null
      },
      {
        "county_name": "Wilson County",
        "state_fips": "47",
        "county_fips": "47189",
        "population": 147737,
        "land_area_sq_mi": 571.088,
        "centroid": [
          36.200347,
          -86.409498
        ],
        "county_seat": null
      }
    ]
