# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Beaver County",
        "state_fips": "49",
        "county_fips": "49001",
        "population": 7072,
        "land_area_sq_mi": 2582.912,
        "centroid": [
          38.29808,
          -112.762542
        ],
        "county_seat": null
      },
      {
        "county_name": "Box Elder County",
        "state_fips": "49",
        "county_fips": "49003",
        "population": 57666,
        "land_area_sq_mi": 5781.304,
        "centroid": [
          41.592632,
          -112.09841
        ],
        "county_seat": null
      },
      {
        "county_name": "Cache County",
        "state_fips": "49",
        "county_fips": "49005",
        "population": 133154,
        "land_area_sq_mi": 1164.687,
        "centroid": [
          41.745425,
          -111.839724
        ],
        "county_seat": null
      },
      {
        "county_name": "Carbon County",
        "state_fips": "49",
        "county_fips": "49007",
        "population": 20412,
        "land_area_sq_mi": 1479.343,
        "centroid": [
          39.602446,
          -110.777569
        ],
        "county_seat": null
      },
      {
        "county_name": "Daggett County",
        "state_fips": "49",
        "county_fips": "49009",
        "population": 935,
        "land_area_sq_mi": 696.515,
        "centroid": [
          40.967095,
          -109.647096
        ],
        "county_seat": null
      },
      {
        "county_name": "Davis County",
        "state_fips": "49",
        "county_fips": "49011",
        "population": 362679,
        "land_area_sq_mi": 324.753,
        "centroid": [
          41.019939,
          -111.960883
        ],
        "county_seat": null
      },
      {
        "county_name": "Duchesne County",
        "state_fips": "49",
        "county_fips": "49013",
        "population": 19596,
        "land_area_sq_mi": 3235.523,
        "centroid": [
          40.289458,
          -110.162356
        ],
        "county_seat": null
      },
      {
        "county_name": "Emery County",
        "state_fips": "49",
        "county_fips": "49015",
        "population": 9825,
        "land_area_sq_mi": 4462.635,
        "centroid": [
          39.217578,
          -110.929942
        ],
        "county_seat": null
      },
      {
        "county_name": "Garfield County",
        "state_fips": "49",
        "county_fips": "49017",
        "population": 5083,
        "land_area_sq_mi": 5179.556,
        "centroid": [
          37.765439,
          -112.100464
        ],
        "county_seat": null
      },
      {
        "county_name": "Grand County",
        "state_fips": "49",
        "county_fips": "49019",
        "population": 9669,
        "land_area_sq_mi": 3672.858,
        "centroid": [
          38.569056,
          -109.528693
        ],
        "county_seat": null
      },
      {
        "county_name": "Iron County",
        "state_fips": "49",
        "county_fips": "49021",
        "population": 57289,
        "land_area_sq_mi": 3296.167,
        "centroid": [
          37.708874,
          -113.076161
        ],
        "county_seat": null
      },
      {
        "county_name": "Juab County",
        "state_fips": "49",
        "county_fips": "49023",
        "population": 11786,
        "land_area_sq_mi": 3391.812,
        "centroid": [
          39.748396,
          -111.878638
        ],
        "county_seat": null
      },
      {
        "county_name": "Kane County",
        "state_fips": "49",
        "county_fips": "49025",
        "population": 7667,
        "land_area_sq_mi": 3994.14,
        "centroid": [
          37.112169,
          -112.452998
        ],
        "county_seat": null
      },
      {
        "county_name": "Millard County",
        "state_fips": "49",
        "county_fips": "49027",
        "population": 12975,
        "land_area_sq_mi": 6785.482,
        "centroid": [
          39.209257,
          -112.485634
        ],
        "county_seat": null
      },
      {
        "county_name": "Morgan County",
        "state_fips": "49",
        "county_fips": "49029",
        "population": 12295,
        "land_area_sq_mi": 609.197,
        "centroid": [
          41.083677,
          -111.724978
        ],
        "county_seat": null
      },
      {
        "county_name": "Piute County",
        "state_fips": "49",
        "county_fips": "49031",
        "population": 1438,
        "land_area_sq_mi": 758.21,
        "centroid": [
          38.277169,
          -112.21441
        ],
        "county_seat": null
      },
      {
        "county_name": "Rich County",
        "state_fips": "49",
        "county_fips": "49033",
        "population": 2510,
        "land_area_sq_mi": 1028.758,
        "centroid": [
          41.776494,
          -111.285765
        ],
        "county_seat": null
      },
      {
        "county_name": "Salt Lake County",
        "state_fips": "49",
        "county_fips": "49035",
        "population": 1185238,
        "land_area_sq_mi": 752.852,
        "centroid": [
          40.638514,
          -111.927686
        ],
        "county_seat": null
      },
      {
        "county_name": "San Juan County",
        "state_fips": "49",
        "county_fips": "49037",
        "population": 14518,
        "land_area_sq_mi": 7823.765,
        "centroid": [
          37.52052,
          -109.545503
        ],
        "county_seat": null
      },
      {
        "county_name": "Sanpete County",
        "state_fips": "49",
        "county_fips": "49039",
        "population": 28437,
        "land_area_sq_mi": 1589.816,
        "centroid": [
          39.384535,
          -111.605199
        ],
        "county_seat": null
      },
      {
        "county_name": "Sevier County",
        "state_fips": "49",
        "county_fips": "49041",
        "population": 21522,
        "land_area_sq_mi": 1910.476,
        "centroid": [
          38.771786,
          -112.044688
        ],
        "county_seat": null
      },
      {
        "county_name": "Summit County",
        "state_fips": "49",
        "county_fips": "49043",
        "population": 42357,
        "land_area_sq_mi": 1870.674,
        "centroid": [
          40.726848,
          -111.470958
        ],
        "county_seat": null
      },
      {
        "county_name": "Tooele County",
        "state_fips": "49",
        "county_fips": "49045",
        "population": 72698,
        "land_area_sq_mi": 7040.271,
        "centroid": [
          40.568237,
          -112.363002
        ],
        "county_seat": null
      },
      {
        "county_name": "Uintah County",
        "state_fips": "49",
        "county_fips": "49047",
        "population": 35620,
        "land_area_sq_mi": 4482.881,
        "centroid": [
          40.426449,
          -109.59027
        ],
        "county_seat": null
      },
      {
        "county_name": "Utah County",
        "state_fips": "49",
        "county_fips": "49049",
        "population": 659399,
        "land_area_sq_mi": 2004.46,
        "centroid": [
          40.278299,
          -111.74994
        ],
        "county_seat": null
      },
      {
        "county_name": "Wasatch County",
        "state_fips": "49",
        "county_fips": "49051",
        "population": 34788,
        "land_area_sq_mi": 1176.952,
        "centroid": [
          40.511436,
          -111.412185
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "49",
        "county_fips": "49053",
        "population": 180279,
        "land_area_sq_mi": 2427.589,
        "centroid": [
          37.13018,
          -113.524041
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "49",
        "county_fips": "49055",
        "population": 2486,
        "land_area_sq_mi": 2461.094,
        "centroid": [
          38.361712,
          -111.473883
        ],
        "county_seat": null
      },
      {
        "county_name": "Weber County",
        "state_fips": "49",
        "county_fips": "49057",
        "population": 262223,
        "land_area_sq_mi": 611.023,
        "centroid": [
          41.227609,
          -111.992699
        ],
        "county_seat": null
      }
    ]
