# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Allen County",
        "state_fips": "20",
        "county_fips": "20001",
        "population": 12526,
        "land_area_sq_mi": 500.297,
        "centroid": [
          37.896944,
          -95.369306
        ],
        "county_seat": null
      },
      {
        "county_name": "Anderson County",
        "state_fips": "20",
        "county_fips": "20003",
        "population": 7836,
        "land_area_sq_mi": 579.641,
        "centroid": [
          38.251802,
          -95.263224
        ],
        "county_seat": null
      },
      {
        "county_name": "Atchison County",
        "state_fips": "20",
        "county_fips": "20005",
        "population": 16348,
        "land_area_sq_mi": 431.174,
        "centroid": [
          39.555375,
          -95.179193
        ],
        "county_seat": null
      },
      {
        "county_name": "Barber County",
        "state_fips": "20",
        "county_fips": "20007",
        "population": 4228,
        "land_area_sq_mi": 1134.075,
        "centroid": [
          37.211912,
          -98.557723
        ],
        "county_seat": null
      },
      {
        "county_name": "Barton County",
        "state_fips": "20",
        "county_fips": "20009",
        "population": 25493,
        "land_area_sq_mi": 895.257,
        "centroid": [
          38.396456,
          -98.75829
        ],
        "county_seat": null
      },
      {
        "county_name": "Bourbon County",
        "state_fips": "20",
        "county_fips": "20011",
        "population": 14360,
        "land_area_sq_mi": 635.461,
        "centroid": [
          37.845974,
          -94.749672
        ],
        "county_seat": null
      },
      {
        "county_name": "Brown County",
        "state_fips": "20",
        "county_fips": "20013",
        "population": 9508,
        "land_area_sq_mi": 570.871,
        "centroid": [
          39.805025,
          -95.551801
        ],
        "county_seat": null
      },
      {
        "county_name": "Butler County",
        "state_fips": "20",
        "county_fips": "20015",
        "population": 67380,
        "land_area_sq_mi": 1429.716,
        "centroid": [
          37.725409,
          -96.99849
        ],
        "county_seat": null
      },
      {
        "county_name": "Chase County",
        "state_fips": "20",
        "county_fips": "20017",
        "population": 2572,
        "land_area_sq_mi": 773.053,
        "centroid": [
          38.358225,
          -96.558338
        ],
        "county_seat": null
      },
      {
        "county_name": "Chautauqua County",
        "state_fips": "20",
        "county_fips": "20019",
        "population": 3379,
        "land_area_sq_mi": 638.881,
        "centroid": [
          37.115752,
          -96.228059
        ],
        "county_seat": null
      },
      {
        "county_name": "Cherokee County",
        "state_fips": "20",
        "county_fips": "20021",
        "population": 19362,
        "land_area_sq_mi": 587.567,
        "centroid": [
          37.114832,
          -94.751725
        ],
        "county_seat": null
      },
      {
        "county_name": "Cheyenne County",
        "state_fips": "20",
        "county_fips": "20023",
        "population": 2616,
        "land_area_sq_mi": 1019.89,
        "centroid": [
          39.769323,
          -101.738091
        ],
        "county_seat": null
      },
      {
        "county_name": "Clark County",
        "state_fips": "20",
        "county_fips": "20025",
        "population": 1991,
        "land_area_sq_mi": 974.638,
        "centroid": [
          37.295814,
          -99.886429
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "20",
        "county_fips": "20027",
        "population": 8117,
        "land_area_sq_mi": 645.298,
        "centroid": [
          39.354338,
          -97.122448
        ],
        "county_seat": null
      },
      {
        "county_name": "Cloud County",
        "state_fips": "20",
        "county_fips": "20029",
        "population": 9032,
        "land_area_sq_mi": 715.342,
        "centroid": [
          39.53486,
          -97.635801
        ],
        "county_seat": null
      },
      {
        "county_name": "Coffey County",
        "state_fips": "20",
        "county_fips": "20031",
        "population": 8360,
        "land_area_sq_mi": 626.885,
        "centroid": [
          38.249077,
          -95.741609
        ],
        "county_seat": null
      },
      {
        "county_name": "Comanche County",
        "state_fips": "20",
        "county_fips": "20033",
        "population": 1689,
        "land_area_sq_mi": 788.298,
        "centroid": [
          37.233664,
          -99.373213
        ],
        "county_seat": null
      },
      {
        "county_name": "Cowley County",
        "state_fips": "20",
        "county_fips": "20035",
        "population": 34549,
        "land_area_sq_mi": 1125.738,
        "centroid": [
          37.17461,
          -96.99836
        ],
        "county_seat": null
      },
      {
        "county_name": "Crawford County",
        "state_fips": "20",
        "county_fips": "20037",
        "population": 38972,
        "land_area_sq_mi": 589.771,
        "centroid": [
          37.438265,
          -94.729385
        ],
        "county_seat": null
      },
      {
        "county_name": "Decatur County",
        "state_fips": "20",
        "county_fips": "20039",
        "population": 2764,
        "land_area_sq_mi": 893.517,
        "centroid": [
          39.804239,
          -100.484373
        ],
        "county_seat": null
      },
      {
        "county_name": "Dickinson County",
        "state_fips": "20",
        "county_fips": "20041",
        "population": 18402,
        "land_area_sq_mi": 847.068,
        "centroid": [
          38.886002,
          -97.152074
        ],
        "county_seat": null
      },
      {
        "county_name": "Doniphan County",
        "state_fips": "20",
        "county_fips": "20043",
        "population": 7510,
        "land_area_sq_mi": 393.475,
        "centroid": [
          39.787452,
          -95.071424
        ],
        "county_seat": null
      },
      {
        "county_name": "Douglas County",
        "state_fips": "20",
        "county_fips": "20045",
        "population": 118785,
        "land_area_sq_mi": 455.764,
        "centroid": [
          38.942493,
          -95.254186
        ],
        "county_seat": null
      },
      {
        "county_name": "Edwards County",
        "state_fips": "20",
        "county_fips": "20047",
        "population": 2907,
        "land_area_sq_mi": 621.894,
        "centroid": [
          37.913198,
          -99.352782
        ],
        "county_seat": null
      },
      {
        "county_name": "Elk County",
        "state_fips": "20",
        "county_fips": "20049",
        "population": 2483,
        "land_area_sq_mi": 644.264,
        "centroid": [
          37.423675,
          -96.239085
        ],
        "county_seat": null
      },
      {
        "county_name": "Ellis County",
        "state_fips": "20",
        "county_fips": "20051",
        "population": 28934,
        "land_area_sq_mi": 899.934,
        "centroid": [
          38.882206,
          -99.330542
        ],
        "county_seat": null
      },
      {
        "county_name": "Ellsworth County",
        "state_fips": "20",
        "county_fips": "20053",
        "population": 6376,
        "land_area_sq_mi": 715.575,
        "centroid": [
          38.725437,
          -98.268058
        ],
        "county_seat": null
      },
      {
        "county_name": "Finney County",
        "state_fips": "20",
        "county_fips": "20055",
        "population": 38470,
        "land_area_sq_mi": 1301.997,
        "centroid": [
          37.977246,
          -100.863047
        ],
        "county_seat": null
      },
      {
        "county_name": "Ford County",
        "state_fips": "20",
        "county_fips": "20057",
        "population": 34287,
        "land_area_sq_mi": 1098.271,
        "centroid": [
          37.753005,
          -99.995523
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "20",
        "county_fips": "20059",
        "population": 25996,
        "land_area_sq_mi": 571.772,
        "centroid": [
          38.603542,
          -95.260357
        ],
        "county_seat": null
      },
      {
        "county_name": "Geary County",
        "state_fips": "20",
        "county_fips": "20061",
        "population": 36739,
        "land_area_sq_mi": 384.652,
        "centroid": [
          39.040483,
          -96.838824
        ],
        "county_seat": null
      },
      {
        "county_name": "Gove County",
        "state_fips": "20",
        "county_fips": "20063",
        "population": 2718,
        "land_area_sq_mi": 1071.666,
        "centroid": [
          39.047079,
          -100.377754
        ],
        "county_seat": null
      },
      {
        "county_name": "Graham County",
        "state_fips": "20",
        "county_fips": "20065",
        "population": 2415,
        "land_area_sq_mi": 898.527,
        "centroid": [
          39.358244,
          -99.855627
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "20",
        "county_fips": "20067",
        "population": 7352,
        "land_area_sq_mi": 574.808,
        "centroid": [
          37.580299,
          -101.351338
        ],
        "county_seat": null
      },
      {
        "county_name": "Gray County",
        "state_fips": "20",
        "county_fips": "20069",
        "population": 5653,
        "land_area_sq_mi": 868.867,
        "centroid": [
          37.724149,
          -100.412286
        ],
        "county_seat": null
      },
      {
        "county_name": "Greeley County",
        "state_fips": "20",
        "county_fips": "20071",
        "population": 1284,
        "land_area_sq_mi": 778.404,
        "centroid": [
          38.483553,
          -101.758084
        ],
        "county_seat": null
      },
      {
        "county_name": "Greenwood County",
        "state_fips": "20",
        "county_fips": "20073",
        "population": 6016,
        "land_area_sq_mi": 1143.304,
        "centroid": [
          37.861919,
          -96.224613
        ],
        "county_seat": null
      },
      {
        "county_name": "Hamilton County",
        "state_fips": "20",
        "county_fips": "20075",
        "population": 2518,
        "land_area_sq_mi": 996.514,
        "centroid": [
          37.98058,
          -101.760582
        ],
        "county_seat": null
      },
      {
        "county_name": "Harper County",
        "state_fips": "20",
        "county_fips": "20077",
        "population": 5485,
        "land_area_sq_mi": 801.274,
        "centroid": [
          37.215327,
          -98.049879
        ],
        "county_seat": null
      },
      {
        "county_name": "Harvey County",
        "state_fips": "20",
        "county_fips": "20079",
        "population": 34024,
        "land_area_sq_mi": 539.756,
        "centroid": [
          38.046143,
          -97.385867
        ],
        "county_seat": null
      },
      {
        "county_name": "Haskell County",
        "state_fips": "20",
        "county_fips": "20081",
        "population": 3780,
        "land_area_sq_mi": 577.521,
        "centroid": [
          37.495004,
          -100.890211
        ],
        "county_seat": null
      },
      {
        "county_name": "Hodgeman County",
        "state_fips": "20",
        "county_fips": "20083",
        "population": 1723,
        "land_area_sq_mi": 859.992,
        "centroid": [
          38.085859,
          -99.860131
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "20",
        "county_fips": "20085",
        "population": 13232,
        "land_area_sq_mi": 656.219,
        "centroid": [
          39.402317,
          -95.752834
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "20",
        "county_fips": "20087",
        "population": 18368,
        "land_area_sq_mi": 532.626,
        "centroid": [
          39.210953,
          -95.397523
        ],
        "county_seat": null
      },
      {
        "county_name": "Jewell County",
        "state_fips": "20",
        "county_fips": "20089",
        "population": 2932,
        "land_area_sq_mi": 909.971,
        "centroid": [
          39.777617,
          -98.198892
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnson County",
        "state_fips": "20",
        "county_fips": "20091",
        "population": 609863,
        "land_area_sq_mi": 473.62,
        "centroid": [
          38.924919,
          -94.740299
        ],
        "county_seat": null
      },
      {
        "county_name": "Kearny County",
        "state_fips": "20",
        "county_fips": "20093",
        "population": 3983,
        "land_area_sq_mi": 870.543,
        "centroid": [
          37.951539,
          -101.24168
        ],
        "county_seat": null
      },
      {
        "county_name": "Kingman County",
        "state_fips": "20",
        "county_fips": "20095",
        "population": 7470,
        "land_area_sq_mi": 863.419,
        "centroid": [
          37.610273,
          -98.098011
        ],
        "county_seat": null
      },
      {
        "county_name": "Kiowa County",
        "state_fips": "20",
        "county_fips": "20097",
        "population": 2460,
        "land_area_sq_mi": 722.64,
        "centroid": [
          37.595999,
          -99.252339
        ],
        "county_seat": null
      },
      {
        "county_name": "Labette County",
        "state_fips": "20",
        "county_fips": "20099",
        "population": 20184,
        "land_area_sq_mi": 645.393,
        "centroid": [
          37.259841,
          -95.262384
        ],
        "county_seat": null
      },
      {
        "county_name": "Lane County",
        "state_fips": "20",
        "county_fips": "20101",
        "population": 1574,
        "land_area_sq_mi": 717.409,
        "centroid": [
          38.504038,
          -100.483419
        ],
        "county_seat": null
      },
      {
        "county_name": "Leavenworth County",
        "state_fips": "20",
        "county_fips": "20103",
        "population": 81881,
        "land_area_sq_mi": 463.408,
        "centroid": [
          39.23513,
          -94.959527
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "20",
        "county_fips": "20105",
        "population": 2939,
        "land_area_sq_mi": 719.4,
        "centroid": [
          39.035019,
          -98.186201
        ],
        "county_seat": null
      },
      {
        "county_name": "Linn County",
        "state_fips": "20",
        "county_fips": "20107",
        "population": 9591,
        "land_area_sq_mi": 594.081,
        "centroid": [
          38.239619,
          -94.800976
        ],
        "county_seat": null
      },
      {
        "county_name": "Logan County",
        "state_fips": "20",
        "county_fips": "20109",
        "population": 2762,
        "land_area_sq_mi": 1072.993,
        "centroid": [
          39.095504,
          -100.926327
        ],
        "county_seat": null
      },
      {
        "county_name": "Lyon County",
        "state_fips": "20",
        "county_fips": "20111",
        "population": 32179,
        "land_area_sq_mi": 847.478,
        "centroid": [
          38.416221,
          -96.17907
        ],
        "county_seat": null
      },
      {
        "county_name": "McPherson County",
        "state_fips": "20",
        "county_fips": "20113",
        "population": 30223,
        "land_area_sq_mi": 898.285,
        "centroid": [
          38.382645,
          -97.646719
        ],
        "county_seat": null
      },
      {
        "county_name": "Marion County",
        "state_fips": "20",
        "county_fips": "20115",
        "population": 11823,
        "land_area_sq_mi": 944.299,
        "centroid": [
          38.324754,
          -97.127529
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "20",
        "county_fips": "20117",
        "population": 10038,
        "land_area_sq_mi": 900.178,
        "centroid": [
          39.800328,
          -96.573926
        ],
        "county_seat": null
      },
      {
        "county_name": "Meade County",
        "state_fips": "20",
        "county_fips": "20119",
        "population": 4055,
        "land_area_sq_mi": 978.083,
        "centroid": [
          37.292243,
          -100.396872
        ],
        "county_seat": null
      },
      {
        "county_name": "Miami County",
        "state_fips": "20",
        "county_fips": "20121",
        "population": 34191,
        "land_area_sq_mi": 575.88,
        "centroid": [
          38.595195,
          -94.83105
        ],
        "county_seat": null
      },
      {
        "county_name": "Mitchell County",
        "state_fips": "20",
        "county_fips": "20123",
        "population": 5796,
        "land_area_sq_mi": 701.792,
        "centroid": [
          39.45426,
          -98.175033
        ],
        "county_seat": null
      },
      {
        "county_name": "Montgomery County",
        "state_fips": "20",
        "county_fips": "20125",
        "population": 31486,
        "land_area_sq_mi": 643.594,
        "centroid": [
          37.143443,
          -95.693873
        ],
        "county_seat": null
      },
      {
        "county_name": "Morris County",
        "state_fips": "20",
        "county_fips": "20127",
        "population": 5386,
        "land_area_sq_mi": 695.343,
        "centroid": [
          38.694354,
          -96.58085
        ],
        "county_seat": null
      },
      {
        "county_name": "Morton County",
        "state_fips": "20",
        "county_fips": "20129",
        "population": 2701,
        "land_area_sq_mi": 729.731,
        "centroid": [
          37.043232,
          -101.840026
        ],
        "county_seat": null
      },
      {
        "county_name": "Nemaha County",
        "state_fips": "20",
        "county_fips": "20131",
        "population": 10273,
        "land_area_sq_mi": 717.427,
        "centroid": [
          39.829395,
          -95.96626
        ],
        "county_seat": null
      },
      {
        "county_name": "Neosho County",
        "state_fips": "20",
        "county_fips": "20133",
        "population": 15904,
        "land_area_sq_mi": 571.481,
        "centroid": [
          37.623786,
          -95.396134
        ],
        "county_seat": null
      },
      {
        "county_name": "Ness County",
        "state_fips": "20",
        "county_fips": "20135",
        "population": 2687,
        "land_area_sq_mi": 1074.739,
        "centroid": [
          38.488254,
          -99.897744
        ],
        "county_seat": null
      },
      {
        "county_name": "Norton County",
        "state_fips": "20",
        "county_fips": "20137",
        "population": 5459,
        "land_area_sq_mi": 878.044,
        "centroid": [
          39.82351,
          -99.876765
        ],
        "county_seat": null
      },
      {
        "county_name": "Osage County",
        "state_fips": "20",
        "county_fips": "20139",
        "population": 15766,
        "land_area_sq_mi": 705.506,
        "centroid": [
          38.699173,
          -95.713137
        ],
        "county_seat": null
      },
      {
        "county_name": "Osborne County",
        "state_fips": "20",
        "county_fips": "20141",
        "population": 3500,
        "land_area_sq_mi": 892.516,
        "centroid": [
          39.425897,
          -98.705316
        ],
        "county_seat": null
      },
      {
        "county_name": "Ottawa County",
        "state_fips": "20",
        "county_fips": "20143",
        "population": 5735,
        "land_area_sq_mi": 720.73,
        "centroid": [
          39.096393,
          -97.682422
        ],
        "county_seat": null
      },
      {
        "county_name": "Pawnee County",
        "state_fips": "20",
        "county_fips": "20145",
        "population": 6253,
        "land_area_sq_mi": 754.263,
        "centroid": [
          38.179763,
          -99.146958
        ],
        "county_seat": null
      },
      {
        "county_name": "Phillips County",
        "state_fips": "20",
        "county_fips": "20147",
        "population": 4981,
        "land_area_sq_mi": 885.871,
        "centroid": [
          39.759487,
          -99.348621
        ],
        "county_seat": null
      },
      {
        "county_name": "Pottawatomie County",
        "state_fips": "20",
        "county_fips": "20149",
        "population": 25348,
        "land_area_sq_mi": 840.735,
        "centroid": [
          39.251723,
          -96.332282
        ],
        "county_seat": null
      },
      {
        "county_name": "Pratt County",
        "state_fips": "20",
        "county_fips": "20151",
        "population": 9157,
        "land_area_sq_mi": 735.039,
        "centroid": [
          37.6448,
          -98.730599
        ],
        "county_seat": null
      },
      {
        "county_name": "Rawlins County",
        "state_fips": "20",
        "county_fips": "20153",
        "population": 2561,
        "land_area_sq_mi": 1069.416,
        "centroid": [
          39.807173,
          -101.050348
        ],
        "county_seat": null
      },
      {
        "county_name": "Reno County",
        "state_fips": "20",
        "county_fips": "20155",
        "population": 61898,
        "land_area_sq_mi": 1255.308,
        "centroid": [
          38.051646,
          -97.931942
        ],
        "county_seat": null
      },
      {
        "county_name": "Republic County",
        "state_fips": "20",
        "county_fips": "20157",
        "population": 4674,
        "land_area_sq_mi": 717.377,
        "centroid": [
          39.817924,
          -97.659071
        ],
        "county_seat": null
      },
      {
        "county_name": "Rice County",
        "state_fips": "20",
        "county_fips": "20159",
        "population": 9427,
        "land_area_sq_mi": 726.235,
        "centroid": [
          38.320405,
          -98.199874
        ],
        "county_seat": null
      },
      {
        "county_name": "Riley County",
        "state_fips": "20",
        "county_fips": "20161",
        "population": 71959,
        "land_area_sq_mi": 609.66,
        "centroid": [
          39.190165,
          -96.632706
        ],
        "county_seat": null
      },
      {
        "county_name": "Rooks County",
        "state_fips": "20",
        "county_fips": "20163",
        "population": 4919,
        "land_area_sq_mi": 890.527,
        "centroid": [
          39.321747,
          -99.314061
        ],
        "county_seat": null
      },
      {
        "county_name": "Rush County",
        "state_fips": "20",
        "county_fips": "20165",
        "population": 2956,
        "land_area_sq_mi": 717.763,
        "centroid": [
          38.527826,
          -99.281206
        ],
        "county_seat": null
      },
      {
        "county_name": "Russell County",
        "state_fips": "20",
        "county_fips": "20167",
        "population": 6691,
        "land_area_sq_mi": 886.26,
        "centroid": [
          38.904218,
          -98.830652
        ],
        "county_seat": null
      },
      {
        "county_name": "Saline County",
        "state_fips": "20",
        "county_fips": "20169",
        "population": 54303,
        "land_area_sq_mi": 720.242,
        "centroid": [
          38.814764,
          -97.605554
        ],
        "county_seat": null
      },
      {
        "county_name": "Scott County",
        "state_fips": "20",
        "county_fips": "20171",
        "population": 5151,
        "land_area_sq_mi": 717.585,
        "centroid": [
          38.481574,
          -100.913143
        ],
        "county_seat": null
      },
      {
        "county_name": "Sedgwick County",
        "state_fips": "20",
        "county_fips": "20173",
        "population": 523824,
        "land_area_sq_mi": 997.001,
        "centroid": [
          37.680269,
          -97.34439
        ],
        "county_seat": null
      },
      {
        "county_name": "Seward County",
        "state_fips": "20",
        "county_fips": "20175",
        "population": 21964,
        "land_area_sq_mi": 639.653,
        "centroid": [
          37.051086,
          -100.918735
        ],
        "county_seat": null
      },
      {
        "county_name": "Shawnee County",
        "state_fips": "20",
        "county_fips": "20177",
        "population": 178909,
        "land_area_sq_mi": 544.012,
        "centroid": [
          39.034789,
          -95.706417
        ],
        "county_seat": null
      },
      {
        "county_name": "Sheridan County",
        "state_fips": "20",
        "county_fips": "20179",
        "population": 2447,
        "land_area_sq_mi": 895.957,
        "centroid": [
          39.368138,
          -100.463405
        ],
        "county_seat": null
      },
      {
        "county_name": "Sherman County",
        "state_fips": "20",
        "county_fips": "20181",
        "population": 5927,
        "land_area_sq_mi": 1056.064,
        "centroid": [
          39.350878,
          -101.726045
        ],
        "county_seat": null
      },
      {
        "county_name": "Smith County",
        "state_fips": "20",
        "county_fips": "20183",
        "population": 3570,
        "land_area_sq_mi": 895.464,
        "centroid": [
          39.770601,
          -98.805608
        ],
        "county_seat": null
      },
      {
        "county_name": "Stafford County",
        "state_fips": "20",
        "county_fips": "20185",
        "population": 4072,
        "land_area_sq_mi": 792.046,
        "centroid": [
          38.005058,
          -98.733831
        ],
        "county_seat": null
      },
      {
        "county_name": "Stanton County",
        "state_fips": "20",
        "county_fips": "20187",
        "population": 2084,
        "land_area_sq_mi": 680.352,
        "centroid": [
          37.565287,
          -101.757372
        ],
        "county_seat": null
      },
      {
        "county_name": "Stevens County",
        "state_fips": "20",
        "county_fips": "20189",
        "population": 5250,
        "land_area_sq_mi": 727.26,
        "centroid": [
          37.187133,
          -101.322543
        ],
        "county_seat": null
      },
      {
        "county_name": "Sumner County",
        "state_fips": "20",
        "county_fips": "20191",
        "population": 22382,
        "land_area_sq_mi": 1181.668,
        "centroid": [
          37.303365,
          -97.406786
        ],
        "county_seat": null
      },
      {
        "county_name": "Thomas County",
        "state_fips": "20",
        "county_fips": "20193",
        "population": 7930,
        "land_area_sq_mi": 1074.687,
        "centroid": [
          39.384656,
          -101.050191
        ],
        "county_seat": null
      },
      {
        "county_name": "Trego County",
        "state_fips": "20",
        "county_fips": "20195",
        "population": 2808,
        "land_area_sq_mi": 889.474,
        "centroid": [
          39.003748,
          -99.881416
        ],
        "county_seat": null
      },
      {
        "county_name": "Wabaunsee County",
        "state_fips": "20",
        "county_fips": "20197",
        "population": 6877,
        "land_area_sq_mi": 794.336,
        "centroid": [
          38.989695,
          -96.178582
        ],
        "county_seat": null
      },
      {
        "county_name": "Wallace County",
        "state_fips": "20",
        "county_fips": "20199",
        "population": 1512,
        "land_area_sq_mi": 913.652,
        "centroid": [
          38.885844,
          -101.761616
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "20",
        "county_fips": "20201",
        "population": 5530,
        "land_area_sq_mi": 894.759,
        "centroid": [
          39.779332,
          -97.048861
        ],
        "county_seat": null
      },
      {
        "county_name": "Wichita County",
        "state_fips": "20",
        "county_fips": "20203",
        "population": 2152,
        "land_area_sq_mi": 718.566,
        "centroid": [
          38.494575,
          -101.349645
        ],
        "county_seat": null
      },
      {
        "county_name": "Wilson County",
        "state_fips": "20",
        "county_fips": "20205",
        "population": 8624,
        "land_area_sq_mi": 570.423,
        "centroid": [
          37.511463,
          -95.739717
        ],
        "county_seat": null
      },
      {
        "county_name": "Woodson County",
        "state_fips": "20",
        "county_fips": "20207",
        "population": 3115,
        "land_area_sq_mi": 497.819,
        "centroid": [
          37.876071,
          -95.735035
        ],
        "county_seat": null
      },
      {
        "county_name": "Wyandotte County",
        "state_fips": "20",
        "county_fips": "20209",
        "population": 169245,
        "land_area_sq_mi": 151.638,
        "centroid": [
          39.106038,
          -94.712818
        ],
        "county_seat": null
      }
    ]
