# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Belknap County",
        "state_fips": "33",
        "county_fips": "33001",
        "population": 63705,
        "land_area_sq_mi": 401.85,
        "centroid": [
          43.518179,
          -71.439516
        ],
        "county_seat": null
      },
      {
        "county_name": "Carroll County",
        "state_fips": "33",
        "county_fips": "33003",
        "population": 50107,
        "land_area_sq_mi": 931.864,
        "centroid": [
          43.810093,
          -71.170079
        ],
        "county_seat": null
      },
      {
        "county_name": "Cheshire County",
        "state_fips": "33",
        "county_fips": "33005",
        "population": 76458,
        "land_area_sq_mi": 706.709,
        "centroid": [
          42.897949,
          -72.260597
        ],
        "county_seat": null
      },
      {
        "county_name": "Coos County",
        "state_fips": "33",
        "county_fips": "33007",
        "population": 31268,
        "land_area_sq_mi": 1794.574,
        "centroid": [
          44.544534,
          -71.3636
        ],
        "county_seat": null
      },
      {
        "county_name": "Grafton County",
        "state_fips": "33",
        "county_fips": "33009",
        "population": 91118,
        "land_area_sq_mi": 1708.599,
        "centroid": [
          43.83744,
          -71.957176
        ],
        "county_seat": null
      },
      {
        "county_name": "Hillsborough County",
        "state_fips": "33",
        "county_fips": "33011",
        "population": 422937,
        "land_area_sq_mi": 876.537,
        "centroid": [
          42.879412,
          -71.531546
        ],
        "county_seat": null
      },
      {
        "county_name": "Merrimack County",
        "state_fips": "33",
        "county_fips": "33013",
        "population": 153808,
        "land_area_sq_mi": 932.891,
        "centroid": [
          43.244048,
          -71.586768
        ],
        "county_seat": null
      },
      {
        "county_name": "Rockingham County",
        "state_fips": "33",
        "county_fips": "33015",
        "population": 314176,
        "land_area_sq_mi": 695.429,
        "centroid": [
          42.937487,
          -71.105861
        ],
        "county_seat": null
      },
      {
        "county_name": "Strafford County",
        "state_fips": "33",
        "county_fips": "33017",
        "population": 130889,
        "land_area_sq_mi": 367.463,
        "centroid": [
          43.246137,
          -70.954351
        ],
        "county_seat": null
      },
      {
        "county_name": "Sullivan County",
        "state_fips": "33",
        "county_fips": "33019",
        "population": 43063,
        "land_area_sq_mi": 537.876,
        "centroid": [
          43.370229,
          -72.256473
        ],
        "county_seat": null
      }
    ]
