# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Aleutians East County",
        "state_fips": "02",
        "county_fips": "02013",
        "population": 3420,
        "land_area_sq_mi": 6986.254,
        "centroid": [
          54.672887,
          -163.763729
        ],
        "county_seat": null
      },
      {
        "county_name": "Aleutians West County",
        "state_fips": "02",
        "county_fips": "02016",
        "population": 5232,
        "land_area_sq_mi": 4393.051,
        "centroid": [
          54.024627,
          -168.148047
        ],
        "county_seat": null
      },
      {
        "county_name": "Anchorage County",
        "state_fips": "02",
        "county_fips": "02020",
        "population": 291247,
        "land_area_sq_mi": 1707.069,
        "centroid": [
          61.191547,
          -149.792287
        ],
        "county_seat": null
      },
      {
        "county_name": "Bethel County",
        "state_fips": "02",
        "county_fips": "02050",
        "population": 18666,
        "land_area_sq_mi": 40660.586,
        "centroid": [
          60.667568,
          -162.178288
        ],
        "county_seat": null
      },
      {
        "county_name": "Bristol Bay County",
        "state_fips": "02",
        "county_fips": "02060",
        "population": 844,
        "land_area_sq_mi": 481.382,
        "centroid": [
          58.733456,
          -156.833611
        ],
        "county_seat": null
      },
      {
        "county_name": "Chugach County",
        "state_fips": "02",
        "county_fips": "02063",
        "population": 7102,
        "land_area_sq_mi": 9575.39,
        "centroid": [
          60.881369,
          -146.199156
        ],
        "county_seat": null
      },
      {
        "county_name": "Copper River County",
        "state_fips": "02",
        "county_fips": "02066",
        "population": 2617,
        "land_area_sq_mi": 24646.759,
        "centroid": [
          62.060769,
          -145.032939
        ],
        "county_seat": null
      },
      {
        "county_name": "Denali County",
        "state_fips": "02",
        "county_fips": "02068",
        "population": 1619,
        "land_area_sq_mi": 12641.049,
        "centroid": [
          63.86431,
          -149.027498
        ],
        "county_seat": null
      },
      {
        "county_name": "Dillingham County",
        "state_fips": "02",
        "county_fips": "02070",
        "population": 4857,
        "land_area_sq_mi": 18335.796,
        "centroid": [
          59.128804,
          -158.75132
        ],
        "county_seat": null
      },
      {
        "county_name": "Fairbanks North Star County",
        "state_fips": "02",
        "county_fips": "02090",
        "population": 95655,
        "land_area_sq_mi": 7334.824,
        "centroid": [
          64.831239,
          -147.623249
        ],
        "county_seat": null
      },
      {
        "county_name": "Haines County",
        "state_fips": "02",
        "county_fips": "02100",
        "population": 2080,
        "land_area_sq_mi": 2334.932,
        "centroid": [
          59.234185,
          -135.497336
        ],
        "county_seat": null
      },
      {
        "county_name": "Hoonah-Angoon County",
        "state_fips": "02",
        "county_fips": "02105",
        "population": 2365,
        "land_area_sq_mi": 6560.319,
        "centroid": [
          58.123876,
          -135.423534
        ],
        "county_seat": null
      },
      {
        "county_name": "Juneau County",
        "state_fips": "02",
        "county_fips": "02110",
        "population": 32255,
        "land_area_sq_mi": 2702.924,
        "centroid": [
          58.360173,
          -134.533023
        ],
        "county_seat": null
      },
      {
        "county_name": "Kenai Peninsula County",
        "state_fips": "02",
        "county_fips": "02122",
        "population": 58799,
        "land_area_sq_mi": 16017.581,
        "centroid": [
          60.283998,
          -151.068103
        ],
        "county_seat": null
      },
      {
        "county_name": "Ketchikan Gateway County",
        "state_fips": "02",
        "county_fips": "02130",
        "population": 13948,
        "land_area_sq_mi": 4857.091,
        "centroid": [
          55.369105,
          -131.678418
        ],
        "county_seat": null
      },
      {
        "county_name": "Kodiak Island County",
        "state_fips": "02",
        "county_fips": "02150",
        "population": 13101,
        "land_area_sq_mi": 6689.486,
        "centroid": [
          57.774607,
          -152.454785
        ],
        "county_seat": null
      },
      {
        "county_name": "Kusilvak County",
        "state_fips": "02",
        "county_fips": "02158",
        "population": 8368,
        "land_area_sq_mi": 17077.965,
        "centroid": [
          62.076819,
          -164.34049
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake and Peninsula County",
        "state_fips": "02",
        "county_fips": "02164",
        "population": 1476,
        "land_area_sq_mi": 23831.019,
        "centroid": [
          58.617154,
          -156.27339
        ],
        "county_seat": null
      },
      {
        "county_name": "Matanuska-Susitna County",
        "state_fips": "02",
        "county_fips": "02170",
        "population": 107081,
        "land_area_sq_mi": 24707.334,
        "centroid": [
          61.607247,
          -149.432649
        ],
        "county_seat": null
      },
      {
        "county_name": "Nome County",
        "state_fips": "02",
        "county_fips": "02180",
        "population": 10046,
        "land_area_sq_mi": 22969.694,
        "centroid": [
          64.431631,
          -165.269108
        ],
        "county_seat": null
      },
      {
        "county_name": "North Slope County",
        "state_fips": "02",
        "county_fips": "02185",
        "population": 11031,
        "land_area_sq_mi": 88792.798,
        "centroid": [
          70.480816,
          -155.295377
        ],
        "county_seat": null
      },
      {
        "county_name": "Northwest Arctic County",
        "state_fips": "02",
        "county_fips": "02188",
        "population": 7793,
        "land_area_sq_mi": 35671.697,
        "centroid": [
          66.897051,
          -161.582978
        ],
        "county_seat": null
      },
      {
        "county_name": "Petersburg County",
        "state_fips": "02",
        "county_fips": "02195",
        "population": 3398,
        "land_area_sq_mi": 2900.889,
        "centroid": [
          56.79507,
          -132.943575
        ],
        "county_seat": null
      },
      {
        "county_name": "Prince of Wales-Hyder County",
        "state_fips": "02",
        "county_fips": "02198",
        "population": 5753,
        "land_area_sq_mi": 5267.636,
        "centroid": [
          55.59077,
          -132.668824
        ],
        "county_seat": null
      },
      {
        "county_name": "Sitka County",
        "state_fips": "02",
        "county_fips": "02220",
        "population": 8458,
        "land_area_sq_mi": 2870.101,
        "centroid": [
          57.062777,
          -135.335988
        ],
        "county_seat": null
      },
      {
        "county_name": "Skagway County",
        "state_fips": "02",
        "county_fips": "02230",
        "population": 1240,
        "land_area_sq_mi": 442.928,
        "centroid": [
          59.465893,
          -135.310551
        ],
        "county_seat": null
      },
      {
        "county_name": "Southeast Fairbanks County",
        "state_fips": "02",
        "county_fips": "02240",
        "population": 6808,
        "land_area_sq_mi": 24832.27,
        "centroid": [
          63.861551,
          -144.698751
        ],
        "county_seat": null
      },
      {
        "county_name": "Wrangell County",
        "state_fips": "02",
        "county_fips": "02275",
        "population": 2127,
        "land_area_sq_mi": 2556.097,
        "centroid": [
          56.426145,
          -132.355422
        ],
        "county_seat": null
      },
      {
        "county_name": "Yakutat County",
        "state_fips": "02",
        "county_fips": "02282",
        "population": 662,
        "land_area_sq_mi": 7627.587,
        "centroid": [
          59.545059,
          -139.714907
        ],
        "county_seat": null
      },
      {
        "county_name": "Yukon-Koyukuk County",
        "state_fips": "02",
        "county_fips": "02290",
        "population": 5343,
        "land_area_sq_mi": 145769.125,
        "centroid": [
          64.966051,
          -152.827744
        ],
        "county_seat": null
      }
    ]
