# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Beaverhead County",
        "state_fips": "30",
        "county_fips": "30001",
        "population": 9371,
        "land_area_sq_mi": 5542.687,
        "centroid": [
          45.225028,
          -112.693549
        ],
        "county_seat": null
      },
      {
        "county_name": "Big Horn County",
        "state_fips": "30",
        "county_fips": "30003",
        "population": 13124,
        "land_area_sq_mi": 4997.778,
        "centroid": [
          45.568552,
          -107.499673
        ],
        "county_seat": null
      },
      {
        "county_name": "Blaine County",
        "state_fips": "30",
        "county_fips": "30005",
        "population": 7044,
        "land_area_sq_mi": 4227.517,
        "centroid": [
          48.432419,
          -108.871588
        ],
        "county_seat": null
      },
      {
        "county_name": "Broadwater County",
        "state_fips": "30",
        "county_fips": "30007",
        "population": 6774,
        "land_area_sq_mi": 1192.359,
        "centroid": [
          46.281619,
          -111.543362
        ],
        "county_seat": null
      },
      {
        "county_name": "Carbon County",
        "state_fips": "30",
        "county_fips": "30009",
        "population": 10473,
        "land_area_sq_mi": 2047.889,
        "centroid": [
          45.322269,
          -109.084845
        ],
        "county_seat": null
      },
      {
        "county_name": "Carter County",
        "state_fips": "30",
        "county_fips": "30011",
        "population": 1415,
        "land_area_sq_mi": 3340.477,
        "centroid": [
          45.687353,
          -104.525341
        ],
        "county_seat": null
      },
      {
        "county_name": "Cascade County",
        "state_fips": "30",
        "county_fips": "30013",
        "population": 84414,
        "land_area_sq_mi": 2698.206,
        "centroid": [
          47.491558,
          -111.306586
        ],
        "county_seat": null
      },
      {
        "county_name": "Chouteau County",
        "state_fips": "30",
        "county_fips": "30015",
        "population": 5895,
        "land_area_sq_mi": 3972.52,
        "centroid": [
          47.962552,
          -110.386252
        ],
        "county_seat": null
      },
      {
        "county_name": "Custer County",
        "state_fips": "30",
        "county_fips": "30017",
        "population": 11867,
        "land_area_sq_mi": 3783.309,
        "centroid": [
          46.401678,
          -105.814642
        ],
        "county_seat": null
      },
      {
        "county_name": "Daniels County",
        "state_fips": "30",
        "county_fips": "30019",
        "population": 1661,
        "land_area_sq_mi": 1426.27,
        "centroid": [
          48.783637,
          -105.431739
        ],
        "county_seat": null
      },
      {
        "county_name": "Dawson County",
        "state_fips": "30",
        "county_fips": "30021",
        "population": 8940,
        "land_area_sq_mi": 2371.926,
        "centroid": [
          47.137216,
          -104.748806
        ],
        "county_seat": null
      },
      {
        "county_name": "Deer Lodge County",
        "state_fips": "30",
        "county_fips": "30023",
        "population": 9421,
        "land_area_sq_mi": 736.683,
        "centroid": [
          46.135851,
          -112.955566
        ],
        "county_seat": null
      },
      {
        "county_name": "Fallon County",
        "state_fips": "30",
        "county_fips": "30025",
        "population": 3049,
        "land_area_sq_mi": 1620.595,
        "centroid": [
          46.360506,
          -104.316077
        ],
        "county_seat": null
      },
      {
        "county_name": "Fergus County",
        "state_fips": "30",
        "county_fips": "30027",
        "population": 11446,
        "land_area_sq_mi": 4339.329,
        "centroid": [
          47.092022,
          -109.4146
        ],
        "county_seat": null
      },
      {
        "county_name": "Flathead County",
        "state_fips": "30",
        "county_fips": "30029",
        "population": 104357,
        "land_area_sq_mi": 5087.302,
        "centroid": [
          48.24738,
          -114.28093
        ],
        "county_seat": null
      },
      {
        "county_name": "Gallatin County",
        "state_fips": "30",
        "county_fips": "30031",
        "population": 118960,
        "land_area_sq_mi": 2605.354,
        "centroid": [
          45.682956,
          -111.128767
        ],
        "county_seat": null
      },
      {
        "county_name": "Garfield County",
        "state_fips": "30",
        "county_fips": "30033",
        "population": 1173,
        "land_area_sq_mi": 4676.56,
        "centroid": [
          47.309975,
          -106.946674
        ],
        "county_seat": null
      },
      {
        "county_name": "Glacier County",
        "state_fips": "30",
        "county_fips": "30035",
        "population": 13778,
        "land_area_sq_mi": 2995.151,
        "centroid": [
          48.601084,
          -112.803122
        ],
        "county_seat": null
      },
      {
        "county_name": "Golden Valley County",
        "state_fips": "30",
        "county_fips": "30037",
        "population": 823,
        "land_area_sq_mi": 1174.423,
        "centroid": [
          46.297881,
          -109.120778
        ],
        "county_seat": null
      },
      {
        "county_name": "Granite County",
        "state_fips": "30",
        "county_fips": "30039",
        "population": 3309,
        "land_area_sq_mi": 1727.162,
        "centroid": [
          46.445392,
          -113.319927
        ],
        "county_seat": null
      },
      {
        "county_name": "Hill County",
        "state_fips": "30",
        "county_fips": "30041",
        "population": 16309,
        "land_area_sq_mi": 2899.396,
        "centroid": [
          48.511678,
          -109.767061
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "30",
        "county_fips": "30043",
        "population": 12085,
        "land_area_sq_mi": 1656.997,
        "centroid": [
          46.268426,
          -112.045462
        ],
        "county_seat": null
      },
      {
        "county_name": "Judith Basin County",
        "state_fips": "30",
        "county_fips": "30045",
        "population": 2023,
        "land_area_sq_mi": 1869.687,
        "centroid": [
          47.094038,
          -110.171269
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake County",
        "state_fips": "30",
        "county_fips": "30047",
        "population": 31134,
        "land_area_sq_mi": 1490.47,
        "centroid": [
          47.608393,
          -114.123168
        ],
        "county_seat": null
      },
      {
        "county_name": "Lewis and Clark County",
        "state_fips": "30",
        "county_fips": "30049",
        "population": 70973,
        "land_area_sq_mi": 3458.381,
        "centroid": [
          46.646621,
          -112.019644
        ],
        "county_seat": null
      },
      {
        "county_name": "Liberty County",
        "state_fips": "30",
        "county_fips": "30051",
        "population": 1959,
        "land_area_sq_mi": 1429.988,
        "centroid": [
          48.538044,
          -110.985198
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "30",
        "county_fips": "30053",
        "population": 19677,
        "land_area_sq_mi": 3612.559,
        "centroid": [
          48.553306,
          -115.42649
        ],
        "county_seat": null
      },
      {
        "county_name": "McCone County",
        "state_fips": "30",
        "county_fips": "30055",
        "population": 1729,
        "land_area_sq_mi": 2642.225,
        "centroid": [
          47.569721,
          -105.638886
        ],
        "county_seat": null
      },
      {
        "county_name": "Madison County",
        "state_fips": "30",
        "county_fips": "30057",
        "population": 8623,
        "land_area_sq_mi": 3588.156,
        "centroid": [
          45.419014,
          -111.922649
        ],
        "county_seat": null
      },
      {
        "county_name": "Meagher County",
        "state_fips": "30",
        "county_fips": "30059",
        "population": 1927,
        "land_area_sq_mi": 2391.868,
        "centroid": [
          46.529828,
          -110.881517
        ],
        "county_seat": null
      },
      {
        "county_name": "Mineral County",
        "state_fips": "30",
        "county_fips": "30061",
        "population": 4535,
        "land_area_sq_mi": 1219.619,
        "centroid": [
          47.182752,
          -114.894335
        ],
        "county_seat": null
      },
      {
        "county_name": "Missoula County",
        "state_fips": "30",
        "county_fips": "30063",
        "population": 117922,
        "land_area_sq_mi": 2593.011,
        "centroid": [
          46.875546,
          -114.021512
        ],
        "county_seat": null
      },
      {
        "county_name": "Musselshell County",
        "state_fips": "30",
        "county_fips": "30065",
        "population": 4730,
        "land_area_sq_mi": 1868.958,
        "centroid": [
          46.420108,
          -108.483111
        ],
        "county_seat": null
      },
      {
        "county_name": "Park County",
        "state_fips": "30",
        "county_fips": "30067",
        "population": 17191,
        "land_area_sq_mi": 2802.479,
        "centroid": [
          45.604896,
          -110.596931
        ],
        "county_seat": null
      },
      {
        "county_name": "Petroleum County",
        "state_fips": "30",
        "county_fips": "30069",
        "population": 496,
        "land_area_sq_mi": 1655.625,
        "centroid": [
          47.012154,
          -108.317862
        ],
        "county_seat": null
      },
      {
        "county_name": "Phillips County",
        "state_fips": "30",
        "county_fips": "30071",
        "population": 4217,
        "land_area_sq_mi": 5140.422,
        "centroid": [
          48.367246,
          -107.86655
        ],
        "county_seat": null
      },
      {
        "county_name": "Pondera County",
        "state_fips": "30",
        "county_fips": "30073",
        "population": 5898,
        "land_area_sq_mi": 1624.567,
        "centroid": [
          48.211424,
          -112.157767
        ],
        "county_seat": null
      },
      {
        "county_name": "Powder River County",
        "state_fips": "30",
        "county_fips": "30075",
        "population": 1694,
        "land_area_sq_mi": 3298.196,
        "centroid": [
          45.438494,
          -105.544609
        ],
        "county_seat": null
      },
      {
        "county_name": "Powell County",
        "state_fips": "30",
        "county_fips": "30077",
        "population": 6946,
        "land_area_sq_mi": 2326.043,
        "centroid": [
          46.450646,
          -112.757979
        ],
        "county_seat": null
      },
      {
        "county_name": "Prairie County",
        "state_fips": "30",
        "county_fips": "30079",
        "population": 1088,
        "land_area_sq_mi": 1736.603,
        "centroid": [
          46.809714,
          -105.276222
        ],
        "county_seat": null
      },
      {
        "county_name": "Ravalli County",
        "state_fips": "30",
        "county_fips": "30081",
        "population": 44174,
        "land_area_sq_mi": 2390.967,
        "centroid": [
          46.358548,
          -114.111357
        ],
        "county_seat": null
      },
      {
        "county_name": "Richland County",
        "state_fips": "30",
        "county_fips": "30083",
        "population": 11491,
        "land_area_sq_mi": 2084.556,
        "centroid": [
          47.72072,
          -104.204227
        ],
        "county_seat": null
      },
      {
        "county_name": "Roosevelt County",
        "state_fips": "30",
        "county_fips": "30085",
        "population": 10794,
        "land_area_sq_mi": 2354.602,
        "centroid": [
          48.134392,
          -105.212553
        ],
        "county_seat": null
      },
      {
        "county_name": "Rosebud County",
        "state_fips": "30",
        "county_fips": "30087",
        "population": 8329,
        "land_area_sq_mi": 5008.135,
        "centroid": [
          45.902894,
          -106.612238
        ],
        "county_seat": null
      },
      {
        "county_name": "Sanders County",
        "state_fips": "30",
        "county_fips": "30089",
        "population": 12400,
        "land_area_sq_mi": 2760.4,
        "centroid": [
          47.635009,
          -115.175789
        ],
        "county_seat": null
      },
      {
        "county_name": "Sheridan County",
        "state_fips": "30",
        "county_fips": "30091",
        "population": 3539,
        "land_area_sq_mi": 1676.941,
        "centroid": [
          48.734101,
          -104.49367
        ],
        "county_seat": null
      },
      {
        "county_name": "Silver Bow County",
        "state_fips": "30",
        "county_fips": "30093",
        "population": 35133,
        "land_area_sq_mi": 717.99,
        "centroid": [
          45.98746,
          -112.525517
        ],
        "county_seat": null
      },
      {
        "county_name": "Stillwater County",
        "state_fips": "30",
        "county_fips": "30095",
        "population": 8963,
        "land_area_sq_mi": 1796.531,
        "centroid": [
          45.615383,
          -109.238178
        ],
        "county_seat": null
      },
      {
        "county_name": "Sweet Grass County",
        "state_fips": "30",
        "county_fips": "30097",
        "population": 3678,
        "land_area_sq_mi": 1855.536,
        "centroid": [
          45.829391,
          -109.91651
        ],
        "county_seat": null
      },
      {
        "county_name": "Teton County",
        "state_fips": "30",
        "county_fips": "30099",
        "population": 6226,
        "land_area_sq_mi": 2271.616,
        "centroid": [
          47.762524,
          -112.039341
        ],
        "county_seat": null
      },
      {
        "county_name": "Toole County",
        "state_fips": "30",
        "county_fips": "30101",
        "population": 4971,
        "land_area_sq_mi": 1914.864,
        "centroid": [
          48.578065,
          -111.850473
        ],
        "county_seat": null
      },
      {
        "county_name": "Treasure County",
        "state_fips": "30",
        "county_fips": "30103",
        "population": 762,
        "land_area_sq_mi": 977.801,
        "centroid": [
          46.247085,
          -107.247111
        ],
        "county_seat": null
      },
      {
        "county_name": "Valley County",
        "state_fips": "30",
        "county_fips": "30105",
        "population": 7578,
        "land_area_sq_mi": 4926.115,
        "centroid": [
          48.236249,
          -106.541586
        ],
        "county_seat": null
      },
      {
        "county_name": "Wheatland County",
        "state_fips": "30",
        "county_fips": "30107",
        "population": 2069,
        "land_area_sq_mi": 1422.481,
        "centroid": [
          46.454552,
          -109.845461
        ],
        "county_seat": null
      },
      {
        "county_name": "Wibaux County",
        "state_fips": "30",
        "county_fips": "30109",
        "population": 937,
        "land_area_sq_mi": 889.571,
        "centroid": [
          46.969955,
          -104.191241
        ],
        "county_seat": null
      },
      {
        "county_name": "Yellowstone County",
        "state_fips": "30",
        "county_fips": "30111",
        "population": 164731,
        "land_area_sq_mi": 2633.4,
        "centroid": [
          45.789945,
          -108.546051
        ],
        "county_seat": null
      }
    ]
