# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Albany County",
        "state_fips": "56",
        "county_fips": "56001",
        "population": 37066,
        "land_area_sq_mi": 4274.175,
        "centroid": [
          41.313442,
          -105.596073
        ],
        "county_seat": null
      },
      {
        "county_name": "Big Horn County",
        "state_fips": "56",
        "county_fips": "56003",
        "population": 11521,
        "land_area_sq_mi": 3136.957,
        "centroid": [
          44.635296,
          -108.250971
        ],
        "county_seat": null
      },
      {
        "county_name": "Campbell County",
        "state_fips": "56",
        "county_fips": "56005",
        "population": 47026,
        "land_area_sq_mi": 4802.065,
        "centroid": [
          44.257046,
          -105.495519
        ],
        "county_seat": null
      },
      {
        "county_name": "Carbon County",
        "state_fips": "56",
        "county_fips": "56007",
        "population": 14537,
        "land_area_sq_mi": 7897.746,
        "centroid": [
          41.659869,
          -107.078124
        ],
        "county_seat": null
      },
      {
        "county_name": "Converse County",
        "state_fips": "56",
        "county_fips": "56009",
        "population": 13751,
        "land_area_sq_mi": 4254.994,
        "centroid": [
          42.788528,
          -105.520738
        ],
        "county_seat": null
      },
      {
        "county_name": "Crook County",
        "state_fips": "56",
        "county_fips": "56011",
        "population": 7181,
        "land_area_sq_mi": 2854.48,
        "centroid": [
          44.434922,
          -104.619744
        ],
        "county_seat": null
      },
      {
        "county_name": "Fremont County",
        "state_fips": "56",
        "county_fips": "56013",
        "population": 39234,
        "land_area_sq_mi": 9183.597,
        "centroid": [
          43.010698,
          -108.609469
        ],
        "county_seat": null
      },
      {
        "county_name": "Goshen County",
        "state_fips": "56",
        "county_fips": "56015",
        "population": 12498,
        "land_area_sq_mi": 2225.613,
        "centroid": [
          42.050142,
          -104.220172
        ],
        "county_seat": null
      },
      {
        "county_name": "Hot Springs County",
        "state_fips": "56",
        "county_fips": "56017",
        "population": 4621,
        "land_area_sq_mi": 2004.431,
        "centroid": [
          43.661523,
          -108.232641
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnson County",
        "state_fips": "56",
        "county_fips": "56019",
        "population": 8447,
        "land_area_sq_mi": 4154.152,
        "centroid": [
          44.288278,
          -106.695709
        ],
        "county_seat": null
      },
      {
        "county_name": "Laramie County",
        "state_fips": "56",
        "county_fips": "56021",
        "population": 100512,
        "land_area_sq_mi": 2685.864,
        "centroid": [
          41.153937,
          -104.771336
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "56",
        "county_fips": "56023",
        "population": 19581,
        "land_area_sq_mi": 4075.337,
        "centroid": [
          42.648291,
          -110.872872
        ],
        "county_seat": null
      },
      {
        "county_name": "Natrona County",
        "state_fips": "56",
        "county_fips": "56025",
        "population": 79955,
        "land_area_sq_mi": 5340.537,
        "centroid": [
          42.842184,
          -106.335315
        ],
        "county_seat": null
      },
      {
        "county_name": "Niobrara County",
        "state_fips": "56",
        "county_fips": "56027",
        "population": 2467,
        "land_area_sq_mi": 2626.028,
        "centroid": [
          42.810897,
          -104.450987
        ],
        "county_seat": null
      },
      {
        "county_name": "Park County",
        "state_fips": "56",
        "county_fips": "56029",
        "population": 29624,
        "land_area_sq_mi": 6939.039,
        "centroid": [
          44.614008,
          -108.97254
        ],
        "county_seat": null
      },
      {
        "county_name": "Platte County",
        "state_fips": "56",
        "county_fips": "56031",
        "population": 8605,
        "land_area_sq_mi": 2081.459,
        "centroid": [
          42.106509,
          -104.929825
        ],
        "county_seat": null
      },
      {
        "county_name": "Sheridan County",
        "state_fips": "56",
        "county_fips": "56033",
        "population": 30921,
        "land_area_sq_mi": 2523.361,
        "centroid": [
          44.780986,
          -106.977846
        ],
        "county_seat": null
      },
      {
        "county_name": "Sublette County",
        "state_fips": "56",
        "county_fips": "56035",
        "population": 8728,
        "land_area_sq_mi": 4886.482,
        "centroid": [
          42.807278,
          -109.943507
        ],
        "county_seat": null
      },
      {
        "county_name": "Sweetwater County",
        "state_fips": "56",
        "county_fips": "56037",
        "population": 42272,
        "land_area_sq_mi": 10426.981,
        "centroid": [
          41.580564,
          -109.302521
        ],
        "county_seat": null
      },
      {
        "county_name": "Teton County",
        "state_fips": "56",
        "county_fips": "56039",
        "population": 23331,
        "land_area_sq_mi": 3996.846,
        "centroid": [
          43.491744,
          -110.785815
        ],
        "county_seat": null
      },
      {
        "county_name": "Uinta County",
        "state_fips": "56",
        "county_fips": "56041",
        "population": 20450,
        "land_area_sq_mi": 2081.726,
        "centroid": [
          41.271502,
          -110.760395
        ],
        "county_seat": null
      },
      {
        "county_name": "Washakie County",
        "state_fips": "56",
        "county_fips": "56043",
        "population": 7685,
        "land_area_sq_mi": 2238.679,
        "centroid": [
          44.012223,
          -107.905059
        ],
        "county_seat": null
      },
      {
        "county_name": "Weston County",
        "state_fips": "56",
        "county_fips": "56045",
        "population": 6838,
        "land_area_sq_mi": 2398.005,
        "centroid": [
          43.908449,
          -104.304384
        ],
        "county_seat": null
      }
    ]
