# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adair County",
        "state_fips": "19",
        "county_fips": "19001",
        "population": 7496,
        "land_area_sq_mi": 569.271,
        "centroid": [
          41.347726,
          -94.478337
        ],
        "county_seat": null
      },
      {
        "county_name": "Adams County",
        "state_fips": "19",
        "county_fips": "19003",
        "population": 3704,
        "land_area_sq_mi": 423.433,
        "centroid": [
          41.007205,
          -94.708824
        ],
        "county_seat": null
      },
      {
        "county_name": "Allamakee County",
        "state_fips": "19",
        "county_fips": "19005",
        "population": 14061,
        "land_area_sq_mi": 639.071,
        "centroid": [
          43.252971,
          -91.42476
        ],
        "county_seat": null
      },
      {
        "county_name": "Appanoose County",
        "state_fips": "19",
        "county_fips": "19007",
        "population": 12317,
        "land_area_sq_mi": 497.299,
        "centroid": [
          40.741265,
          -92.864741
        ],
        "county_seat": null
      },
      {
        "county_name": "Audubon County",
        "state_fips": "19",
        "county_fips": "19009",
        "population": 5674,
        "land_area_sq_mi": 442.96,
        "centroid": [
          41.675888,
          -94.925428
        ],
        "county_seat": null
      },
      {
        "county_name": "Benton County",
        "state_fips": "19",
        "county_fips": "19011",
        "population": 25575,
        "land_area_sq_mi": 716.102,
        "centroid": [
          42.063318,
          -92.013283
        ],
        "county_seat": null
      },
      {
        "county_name": "Black Hawk County",
        "state_fips": "19",
        "county_fips": "19013",
        "population": 131144,
        "land_area_sq_mi": 565.773,
        "centroid": [
          42.490207,
          -92.37179
        ],
        "county_seat": null
      },
      {
        "county_name": "Boone County",
        "state_fips": "19",
        "county_fips": "19015",
        "population": 26715,
        "land_area_sq_mi": 570.461,
        "centroid": [
          42.026222,
          -93.892211
        ],
        "county_seat": null
      },
      {
        "county_name": "Bremer County",
        "state_fips": "19",
        "county_fips": "19017",
        "population": 24988,
        "land_area_sq_mi": 435.479,
        "centroid": [
          42.740346,
          -92.380697
        ],
        "county_seat": null
      },
      {
        "county_name": "Buchanan County",
        "state_fips": "19",
        "county_fips": "19019",
        "population": 20565,
        "land_area_sq_mi": 571.084,
        "centroid": [
          42.48513,
          -91.901131
        ],
        "county_seat": null
      },
      {
        "county_name": "Buena Vista County",
        "state_fips": "19",
        "county_fips": "19021",
        "population": 20823,
        "land_area_sq_mi": 574.899,
        "centroid": [
          42.676707,
          -95.184296
        ],
        "county_seat": null
      },
      {
        "county_name": "Butler County",
        "state_fips": "19",
        "county_fips": "19023",
        "population": 14334,
        "land_area_sq_mi": 580.138,
        "centroid": [
          42.701602,
          -92.758281
        ],
        "county_seat": null
      },
      {
        "county_name": "Calhoun County",
        "state_fips": "19",
        "county_fips": "19025",
        "population": 9927,
        "land_area_sq_mi": 569.846,
        "centroid": [
          42.39777,
          -94.623179
        ],
        "county_seat": null
      },
      {
        "county_name": "Carroll County",
        "state_fips": "19",
        "county_fips": "19027",
        "population": 20760,
        "land_area_sq_mi": 569.453,
        "centroid": [
          42.039462,
          -94.867701
        ],
        "county_seat": null
      },
      {
        "county_name": "Cass County",
        "state_fips": "19",
        "county_fips": "19029",
        "population": 13127,
        "land_area_sq_mi": 564.258,
        "centroid": [
          41.366511,
          -94.977692
        ],
        "county_seat": null
      },
      {
        "county_name": "Cedar County",
        "state_fips": "19",
        "county_fips": "19031",
        "population": 18505,
        "land_area_sq_mi": 579.462,
        "centroid": [
          41.756011,
          -91.140408
        ],
        "county_seat": null
      },
      {
        "county_name": "Cerro Gordo County",
        "state_fips": "19",
        "county_fips": "19033",
        "population": 43127,
        "land_area_sq_mi": 568.302,
        "centroid": [
          43.135216,
          -93.246108
        ],
        "county_seat": null
      },
      {
        "county_name": "Cherokee County",
        "state_fips": "19",
        "county_fips": "19035",
        "population": 11658,
        "land_area_sq_mi": 576.907,
        "centroid": [
          42.751225,
          -95.591928
        ],
        "county_seat": null
      },
      {
        "county_name": "Chickasaw County",
        "state_fips": "19",
        "county_fips": "19037",
        "population": 12012,
        "land_area_sq_mi": 504.324,
        "centroid": [
          43.038731,
          -92.342847
        ],
        "county_seat": null
      },
      {
        "county_name": "Clarke County",
        "state_fips": "19",
        "county_fips": "19039",
        "population": 9748,
        "land_area_sq_mi": 431.111,
        "centroid": [
          41.034767,
          -93.783479
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "19",
        "county_fips": "19041",
        "population": 16384,
        "land_area_sq_mi": 567.238,
        "centroid": [
          43.127358,
          -95.159344
        ],
        "county_seat": null
      },
      {
        "county_name": "Clayton County",
        "state_fips": "19",
        "county_fips": "19043",
        "population": 17043,
        "land_area_sq_mi": 778.464,
        "centroid": [
          42.860684,
          -91.321147
        ],
        "county_seat": null
      },
      {
        "county_name": "Clinton County",
        "state_fips": "19",
        "county_fips": "19045",
        "population": 46460,
        "land_area_sq_mi": 694.959,
        "centroid": [
          41.852141,
          -90.341168
        ],
        "county_seat": null
      },
      {
        "county_name": "Crawford County",
        "state_fips": "19",
        "county_fips": "19047",
        "population": 16525,
        "land_area_sq_mi": 714.198,
        "centroid": [
          42.026692,
          -95.357436
        ],
        "county_seat": null
      },
      {
        "county_name": "Dallas County",
        "state_fips": "19",
        "county_fips": "19049",
        "population": 99678,
        "land_area_sq_mi": 588.23,
        "centroid": [
          41.630722,
          -93.900543
        ],
        "county_seat": null
      },
      {
        "county_name": "Davis County",
        "state_fips": "19",
        "county_fips": "19051",
        "population": 9110,
        "land_area_sq_mi": 502.188,
        "centroid": [
          40.762546,
          -92.418316
        ],
        "county_seat": null
      },
      {
        "county_name": "Decatur County",
        "state_fips": "19",
        "county_fips": "19053",
        "population": 7645,
        "land_area_sq_mi": 531.883,
        "centroid": [
          40.7123,
          -93.817156
        ],
        "county_seat": null
      },
      {
        "county_name": "Delaware County",
        "state_fips": "19",
        "county_fips": "19055",
        "population": 17488,
        "land_area_sq_mi": 577.684,
        "centroid": [
          42.48163,
          -91.383936
        ],
        "county_seat": null
      },
      {
        "county_name": "Des Moines County",
        "state_fips": "19",
        "county_fips": "19057",
        "population": 38910,
        "land_area_sq_mi": 416.129,
        "centroid": [
          40.83528,
          -91.143256
        ],
        "county_seat": null
      },
      {
        "county_name": "Dickinson County",
        "state_fips": "19",
        "county_fips": "19059",
        "population": 17703,
        "land_area_sq_mi": 380.532,
        "centroid": [
          43.38895,
          -95.134559
        ],
        "county_seat": null
      },
      {
        "county_name": "Dubuque County",
        "state_fips": "19",
        "county_fips": "19061",
        "population": 99266,
        "land_area_sq_mi": 608.299,
        "centroid": [
          42.493173,
          -90.762214
        ],
        "county_seat": null
      },
      {
        "county_name": "Emmet County",
        "state_fips": "19",
        "county_fips": "19063",
        "population": 9388,
        "land_area_sq_mi": 395.89,
        "centroid": [
          43.395995,
          -94.75827
        ],
        "county_seat": null
      },
      {
        "county_name": "Fayette County",
        "state_fips": "19",
        "county_fips": "19065",
        "population": 19509,
        "land_area_sq_mi": 730.817,
        "centroid": [
          42.821543,
          -91.855739
        ],
        "county_seat": null
      },
      {
        "county_name": "Floyd County",
        "state_fips": "19",
        "county_fips": "19067",
        "population": 15627,
        "land_area_sq_mi": 500.571,
        "centroid": [
          43.075228,
          -92.751434
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "19",
        "county_fips": "19069",
        "population": 10019,
        "land_area_sq_mi": 581.972,
        "centroid": [
          42.754609,
          -93.239282
        ],
        "county_seat": null
      },
      {
        "county_name": "Fremont County",
        "state_fips": "19",
        "county_fips": "19071",
        "population": 6605,
        "land_area_sq_mi": 511.168,
        "centroid": [
          40.753741,
          -95.616798
        ],
        "county_seat": null
      },
      {
        "county_name": "Greene County",
        "state_fips": "19",
        "county_fips": "19073",
        "population": 8771,
        "land_area_sq_mi": 569.558,
        "centroid": [
          42.029106,
          -94.379863
        ],
        "county_seat": null
      },
      {
        "county_name": "Grundy County",
        "state_fips": "19",
        "county_fips": "19075",
        "population": 12329,
        "land_area_sq_mi": 501.855,
        "centroid": [
          42.38048,
          -92.747282
        ],
        "county_seat": null
      },
      {
        "county_name": "Guthrie County",
        "state_fips": "19",
        "county_fips": "19077",
        "population": 10623,
        "land_area_sq_mi": 590.614,
        "centroid": [
          41.665841,
          -94.427696
        ],
        "county_seat": null
      },
      {
        "county_name": "Hamilton County",
        "state_fips": "19",
        "county_fips": "19079",
        "population": 15039,
        "land_area_sq_mi": 576.731,
        "centroid": [
          42.406603,
          -93.767427
        ],
        "county_seat": null
      },
      {
        "county_name": "Hancock County",
        "state_fips": "19",
        "county_fips": "19081",
        "population": 10795,
        "land_area_sq_mi": 571.005,
        "centroid": [
          43.092315,
          -93.702667
        ],
        "county_seat": null
      },
      {
        "county_name": "Hardin County",
        "state_fips": "19",
        "county_fips": "19083",
        "population": 16878,
        "land_area_sq_mi": 569.307,
        "centroid": [
          42.436346,
          -93.217038
        ],
        "county_seat": null
      },
      {
        "county_name": "Harrison County",
        "state_fips": "19",
        "county_fips": "19085",
        "population": 14582,
        "land_area_sq_mi": 696.874,
        "centroid": [
          41.662599,
          -95.804583
        ],
        "county_seat": null
      },
      {
        "county_name": "Henry County",
        "state_fips": "19",
        "county_fips": "19087",
        "population": 20482,
        "land_area_sq_mi": 434.288,
        "centroid": [
          40.977985,
          -91.536884
        ],
        "county_seat": null
      },
      {
        "county_name": "Howard County",
        "state_fips": "19",
        "county_fips": "19089",
        "population": 9469,
        "land_area_sq_mi": 473.247,
        "centroid": [
          43.361965,
          -92.229351
        ],
        "county_seat": null
      },
      {
        "county_name": "Humboldt County",
        "state_fips": "19",
        "county_fips": "19091",
        "population": 9597,
        "land_area_sq_mi": 434.372,
        "centroid": [
          42.746569,
          -94.216619
        ],
        "county_seat": null
      },
      {
        "county_name": "Ida County",
        "state_fips": "19",
        "county_fips": "19093",
        "population": 7005,
        "land_area_sq_mi": 431.513,
        "centroid": [
          42.393275,
          -95.505465
        ],
        "county_seat": null
      },
      {
        "county_name": "Iowa County",
        "state_fips": "19",
        "county_fips": "19095",
        "population": 16662,
        "land_area_sq_mi": 586.455,
        "centroid": [
          41.701018,
          -92.039155
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "19",
        "county_fips": "19097",
        "population": 19485,
        "land_area_sq_mi": 636.047,
        "centroid": [
          42.141479,
          -90.567662
        ],
        "county_seat": null
      },
      {
        "county_name": "Jasper County",
        "state_fips": "19",
        "county_fips": "19099",
        "population": 37813,
        "land_area_sq_mi": 730.428,
        "centroid": [
          41.678059,
          -93.07144
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "19",
        "county_fips": "19101",
        "population": 15663,
        "land_area_sq_mi": 435.524,
        "centroid": [
          41.012603,
          -91.965861
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnson County",
        "state_fips": "19",
        "county_fips": "19103",
        "population": 152854,
        "land_area_sq_mi": 612.997,
        "centroid": [
          41.683586,
          -91.561276
        ],
        "county_seat": null
      },
      {
        "county_name": "Jones County",
        "state_fips": "19",
        "county_fips": "19105",
        "population": 20646,
        "land_area_sq_mi": 575.618,
        "centroid": [
          42.138136,
          -91.200472
        ],
        "county_seat": null
      },
      {
        "county_name": "Keokuk County",
        "state_fips": "19",
        "county_fips": "19107",
        "population": 10033,
        "land_area_sq_mi": 579.175,
        "centroid": [
          41.324433,
          -92.175248
        ],
        "county_seat": null
      },
      {
        "county_name": "Kossuth County",
        "state_fips": "19",
        "county_fips": "19109",
        "population": 14828,
        "land_area_sq_mi": 972.735,
        "centroid": [
          43.143301,
          -94.221432
        ],
        "county_seat": null
      },
      {
        "county_name": "Lee County",
        "state_fips": "19",
        "county_fips": "19111",
        "population": 33555,
        "land_area_sq_mi": 517.55,
        "centroid": [
          40.560697,
          -91.397062
        ],
        "county_seat": null
      },
      {
        "county_name": "Linn County",
        "state_fips": "19",
        "county_fips": "19113",
        "population": 230299,
        "land_area_sq_mi": 717.013,
        "centroid": [
          42.008474,
          -91.648394
        ],
        "county_seat": null
      },
      {
        "county_name": "Louisa County",
        "state_fips": "19",
        "county_fips": "19115",
        "population": 10837,
        "land_area_sq_mi": 401.777,
        "centroid": [
          41.225335,
          -91.262686
        ],
        "county_seat": null
      },
      {
        "county_name": "Lucas County",
        "state_fips": "19",
        "county_fips": "19117",
        "population": 8634,
        "land_area_sq_mi": 430.681,
        "centroid": [
          41.022123,
          -93.312466
        ],
        "county_seat": null
      },
      {
        "county_name": "Lyon County",
        "state_fips": "19",
        "county_fips": "19119",
        "population": 11934,
        "land_area_sq_mi": 587.609,
        "centroid": [
          43.385476,
          -96.227291
        ],
        "county_seat": null
      },
      {
        "county_name": "Madison County",
        "state_fips": "19",
        "county_fips": "19121",
        "population": 16548,
        "land_area_sq_mi": 561.006,
        "centroid": [
          41.348667,
          -93.98679
        ],
        "county_seat": null
      },
      {
        "county_name": "Mahaska County",
        "state_fips": "19",
        "county_fips": "19123",
        "population": 22190,
        "land_area_sq_mi": 570.851,
        "centroid": [
          41.311761,
          -92.642105
        ],
        "county_seat": null
      },
      {
        "county_name": "Marion County",
        "state_fips": "19",
        "county_fips": "19125",
        "population": 33414,
        "land_area_sq_mi": 554.49,
        "centroid": [
          41.357267,
          -93.041728
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "19",
        "county_fips": "19127",
        "population": 40105,
        "land_area_sq_mi": 572.503,
        "centroid": [
          42.030436,
          -92.938199
        ],
        "county_seat": null
      },
      {
        "county_name": "Mills County",
        "state_fips": "19",
        "county_fips": "19129",
        "population": 14484,
        "land_area_sq_mi": 437.431,
        "centroid": [
          41.050907,
          -95.693715
        ],
        "county_seat": null
      },
      {
        "county_name": "Mitchell County",
        "state_fips": "19",
        "county_fips": "19131",
        "population": 10565,
        "land_area_sq_mi": 469.256,
        "centroid": [
          43.334549,
          -92.806056
        ],
        "county_seat": null
      },
      {
        "county_name": "Monona County",
        "state_fips": "19",
        "county_fips": "19133",
        "population": 8751,
        "land_area_sq_mi": 694.072,
        "centroid": [
          42.062617,
          -95.988925
        ],
        "county_seat": null
      },
      {
        "county_name": "Monroe County",
        "state_fips": "19",
        "county_fips": "19135",
        "population": 7577,
        "land_area_sq_mi": 433.708,
        "centroid": [
          41.03376,
          -92.825189
        ],
        "county_seat": null
      },
      {
        "county_name": "Montgomery County",
        "state_fips": "19",
        "county_fips": "19137",
        "population": 10330,
        "land_area_sq_mi": 424.097,
        "centroid": [
          41.009252,
          -95.169693
        ],
        "county_seat": null
      },
      {
        "county_name": "Muscatine County",
        "state_fips": "19",
        "county_fips": "19139",
        "population": 43235,
        "land_area_sq_mi": 437.44,
        "centroid": [
          41.465515,
          -91.077753
        ],
        "county_seat": null
      },
      {
        "county_name": "O'Brien County",
        "state_fips": "19",
        "county_fips": "19141",
        "population": 14182,
        "land_area_sq_mi": 573.035,
        "centroid": [
          43.129233,
          -95.69531
        ],
        "county_seat": null
      },
      {
        "county_name": "Osceola County",
        "state_fips": "19",
        "county_fips": "19143",
        "population": 6192,
        "land_area_sq_mi": 398.687,
        "centroid": [
          43.387203,
          -95.680981
        ],
        "county_seat": null
      },
      {
        "county_name": "Page County",
        "state_fips": "19",
        "county_fips": "19145",
        "population": 15211,
        "land_area_sq_mi": 534.944,
        "centroid": [
          40.746972,
          -95.18734
        ],
        "county_seat": null
      },
      {
        "county_name": "Palo Alto County",
        "state_fips": "19",
        "county_fips": "19147",
        "population": 8996,
        "land_area_sq_mi": 563.864,
        "centroid": [
          43.101085,
          -94.688525
        ],
        "county_seat": null
      },
      {
        "county_name": "Plymouth County",
        "state_fips": "19",
        "county_fips": "19149",
        "population": 25698,
        "land_area_sq_mi": 862.828,
        "centroid": [
          42.748026,
          -96.20304
        ],
        "county_seat": null
      },
      {
        "county_name": "Pocahontas County",
        "state_fips": "19",
        "county_fips": "19151",
        "population": 7078,
        "land_area_sq_mi": 577.241,
        "centroid": [
          42.744041,
          -94.706993
        ],
        "county_seat": null
      },
      {
        "county_name": "Polk County",
        "state_fips": "19",
        "county_fips": "19153",
        "population": 492401,
        "land_area_sq_mi": 572.72,
        "centroid": [
          41.630968,
          -93.640165
        ],
        "county_seat": null
      },
      {
        "county_name": "Pottawattamie County",
        "state_fips": "19",
        "county_fips": "19155",
        "population": 93667,
        "land_area_sq_mi": 951.274,
        "centroid": [
          41.278446,
          -95.79385
        ],
        "county_seat": null
      },
      {
        "county_name": "Poweshiek County",
        "state_fips": "19",
        "county_fips": "19157",
        "population": 18662,
        "land_area_sq_mi": 584.932,
        "centroid": [
          41.712451,
          -92.624939
        ],
        "county_seat": null
      },
      {
        "county_name": "Ringgold County",
        "state_fips": "19",
        "county_fips": "19159",
        "population": 4663,
        "land_area_sq_mi": 535.494,
        "centroid": [
          40.737978,
          -94.237097
        ],
        "county_seat": null
      },
      {
        "county_name": "Sac County",
        "state_fips": "19",
        "county_fips": "19161",
        "population": 9814,
        "land_area_sq_mi": 575.022,
        "centroid": [
          42.37525,
          -95.089609
        ],
        "county_seat": null
      },
      {
        "county_name": "Scott County",
        "state_fips": "19",
        "county_fips": "19163",
        "population": 174669,
        "land_area_sq_mi": 458.101,
        "centroid": [
          41.5647,
          -90.562678
        ],
        "county_seat": null
      },
      {
        "county_name": "Shelby County",
        "state_fips": "19",
        "county_fips": "19165",
        "population": 11746,
        "land_area_sq_mi": 590.776,
        "centroid": [
          41.662625,
          -95.32328
        ],
        "county_seat": null
      },
      {
        "county_name": "Sioux County",
        "state_fips": "19",
        "county_fips": "19167",
        "population": 35872,
        "land_area_sq_mi": 767.911,
        "centroid": [
          43.080798,
          -96.167993
        ],
        "county_seat": null
      },
      {
        "county_name": "Story County",
        "state_fips": "19",
        "county_fips": "19169",
        "population": 98537,
        "land_area_sq_mi": 572.544,
        "centroid": [
          42.025132,
          -93.604948
        ],
        "county_seat": null
      },
      {
        "county_name": "Tama County",
        "state_fips": "19",
        "county_fips": "19171",
        "population": 17135,
        "land_area_sq_mi": 721.011,
        "centroid": [
          42.062414,
          -92.544134
        ],
        "county_seat": null
      },
      {
        "county_name": "Taylor County",
        "state_fips": "19",
        "county_fips": "19173",
        "population": 5896,
        "land_area_sq_mi": 531.902,
        "centroid": [
          40.753586,
          -94.679839
        ],
        "county_seat": null
      },
      {
        "county_name": "Union County",
        "state_fips": "19",
        "county_fips": "19175",
        "population": 12138,
        "land_area_sq_mi": 423.645,
        "centroid": [
          41.054759,
          -94.318334
        ],
        "county_seat": null
      },
      {
        "county_name": "Van Buren County",
        "state_fips": "19",
        "county_fips": "19177",
        "population": 7203,
        "land_area_sq_mi": 484.792,
        "centroid": [
          40.744224,
          -91.942474
        ],
        "county_seat": null
      },
      {
        "county_name": "Wapello County",
        "state_fips": "19",
        "county_fips": "19179",
        "population": 35437,
        "land_area_sq_mi": 431.843,
        "centroid": [
          41.01642,
          -92.418899
        ],
        "county_seat": null
      },
      {
        "county_name": "Warren County",
        "state_fips": "19",
        "county_fips": "19181",
        "population": 52403,
        "land_area_sq_mi": 569.658,
        "centroid": [
          41.40685,
          -93.595647
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "19",
        "county_fips": "19183",
        "population": 22565,
        "land_area_sq_mi": 568.828,
        "centroid": [
          41.365129,
          -91.69418
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "19",
        "county_fips": "19185",
        "population": 6497,
        "land_area_sq_mi": 525.469,
        "centroid": [
          40.733313,
          -93.304108
        ],
        "county_seat": null
      },
      {
        "county_name": "Webster County",
        "state_fips": "19",
        "county_fips": "19187",
        "population": 36999,
        "land_area_sq_mi": 715.704,
        "centroid": [
          42.481229,
          -94.179496
        ],
        "county_seat": null
      },
      {
        "county_name": "Winnebago County",
        "state_fips": "19",
        "county_fips": "19189",
        "population": 10679,
        "land_area_sq_mi": 400.489,
        "centroid": [
          43.341507,
          -93.663913
        ],
        "county_seat": null
      },
      {
        "county_name": "Winneshiek County",
        "state_fips": "19",
        "county_fips": "19191",
        "population": 20070,
        "land_area_sq_mi": 689.844,
        "centroid": [
          43.281109,
          -91.813207
        ],
        "county_seat": null
      },
      {
        "county_name": "Woodbury County",
        "state_fips": "19",
        "county_fips": "19193",
        "population": 105941,
        "land_area_sq_mi": 872.896,
        "centroid": [
          42.483312,
          -96.345995
        ],
        "county_seat": null
      },
      {
        "county_name": "Worth County",
        "state_fips": "19",
        "county_fips": "19195",
        "population": 7443,
        "land_area_sq_mi": 400.123,
        "centroid": [
          43.369396,
          -93.250437
        ],
        "county_seat": null
      },
      {
        "county_name": "Wright County",
        "state_fips": "19",
        "county_fips": "19197",
        "population": 12943,
        "land_area_sq_mi": 580.412,
        "centroid": [
          42.732976,
          -93.756305
        ],
        "county_seat": null
      }
    ]
