# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Alcona County",
        "state_fips": "26",
        "county_fips": "26001",
        "population": 10167,
        "land_area_sq_mi": 674.655,
        "centroid": [
          44.668106,
          -83.46556
        ],
        "county_seat": null
      },
      {
        "county_name": "Alger County",
        "state_fips": "26",
        "county_fips": "26003",
        "population": 8842,
        "land_area_sq_mi": 915.034,
        "centroid": [
          46.384467,
          -86.711752
        ],
        "county_seat": null
      },
      {
        "county_name": "Allegan County",
        "state_fips": "26",
        "county_fips": "26005",
        "population": 120502,
        "land_area_sq_mi": 825.253,
        "centroid": [
          42.608445,
          -85.871027
        ],
        "county_seat": null
      },
      {
        "county_name": "Alpena County",
        "state_fips": "26",
        "county_fips": "26007",
        "population": 28907,
        "land_area_sq_mi": 571.899,
        "centroid": [
          45.050588,
          -83.502895
        ],
        "county_seat": null
      },
      {
        "county_name": "Antrim County",
        "state_fips": "26",
        "county_fips": "26009",
        "population": 23431,
        "land_area_sq_mi": 475.679,
        "centroid": [
          44.978317,
          -85.198554
        ],
        "county_seat": null
      },
      {
        "county_name": "Arenac County",
        "state_fips": "26",
        "county_fips": "26011",
        "population": 15002,
        "land_area_sq_mi": 363.178,
        "centroid": [
          44.044452,
          -83.884489
        ],
        "county_seat": null
      },
      {
        "county_name": "Baraga County",
        "state_fips": "26",
        "county_fips": "26013",
        "population": 8158,
        "land_area_sq_mi": 898.427,
        "centroid": [
          46.766517,
          -88.450012
        ],
        "county_seat": null
      },
      {
        "county_name": "Barry County",
        "state_fips": "26",
        "county_fips": "26015",
        "population": 62423,
        "land_area_sq_mi": 553.104,
        "centroid": [
          42.618511,
          -85.349392
        ],
        "county_seat": null
      },
      {
        "county_name": "Bay County",
        "state_fips": "26",
        "county_fips": "26017",
        "population": 103856,
        "land_area_sq_mi": 442.409,
        "centroid": [
          43.629992,
          -83.929196
        ],
        "county_seat": null
      },
      {
        "county_name": "Benzie County",
        "state_fips": "26",
        "county_fips": "26019",
        "population": 17970,
        "land_area_sq_mi": 319.697,
        "centroid": [
          44.651834,
          -86.011382
        ],
        "county_seat": null
      },
      {
        "county_name": "Berrien County",
        "state_fips": "26",
        "county_fips": "26021",
        "population": 154316,
        "land_area_sq_mi": 567.795,
        "centroid": [
          41.985704,
          -86.406377
        ],
        "county_seat": null
      },
      {
        "county_name": "Branch County",
        "state_fips": "26",
        "county_fips": "26023",
        "population": 44862,
        "land_area_sq_mi": 506.411,
        "centroid": [
          41.929177,
          -85.030705
        ],
        "county_seat": null
      },
      {
        "county_name": "Calhoun County",
        "state_fips": "26",
        "county_fips": "26025",
        "population": 134310,
        "land_area_sq_mi": 706.259,
        "centroid": [
          42.289631,
          -85.106049
        ],
        "county_seat": null
      },
      {
        "county_name": "Cass County",
        "state_fips": "26",
        "county_fips": "26027",
        "population": 51589,
        "land_area_sq_mi": 490.125,
        "centroid": [
          41.892277,
          -86.040504
        ],
        "county_seat": null
      },
      {
        "county_name": "Charlevoix County",
        "state_fips": "26",
        "county_fips": "26029",
        "population": 26054,
        "land_area_sq_mi": 416.33,
        "centroid": [
          45.244536,
          -85.11101
        ],
        "county_seat": null
      },
      {
        "county_name": "Cheboygan County",
        "state_fips": "26",
        "county_fips": "26031",
        "population": 25579,
        "land_area_sq_mi": 715.279,
        "centroid": [
          45.511041,
          -84.52108
        ],
        "county_seat": null
      },
      {
        "county_name": "Chippewa County",
        "state_fips": "26",
        "county_fips": "26033",
        "population": 36785,
        "land_area_sq_mi": 1558.513,
        "centroid": [
          46.365585,
          -84.396326
        ],
        "county_seat": null
      },
      {
        "county_name": "Clare County",
        "state_fips": "26",
        "county_fips": "26035",
        "population": 30856,
        "land_area_sq_mi": 564.367,
        "centroid": [
          43.944384,
          -84.825685
        ],
        "county_seat": null
      },
      {
        "county_name": "Clinton County",
        "state_fips": "26",
        "county_fips": "26037",
        "population": 79128,
        "land_area_sq_mi": 567.349,
        "centroid": [
          42.886259,
          -84.55428
        ],
        "county_seat": null
      },
      {
        "county_name": "Crawford County",
        "state_fips": "26",
        "county_fips": "26039",
        "population": 12988,
        "land_area_sq_mi": 556.415,
        "centroid": [
          44.657052,
          -84.668957
        ],
        "county_seat": null
      },
      {
        "county_name": "Delta County",
        "state_fips": "26",
        "county_fips": "26041",
        "population": 36903,
        "land_area_sq_mi": 1171.094,
        "centroid": [
          45.801912,
          -87.065752
        ],
        "county_seat": null
      },
      {
        "county_name": "Dickinson County",
        "state_fips": "26",
        "county_fips": "26043",
        "population": 25947,
        "land_area_sq_mi": 760.95,
        "centroid": [
          45.832994,
          -88.014029
        ],
        "county_seat": null
      },
      {
        "county_name": "Eaton County",
        "state_fips": "26",
        "county_fips": "26045",
        "population": 109175,
        "land_area_sq_mi": 575.209,
        "centroid": [
          42.645094,
          -84.739621
        ],
        "county_seat": null
      },
      {
        "county_name": "Emmet County",
        "state_fips": "26",
        "county_fips": "26047",
        "population": 34112,
        "land_area_sq_mi": 467.546,
        "centroid": [
          45.432042,
          -84.910442
        ],
        "county_seat": null
      },
      {
        "county_name": "Genesee County",
        "state_fips": "26",
        "county_fips": "26049",
        "population": 406211,
        "land_area_sq_mi": 636.944,
        "centroid": [
          43.002399,
          -83.693809
        ],
        "county_seat": null
      },
      {
        "county_name": "Gladwin County",
        "state_fips": "26",
        "county_fips": "26051",
        "population": 25386,
        "land_area_sq_mi": 501.787,
        "centroid": [
          43.968003,
          -84.439806
        ],
        "county_seat": null
      },
      {
        "county_name": "Gogebic County",
        "state_fips": "26",
        "county_fips": "26053",
        "population": 14380,
        "land_area_sq_mi": 1102.136,
        "centroid": [
          46.446365,
          -89.992958
        ],
        "county_seat": null
      },
      {
        "county_name": "Grand Traverse County",
        "state_fips": "26",
        "county_fips": "26055",
        "population": 95238,
        "land_area_sq_mi": 464.336,
        "centroid": [
          44.713441,
          -85.613028
        ],
        "county_seat": null
      },
      {
        "county_name": "Gratiot County",
        "state_fips": "26",
        "county_fips": "26057",
        "population": 41761,
        "land_area_sq_mi": 568.383,
        "centroid": [
          43.34413,
          -84.631259
        ],
        "county_seat": null
      },
      {
        "county_name": "Hillsdale County",
        "state_fips": "26",
        "county_fips": "26059",
        "population": 45746,
        "land_area_sq_mi": 598.152,
        "centroid": [
          41.916883,
          -84.605231
        ],
        "county_seat": null
      },
      {
        "county_name": "Houghton County",
        "state_fips": "26",
        "county_fips": "26061",
        "population": 37361,
        "land_area_sq_mi": 1009.103,
        "centroid": [
          47.127331,
          -88.54177
        ],
        "county_seat": null
      },
      {
        "county_name": "Huron County",
        "state_fips": "26",
        "county_fips": "26063",
        "population": 31407,
        "land_area_sq_mi": 836.018,
        "centroid": [
          43.832366,
          -83.063027
        ],
        "county_seat": null
      },
      {
        "county_name": "Ingham County",
        "state_fips": "26",
        "county_fips": "26065",
        "population": 284900,
        "land_area_sq_mi": 556.081,
        "centroid": [
          42.688382,
          -84.486253
        ],
        "county_seat": null
      },
      {
        "county_name": "Ionia County",
        "state_fips": "26",
        "county_fips": "26067",
        "population": 66804,
        "land_area_sq_mi": 571.32,
        "centroid": [
          42.957003,
          -85.086727
        ],
        "county_seat": null
      },
      {
        "county_name": "Iosco County",
        "state_fips": "26",
        "county_fips": "26069",
        "population": 25237,
        "land_area_sq_mi": 549.477,
        "centroid": [
          44.357042,
          -83.532361
        ],
        "county_seat": null
      },
      {
        "county_name": "Iron County",
        "state_fips": "26",
        "county_fips": "26071",
        "population": 11631,
        "land_area_sq_mi": 1166.096,
        "centroid": [
          46.099565,
          -88.53764
        ],
        "county_seat": null
      },
      {
        "county_name": "Isabella County",
        "state_fips": "26",
        "county_fips": "26073",
        "population": 64394,
        "land_area_sq_mi": 572.7,
        "centroid": [
          43.608534,
          -84.80345
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "26",
        "county_fips": "26075",
        "population": 160366,
        "land_area_sq_mi": 701.903,
        "centroid": [
          42.241802,
          -84.406618
        ],
        "county_seat": null
      },
      {
        "county_name": "Kalamazoo County",
        "state_fips": "26",
        "county_fips": "26077",
        "population": 261670,
        "land_area_sq_mi": 561.959,
        "centroid": [
          42.262549,
          -85.586372
        ],
        "county_seat": null
      },
      {
        "county_name": "Kalkaska County",
        "state_fips": "26",
        "county_fips": "26079",
        "population": 17939,
        "land_area_sq_mi": 559.744,
        "centroid": [
          44.720582,
          -85.164963
        ],
        "county_seat": null
      },
      {
        "county_name": "Kent County",
        "state_fips": "26",
        "county_fips": "26081",
        "population": 657974,
        "land_area_sq_mi": 848.931,
        "centroid": [
          42.961776,
          -85.625638
        ],
        "county_seat": null
      },
      {
        "county_name": "Keweenaw County",
        "state_fips": "26",
        "county_fips": "26083",
        "population": 2046,
        "land_area_sq_mi": 540.112,
        "centroid": [
          47.336126,
          -88.289269
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake County",
        "state_fips": "26",
        "county_fips": "26085",
        "population": 12096,
        "land_area_sq_mi": 567.595,
        "centroid": [
          43.95721,
          -85.799431
        ],
        "county_seat": null
      },
      {
        "county_name": "Lapeer County",
        "state_fips": "26",
        "county_fips": "26087",
        "population": 88619,
        "land_area_sq_mi": 646.983,
        "centroid": [
          43.058194,
          -83.249396
        ],
        "county_seat": null
      },
      {
        "county_name": "Leelanau County",
        "state_fips": "26",
        "county_fips": "26089",
        "population": 22301,
        "land_area_sq_mi": 347.2,
        "centroid": [
          44.906992,
          -85.730072
        ],
        "county_seat": null
      },
      {
        "county_name": "Lenawee County",
        "state_fips": "26",
        "county_fips": "26091",
        "population": 99423,
        "land_area_sq_mi": 749.638,
        "centroid": [
          41.926112,
          -84.052777
        ],
        "county_seat": null
      },
      {
        "county_name": "Livingston County",
        "state_fips": "26",
        "county_fips": "26093",
        "population": 193866,
        "land_area_sq_mi": 565.284,
        "centroid": [
          42.575026,
          -83.856466
        ],
        "county_seat": null
      },
      {
        "county_name": "Luce County",
        "state_fips": "26",
        "county_fips": "26095",
        "population": 5339,
        "land_area_sq_mi": 899.075,
        "centroid": [
          46.335663,
          -85.56135
        ],
        "county_seat": null
      },
      {
        "county_name": "Mackinac County",
        "state_fips": "26",
        "county_fips": "26097",
        "population": 10834,
        "land_area_sq_mi": 1021.879,
        "centroid": [
          45.997314,
          -84.881331
        ],
        "county_seat": null
      },
      {
        "county_name": "Macomb County",
        "state_fips": "26",
        "county_fips": "26099",
        "population": 881217,
        "land_area_sq_mi": 479.35,
        "centroid": [
          42.589118,
          -82.957895
        ],
        "county_seat": null
      },
      {
        "county_name": "Manistee County",
        "state_fips": "26",
        "county_fips": "26101",
        "population": 25032,
        "land_area_sq_mi": 542.325,
        "centroid": [
          44.306321,
          -86.185294
        ],
        "county_seat": null
      },
      {
        "county_name": "Marquette County",
        "state_fips": "26",
        "county_fips": "26103",
        "population": 66017,
        "land_area_sq_mi": 1809.068,
        "centroid": [
          46.486717,
          -87.492759
        ],
        "county_seat": null
      },
      {
        "county_name": "Mason County",
        "state_fips": "26",
        "county_fips": "26105",
        "population": 29052,
        "land_area_sq_mi": 494.969,
        "centroid": [
          43.97455,
          -86.346719
        ],
        "county_seat": null
      },
      {
        "county_name": "Mecosta County",
        "state_fips": "26",
        "county_fips": "26107",
        "population": 39714,
        "land_area_sq_mi": 555.155,
        "centroid": [
          43.650863,
          -85.382191
        ],
        "county_seat": null
      },
      {
        "county_name": "Menominee County",
        "state_fips": "26",
        "county_fips": "26109",
        "population": 23502,
        "land_area_sq_mi": 1044.041,
        "centroid": [
          45.342064,
          -87.579801
        ],
        "county_seat": null
      },
      {
        "county_name": "Midland County",
        "state_fips": "26",
        "county_fips": "26111",
        "population": 83494,
        "land_area_sq_mi": 518.434,
        "centroid": [
          43.643318,
          -84.296349
        ],
        "county_seat": null
      },
      {
        "county_name": "Missaukee County",
        "state_fips": "26",
        "county_fips": "26113",
        "population": 15052,
        "land_area_sq_mi": 564.788,
        "centroid": [
          44.307677,
          -85.179858
        ],
        "county_seat": null
      },
      {
        "county_name": "Monroe County",
        "state_fips": "26",
        "county_fips": "26115",
        "population": 154809,
        "land_area_sq_mi": 549.362,
        "centroid": [
          41.901664,
          -83.486421
        ],
        "county_seat": null
      },
      {
        "county_name": "Montcalm County",
        "state_fips": "26",
        "county_fips": "26117",
        "population": 66614,
        "land_area_sq_mi": 705.329,
        "centroid": [
          43.283564,
          -85.172737
        ],
        "county_seat": null
      },
      {
        "county_name": "Montmorency County",
        "state_fips": "26",
        "county_fips": "26119",
        "population": 9153,
        "land_area_sq_mi": 546.675,
        "centroid": [
          44.997449,
          -84.12591
        ],
        "county_seat": null
      },
      {
        "county_name": "Muskegon County",
        "state_fips": "26",
        "county_fips": "26121",
        "population": 175824,
        "land_area_sq_mi": 503.914,
        "centroid": [
          43.243847,
          -86.214941
        ],
        "county_seat": null
      },
      {
        "county_name": "Newaygo County",
        "state_fips": "26",
        "county_fips": "26123",
        "population": 49978,
        "land_area_sq_mi": 838.887,
        "centroid": [
          43.466224,
          -85.811272
        ],
        "county_seat": null
      },
      {
        "county_name": "Oakland County",
        "state_fips": "26",
        "county_fips": "26125",
        "population": 1274395,
        "land_area_sq_mi": 867.399,
        "centroid": [
          42.586862,
          -83.314039
        ],
        "county_seat": null
      },
      {
        "county_name": "Oceana County",
        "state_fips": "26",
        "county_fips": "26127",
        "population": 26659,
        "land_area_sq_mi": 538.105,
        "centroid": [
          43.632662,
          -86.305778
        ],
        "county_seat": null
      },
      {
        "county_name": "Ogemaw County",
        "state_fips": "26",
        "county_fips": "26129",
        "population": 20770,
        "land_area_sq_mi": 563.506,
        "centroid": [
          44.286618,
          -84.127345
        ],
        "county_seat": null
      },
      {
        "county_name": "Ontonagon County",
        "state_fips": "26",
        "county_fips": "26131",
        "population": 5816,
        "land_area_sq_mi": 1310.978,
        "centroid": [
          46.718929,
          -89.288199
        ],
        "county_seat": null
      },
      {
        "county_name": "Osceola County",
        "state_fips": "26",
        "county_fips": "26133",
        "population": 22891,
        "land_area_sq_mi": 566.286,
        "centroid": [
          43.965434,
          -85.357843
        ],
        "county_seat": null
      },
      {
        "county_name": "Oscoda County",
        "state_fips": "26",
        "county_fips": "26135",
        "population": 8219,
        "land_area_sq_mi": 565.674,
        "centroid": [
          44.701471,
          -84.14837
        ],
        "county_seat": null
      },
      {
        "county_name": "Otsego County",
        "state_fips": "26",
        "county_fips": "26137",
        "population": 25091,
        "land_area_sq_mi": 515.006,
        "centroid": [
          45.006949,
          -84.666769
        ],
        "county_seat": null
      },
      {
        "county_name": "Ottawa County",
        "state_fips": "26",
        "county_fips": "26139",
        "population": 296200,
        "land_area_sq_mi": 563.52,
        "centroid": [
          42.911054,
          -86.015862
        ],
        "county_seat": null
      },
      {
        "county_name": "Presque Isle County",
        "state_fips": "26",
        "county_fips": "26141",
        "population": 12982,
        "land_area_sq_mi": 658.718,
        "centroid": [
          45.356976,
          -83.868249
        ],
        "county_seat": null
      },
      {
        "county_name": "Roscommon County",
        "state_fips": "26",
        "county_fips": "26143",
        "population": 23459,
        "land_area_sq_mi": 519.897,
        "centroid": [
          44.364342,
          -84.650133
        ],
        "county_seat": null
      },
      {
        "county_name": "Saginaw County",
        "state_fips": "26",
        "county_fips": "26145",
        "population": 190124,
        "land_area_sq_mi": 800.807,
        "centroid": [
          43.399088,
          -83.996446
        ],
        "county_seat": null
      },
      {
        "county_name": "St. Clair County",
        "state_fips": "26",
        "county_fips": "26147",
        "population": 160383,
        "land_area_sq_mi": 721.501,
        "centroid": [
          42.912215,
          -82.563457
        ],
        "county_seat": null
      },
      {
        "county_name": "St. Joseph County",
        "state_fips": "26",
        "county_fips": "26149",
        "population": 60939,
        "land_area_sq_mi": 500.639,
        "centroid": [
          41.887521,
          -85.526887
        ],
        "county_seat": null
      },
      {
        "county_name": "Sanilac County",
        "state_fips": "26",
        "county_fips": "26151",
        "population": 40611,
        "land_area_sq_mi": 962.571,
        "centroid": [
          43.365189,
          -82.782963
        ],
        "county_seat": null
      },
      {
        "county_name": "Schoolcraft County",
        "state_fips": "26",
        "county_fips": "26153",
        "population": 8047,
        "land_area_sq_mi": 1171.876,
        "centroid": [
          46.006087,
          -86.226826
        ],
        "county_seat": null
      },
      {
        "county_name": "Shiawassee County",
        "state_fips": "26",
        "county_fips": "26155",
        "population": 68094,
        "land_area_sq_mi": 530.967,
        "centroid": [
          42.942704,
          -84.147876
        ],
        "county_seat": null
      },
      {
        "county_name": "Tuscola County",
        "state_fips": "26",
        "county_fips": "26157",
        "population": 53323,
        "land_area_sq_mi": 804.84,
        "centroid": [
          43.429916,
          -83.433939
        ],
        "county_seat": null
      },
      {
        "county_name": "Van Buren County",
        "state_fips": "26",
        "county_fips": "26159",
        "population": 75587,
        "land_area_sq_mi": 607.793,
        "centroid": [
          42.260186,
          -86.001338
        ],
        "county_seat": null
      },
      {
        "county_name": "Washtenaw County",
        "state_fips": "26",
        "county_fips": "26161",
        "population": 372258,
        "land_area_sq_mi": 706.003,
        "centroid": [
          42.257602,
          -83.726939
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "26",
        "county_fips": "26163",
        "population": 1793561,
        "land_area_sq_mi": 611.84,
        "centroid": [
          42.329477,
          -83.226321
        ],
        "county_seat": null
      },
      {
        "county_name": "Wexford County",
        "state_fips": "26",
        "county_fips": "26165",
        "population": 33673,
        "land_area_sq_mi": 564.924,
        "centroid": [
          44.309686,
          -85.486553
        ],
        "county_seat": null
      }
    ]
