# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adams County",
        "state_fips": "31",
        "county_fips": "31001",
        "population": 31205,
        "land_area_sq_mi": 563.26,
        "centroid": [
          40.585501,
          -98.41518
        ],
        "county_seat": null
      },
      {
        "county_name": "Antelope County",
        "state_fips": "31",
        "county_fips": "31003",
        "population": 6295,
        "land_area_sq_mi": 857.157,
        "centroid": [
          42.147054,
          -98.057377
        ],
        "county_seat": null
      },
      {
        "county_name": "Arthur County",
        "state_fips": "31",
        "county_fips": "31005",
        "population": 434,
        "land_area_sq_mi": 715.152,
        "centroid": [
          41.569368,
          -101.678874
        ],
        "county_seat": null
      },
      {
        "county_name": "Banner County",
        "state_fips": "31",
        "county_fips": "31007",
        "population": 674,
        "land_area_sq_mi": 746.039,
        "centroid": [
          41.558824,
          -103.721644
        ],
        "county_seat": null
      },
      {
        "county_name": "Blaine County",
        "state_fips": "31",
        "county_fips": "31009",
        "population": 431,
        "land_area_sq_mi": 710.702,
        "centroid": [
          41.906138,
          -100.013369
        ],
        "county_seat": null
      },
      {
        "county_name": "Boone County",
        "state_fips": "31",
        "county_fips": "31011",
        "population": 5379,
        "land_area_sq_mi": 686.53,
        "centroid": [
          41.677314,
          -98.014023
        ],
        "county_seat": null
      },
      {
        "county_name": "Box Butte County",
        "state_fips": "31",
        "county_fips": "31013",
        "population": 10842,
        "land_area_sq_mi": 1075.161,
        "centroid": [
          42.136678,
          -102.905215
        ],
        "county_seat": null
      },
      {
        "county_name": "Boyd County",
        "state_fips": "31",
        "county_fips": "31015",
        "population": 1810,
        "land_area_sq_mi": 539.368,
        "centroid": [
          42.893569,
          -98.74483
        ],
        "county_seat": null
      },
      {
        "county_name": "Brown County",
        "state_fips": "31",
        "county_fips": "31017",
        "population": 2903,
        "land_area_sq_mi": 1221.405,
        "centroid": [
          42.543087,
          -99.849627
        ],
        "county_seat": null
      },
      {
        "county_name": "Buffalo County",
        "state_fips": "31",
        "county_fips": "31019",
        "population": 50084,
        "land_area_sq_mi": 968.246,
        "centroid": [
          40.737756,
          -99.072828
        ],
        "county_seat": null
      },
      {
        "county_name": "Burt County",
        "state_fips": "31",
        "county_fips": "31021",
        "population": 6722,
        "land_area_sq_mi": 491.587,
        "centroid": [
          41.845218,
          -96.347791
        ],
        "county_seat": null
      },
      {
        "county_name": "Butler County",
        "state_fips": "31",
        "county_fips": "31023",
        "population": 8369,
        "land_area_sq_mi": 584.789,
        "centroid": [
          41.247435,
          -97.141745
        ],
        "county_seat": null
      },
      {
        "county_name": "Cass County",
        "state_fips": "31",
        "county_fips": "31025",
        "population": 26598,
        "land_area_sq_mi": 556.907,
        "centroid": [
          40.949471,
          -96.063719
        ],
        "county_seat": null
      },
      {
        "county_name": "Cedar County",
        "state_fips": "31",
        "county_fips": "31027",
        "population": 8380,
        "land_area_sq_mi": 740.189,
        "centroid": [
          42.576739,
          -97.250958
        ],
        "county_seat": null
      },
      {
        "county_name": "Chase County",
        "state_fips": "31",
        "county_fips": "31029",
        "population": 3893,
        "land_area_sq_mi": 894.425,
        "centroid": [
          40.501955,
          -101.625629
        ],
        "county_seat": null
      },
      {
        "county_name": "Cherry County",
        "state_fips": "31",
        "county_fips": "31031",
        "population": 5455,
        "land_area_sq_mi": 5960.099,
        "centroid": [
          42.788407,
          -100.749694
        ],
        "county_seat": null
      },
      {
        "county_name": "Cheyenne County",
        "state_fips": "31",
        "county_fips": "31033",
        "population": 9468,
        "land_area_sq_mi": 1196.008,
        "centroid": [
          41.164852,
          -102.982567
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "31",
        "county_fips": "31035",
        "population": 6104,
        "land_area_sq_mi": 572.289,
        "centroid": [
          40.547589,
          -98.027882
        ],
        "county_seat": null
      },
      {
        "county_name": "Colfax County",
        "state_fips": "31",
        "county_fips": "31037",
        "population": 10582,
        "land_area_sq_mi": 411.46,
        "centroid": [
          41.515594,
          -97.076357
        ],
        "county_seat": null
      },
      {
        "county_name": "Cuming County",
        "state_fips": "31",
        "county_fips": "31039",
        "population": 9013,
        "land_area_sq_mi": 570.49,
        "centroid": [
          41.896856,
          -96.758441
        ],
        "county_seat": null
      },
      {
        "county_name": "Custer County",
        "state_fips": "31",
        "county_fips": "31041",
        "population": 10545,
        "land_area_sq_mi": 2575.458,
        "centroid": [
          41.400577,
          -99.673936
        ],
        "county_seat": null
      },
      {
        "county_name": "Dakota County",
        "state_fips": "31",
        "county_fips": "31043",
        "population": 21582,
        "land_area_sq_mi": 264.276,
        "centroid": [
          42.446864,
          -96.438647
        ],
        "county_seat": null
      },
      {
        "county_name": "Dawes County",
        "state_fips": "31",
        "county_fips": "31045",
        "population": 8199,
        "land_area_sq_mi": 1396.437,
        "centroid": [
          42.786274,
          -103.066332
        ],
        "county_seat": null
      },
      {
        "county_name": "Dawson County",
        "state_fips": "31",
        "county_fips": "31047",
        "population": 24111,
        "land_area_sq_mi": 1013.786,
        "centroid": [
          40.827351,
          -99.856676
        ],
        "county_seat": null
      },
      {
        "county_name": "Deuel County",
        "state_fips": "31",
        "county_fips": "31049",
        "population": 1838,
        "land_area_sq_mi": 439.825,
        "centroid": [
          41.090929,
          -102.33652
        ],
        "county_seat": null
      },
      {
        "county_name": "Dixon County",
        "state_fips": "31",
        "county_fips": "31051",
        "population": 5606,
        "land_area_sq_mi": 475.621,
        "centroid": [
          42.436803,
          -96.826061
        ],
        "county_seat": null
      },
      {
        "county_name": "Dodge County",
        "state_fips": "31",
        "county_fips": "31053",
        "population": 37167,
        "land_area_sq_mi": 528.844,
        "centroid": [
          41.471288,
          -96.528637
        ],
        "county_seat": null
      },
      {
        "county_name": "Douglas County",
        "state_fips": "31",
        "county_fips": "31055",
        "population": 584526,
        "land_area_sq_mi": 326.547,
        "centroid": [
          41.26173,
          -96.069741
        ],
        "county_seat": null
      },
      {
        "county_name": "Dundy County",
        "state_fips": "31",
        "county_fips": "31057",
        "population": 1654,
        "land_area_sq_mi": 919.678,
        "centroid": [
          40.089487,
          -101.59927
        ],
        "county_seat": null
      },
      {
        "county_name": "Fillmore County",
        "state_fips": "31",
        "county_fips": "31059",
        "population": 5551,
        "land_area_sq_mi": 575.37,
        "centroid": [
          40.541248,
          -97.580053
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "31",
        "county_fips": "31061",
        "population": 2889,
        "land_area_sq_mi": 575.816,
        "centroid": [
          40.185987,
          -98.95454
        ],
        "county_seat": null
      },
      {
        "county_name": "Frontier County",
        "state_fips": "31",
        "county_fips": "31063",
        "population": 2519,
        "land_area_sq_mi": 974.655,
        "centroid": [
          40.609996,
          -100.398828
        ],
        "county_seat": null
      },
      {
        "county_name": "Furnas County",
        "state_fips": "31",
        "county_fips": "31065",
        "population": 4636,
        "land_area_sq_mi": 719.204,
        "centroid": [
          40.250813,
          -99.934116
        ],
        "county_seat": null
      },
      {
        "county_name": "Gage County",
        "state_fips": "31",
        "county_fips": "31067",
        "population": 21704,
        "land_area_sq_mi": 851.468,
        "centroid": [
          40.280866,
          -96.713556
        ],
        "county_seat": null
      },
      {
        "county_name": "Garden County",
        "state_fips": "31",
        "county_fips": "31069",
        "population": 1874,
        "land_area_sq_mi": 1704.826,
        "centroid": [
          41.429505,
          -102.323863
        ],
        "county_seat": null
      },
      {
        "county_name": "Garfield County",
        "state_fips": "31",
        "county_fips": "31071",
        "population": 1813,
        "land_area_sq_mi": 569.356,
        "centroid": [
          41.803658,
          -99.104124
        ],
        "county_seat": null
      },
      {
        "county_name": "Gosper County",
        "state_fips": "31",
        "county_fips": "31073",
        "population": 1893,
        "land_area_sq_mi": 458.199,
        "centroid": [
          40.59443,
          -99.826842
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "31",
        "county_fips": "31075",
        "population": 611,
        "land_area_sq_mi": 776.696,
        "centroid": [
          41.969597,
          -101.734576
        ],
        "county_seat": null
      },
      {
        "county_name": "Greeley County",
        "state_fips": "31",
        "county_fips": "31077",
        "population": 2188,
        "land_area_sq_mi": 569.826,
        "centroid": [
          41.555312,
          -98.49942
        ],
        "county_seat": null
      },
      {
        "county_name": "Hall County",
        "state_fips": "31",
        "county_fips": "31079",
        "population": 62895,
        "land_area_sq_mi": 546.529,
        "centroid": [
          40.91634,
          -98.377793
        ],
        "county_seat": null
      },
      {
        "county_name": "Hamilton County",
        "state_fips": "31",
        "county_fips": "31081",
        "population": 9429,
        "land_area_sq_mi": 542.03,
        "centroid": [
          40.879505,
          -98.023002
        ],
        "county_seat": null
      },
      {
        "county_name": "Harlan County",
        "state_fips": "31",
        "county_fips": "31083",
        "population": 3073,
        "land_area_sq_mi": 553.466,
        "centroid": [
          40.145347,
          -99.406335
        ],
        "county_seat": null
      },
      {
        "county_name": "Hayes County",
        "state_fips": "31",
        "county_fips": "31085",
        "population": 856,
        "land_area_sq_mi": 713.065,
        "centroid": [
          40.500842,
          -101.049757
        ],
        "county_seat": null
      },
      {
        "county_name": "Hitchcock County",
        "state_fips": "31",
        "county_fips": "31087",
        "population": 2616,
        "land_area_sq_mi": 709.951,
        "centroid": [
          40.21095,
          -101.004675
        ],
        "county_seat": null
      },
      {
        "county_name": "Holt County",
        "state_fips": "31",
        "county_fips": "31089",
        "population": 10127,
        "land_area_sq_mi": 2411.851,
        "centroid": [
          42.460461,
          -98.743792
        ],
        "county_seat": null
      },
      {
        "county_name": "Hooker County",
        "state_fips": "31",
        "county_fips": "31091",
        "population": 711,
        "land_area_sq_mi": 720.966,
        "centroid": [
          42.010663,
          -101.050551
        ],
        "county_seat": null
      },
      {
        "county_name": "Howard County",
        "state_fips": "31",
        "county_fips": "31093",
        "population": 6475,
        "land_area_sq_mi": 569.27,
        "centroid": [
          41.18917,
          -98.489627
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "31",
        "county_fips": "31095",
        "population": 7240,
        "land_area_sq_mi": 570.182,
        "centroid": [
          40.164225,
          -97.141688
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnson County",
        "state_fips": "31",
        "county_fips": "31097",
        "population": 5290,
        "land_area_sq_mi": 376.086,
        "centroid": [
          40.401098,
          -96.227732
        ],
        "county_seat": null
      },
      {
        "county_name": "Kearney County",
        "state_fips": "31",
        "county_fips": "31099",
        "population": 6688,
        "land_area_sq_mi": 516.193,
        "centroid": [
          40.507252,
          -98.99218
        ],
        "county_seat": null
      },
      {
        "county_name": "Keith County",
        "state_fips": "31",
        "county_fips": "31101",
        "population": 8335,
        "land_area_sq_mi": 1062.063,
        "centroid": [
          41.141819,
          -101.6998
        ],
        "county_seat": null
      },
      {
        "county_name": "Keya Paha County",
        "state_fips": "31",
        "county_fips": "31103",
        "population": 769,
        "land_area_sq_mi": 772.876,
        "centroid": [
          42.868932,
          -99.717406
        ],
        "county_seat": null
      },
      {
        "county_name": "Kimball County",
        "state_fips": "31",
        "county_fips": "31105",
        "population": 3434,
        "land_area_sq_mi": 951.942,
        "centroid": [
          41.231296,
          -103.66158
        ],
        "county_seat": null
      },
      {
        "county_name": "Knox County",
        "state_fips": "31",
        "county_fips": "31107",
        "population": 8391,
        "land_area_sq_mi": 1108.235,
        "centroid": [
          42.62421,
          -97.782589
        ],
        "county_seat": null
      },
      {
        "county_name": "Lancaster County",
        "state_fips": "31",
        "county_fips": "31109",
        "population": 322608,
        "land_area_sq_mi": 837.56,
        "centroid": [
          40.799269,
          -96.671536
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "31",
        "county_fips": "31111",
        "population": 34676,
        "land_area_sq_mi": 2564.155,
        "centroid": [
          41.119294,
          -100.789525
        ],
        "county_seat": null
      },
      {
        "county_name": "Logan County",
        "state_fips": "31",
        "county_fips": "31113",
        "population": 716,
        "land_area_sq_mi": 570.698,
        "centroid": [
          41.499176,
          -100.507661
        ],
        "county_seat": null
      },
      {
        "county_name": "Loup County",
        "state_fips": "31",
        "county_fips": "31115",
        "population": 607,
        "land_area_sq_mi": 563.341,
        "centroid": [
          41.832646,
          -99.416371
        ],
        "county_seat": null
      },
      {
        "county_name": "McPherson County",
        "state_fips": "31",
        "county_fips": "31117",
        "population": 399,
        "land_area_sq_mi": 859.259,
        "centroid": [
          41.560427,
          -101.004858
        ],
        "county_seat": null
      },
      {
        "county_name": "Madison County",
        "state_fips": "31",
        "county_fips": "31119",
        "population": 35585,
        "land_area_sq_mi": 572.612,
        "centroid": [
          42.00636,
          -97.461443
        ],
        "county_seat": null
      },
      {
        "county_name": "Merrick County",
        "state_fips": "31",
        "county_fips": "31121",
        "population": 7668,
        "land_area_sq_mi": 487.794,
        "centroid": [
          41.130786,
          -98.037243
        ],
        "county_seat": null
      },
      {
        "county_name": "Morrill County",
        "state_fips": "31",
        "county_fips": "31123",
        "population": 4555,
        "land_area_sq_mi": 1423.706,
        "centroid": [
          41.708586,
          -103.162925
        ],
        "county_seat": null
      },
      {
        "county_name": "Nance County",
        "state_fips": "31",
        "county_fips": "31125",
        "population": 3380,
        "land_area_sq_mi": 441.595,
        "centroid": [
          41.404591,
          -97.896242
        ],
        "county_seat": null
      },
      {
        "county_name": "Nemaha County",
        "state_fips": "31",
        "county_fips": "31127",
        "population": 7074,
        "land_area_sq_mi": 407.301,
        "centroid": [
          40.401975,
          -95.839188
        ],
        "county_seat": null
      },
      {
        "county_name": "Nuckolls County",
        "state_fips": "31",
        "county_fips": "31129",
        "population": 4095,
        "land_area_sq_mi": 575.155,
        "centroid": [
          40.114628,
          -98.0618
        ],
        "county_seat": null
      },
      {
        "county_name": "Otoe County",
        "state_fips": "31",
        "county_fips": "31131",
        "population": 15912,
        "land_area_sq_mi": 615.616,
        "centroid": [
          40.670824,
          -96.03688
        ],
        "county_seat": null
      },
      {
        "county_name": "Pawnee County",
        "state_fips": "31",
        "county_fips": "31133",
        "population": 2544,
        "land_area_sq_mi": 431.075,
        "centroid": [
          40.133204,
          -96.177346
        ],
        "county_seat": null
      },
      {
        "county_name": "Perkins County",
        "state_fips": "31",
        "county_fips": "31135",
        "population": 2858,
        "land_area_sq_mi": 883.313,
        "centroid": [
          40.844891,
          -101.675458
        ],
        "county_seat": null
      },
      {
        "county_name": "Phelps County",
        "state_fips": "31",
        "county_fips": "31137",
        "population": 8968,
        "land_area_sq_mi": 539.765,
        "centroid": [
          40.466361,
          -99.40454
        ],
        "county_seat": null
      },
      {
        "county_name": "Pierce County",
        "state_fips": "31",
        "county_fips": "31139",
        "population": 7317,
        "land_area_sq_mi": 573.249,
        "centroid": [
          42.259529,
          -97.591612
        ],
        "county_seat": null
      },
      {
        "county_name": "Platte County",
        "state_fips": "31",
        "county_fips": "31141",
        "population": 34296,
        "land_area_sq_mi": 675.118,
        "centroid": [
          41.46697,
          -97.385528
        ],
        "county_seat": null
      },
      {
        "county_name": "Polk County",
        "state_fips": "31",
        "county_fips": "31143",
        "population": 5214,
        "land_area_sq_mi": 438.832,
        "centroid": [
          41.173605,
          -97.55672
        ],
        "county_seat": null
      },
      {
        "county_name": "Red Willow County",
        "state_fips": "31",
        "county_fips": "31145",
        "population": 10702,
        "land_area_sq_mi": 717.17,
        "centroid": [
          40.206742,
          -100.592097
        ],
        "county_seat": null
      },
      {
        "county_name": "Richardson County",
        "state_fips": "31",
        "county_fips": "31147",
        "population": 7871,
        "land_area_sq_mi": 551.841,
        "centroid": [
          40.099879,
          -95.669705
        ],
        "county_seat": null
      },
      {
        "county_name": "Rock County",
        "state_fips": "31",
        "county_fips": "31149",
        "population": 1262,
        "land_area_sq_mi": 1008.291,
        "centroid": [
          42.536738,
          -99.499863
        ],
        "county_seat": null
      },
      {
        "county_name": "Saline County",
        "state_fips": "31",
        "county_fips": "31151",
        "population": 14292,
        "land_area_sq_mi": 574.07,
        "centroid": [
          40.579217,
          -97.016896
        ],
        "county_seat": null
      },
      {
        "county_name": "Sarpy County",
        "state_fips": "31",
        "county_fips": "31153",
        "population": 190604,
        "land_area_sq_mi": 237.996,
        "centroid": [
          41.152889,
          -96.0437
        ],
        "county_seat": null
      },
      {
        "county_name": "Saunders County",
        "state_fips": "31",
        "county_fips": "31155",
        "population": 22278,
        "land_area_sq_mi": 748.703,
        "centroid": [
          41.195383,
          -96.560061
        ],
        "county_seat": null
      },
      {
        "county_name": "Scotts Bluff County",
        "state_fips": "31",
        "county_fips": "31157",
        "population": 36084,
        "land_area_sq_mi": 739.621,
        "centroid": [
          41.865094,
          -103.680393
        ],
        "county_seat": null
      },
      {
        "county_name": "Seward County",
        "state_fips": "31",
        "county_fips": "31159",
        "population": 17609,
        "land_area_sq_mi": 571.43,
        "centroid": [
          40.875087,
          -97.102308
        ],
        "county_seat": null
      },
      {
        "county_name": "Sheridan County",
        "state_fips": "31",
        "county_fips": "31161",
        "population": 5127,
        "land_area_sq_mi": 2440.17,
        "centroid": [
          42.704794,
          -102.404074
        ],
        "county_seat": null
      },
      {
        "county_name": "Sherman County",
        "state_fips": "31",
        "county_fips": "31163",
        "population": 2959,
        "land_area_sq_mi": 565.877,
        "centroid": [
          41.228647,
          -98.968633
        ],
        "county_seat": null
      },
      {
        "county_name": "Sioux County",
        "state_fips": "31",
        "county_fips": "31165",
        "population": 1135,
        "land_area_sq_mi": 2066.723,
        "centroid": [
          42.408762,
          -103.833171
        ],
        "county_seat": null
      },
      {
        "county_name": "Stanton County",
        "state_fips": "31",
        "county_fips": "31167",
        "population": 5842,
        "land_area_sq_mi": 427.633,
        "centroid": [
          41.985101,
          -97.255038
        ],
        "county_seat": null
      },
      {
        "county_name": "Thayer County",
        "state_fips": "31",
        "county_fips": "31169",
        "population": 5034,
        "land_area_sq_mi": 573.789,
        "centroid": [
          40.178256,
          -97.628078
        ],
        "county_seat": null
      },
      {
        "county_name": "Thomas County",
        "state_fips": "31",
        "county_fips": "31171",
        "population": 669,
        "land_area_sq_mi": 712.554,
        "centroid": [
          41.967138,
          -100.565595
        ],
        "county_seat": null
      },
      {
        "county_name": "Thurston County",
        "state_fips": "31",
        "county_fips": "31173",
        "population": 6773,
        "land_area_sq_mi": 393.592,
        "centroid": [
          42.161934,
          -96.522459
        ],
        "county_seat": null
      },
      {
        "county_name": "Valley County",
        "state_fips": "31",
        "county_fips": "31175",
        "population": 4059,
        "land_area_sq_mi": 568.09,
        "centroid": [
          41.573672,
          -98.948914
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "31",
        "county_fips": "31177",
        "population": 20865,
        "land_area_sq_mi": 389.93,
        "centroid": [
          41.504682,
          -96.156611
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "31",
        "county_fips": "31179",
        "population": 9697,
        "land_area_sq_mi": 442.916,
        "centroid": [
          42.223628,
          -97.056303
        ],
        "county_seat": null
      },
      {
        "county_name": "Webster County",
        "state_fips": "31",
        "county_fips": "31181",
        "population": 3395,
        "land_area_sq_mi": 574.913,
        "centroid": [
          40.195862,
          -98.486606
        ],
        "county_seat": null
      },
      {
        "county_name": "Wheeler County",
        "state_fips": "31",
        "county_fips": "31183",
        "population": 774,
        "land_area_sq_mi": 575.183,
        "centroid": [
          41.885209,
          -98.545473
        ],
        "county_seat": null
      },
      {
        "county_name": "York County",
        "state_fips": "31",
        "county_fips": "31185",
        "population": 14125,
        "land_area_sq_mi": 572.516,
        "centroid": [
          40.863485,
          -97.605023
        ],
        "county_seat": null
      }
    ]
