# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Churchill County",
        "state_fips": "32",
        "county_fips": "32001",
        "population": 25516,
        "land_area_sq_mi": 4950.157,
        "centroid": [
          39.474469,
          -118.796052
        ],
        "county_seat": null
      },
      {
        "county_name": "Clark County",
        "state_fips": "32",
        "county_fips": "32003",
        "population": 2265461,
        "land_area_sq_mi": 7891.661,
        "centroid": [
          36.141141,
          -115.152976
        ],
        "county_seat": null
      },
      {
        "county_name": "Douglas County",
        "state_fips": "32",
        "county_fips": "32005",
        "population": 49488,
        "land_area_sq_mi": 710.537,
        "centroid": [
          38.957468,
          -119.756218
        ],
        "county_seat": null
      },
      {
        "county_name": "Elko County",
        "state_fips": "32",
        "county_fips": "32007",
        "population": 53702,
        "land_area_sq_mi": 17173.302,
        "centroid": [
          40.856303,
          -115.534273
        ],
        "county_seat": null
      },
      {
        "county_name": "Esmeralda County",
        "state_fips": "32",
        "county_fips": "32009",
        "population": 729,
        "land_area_sq_mi": 3581.889,
        "centroid": [
          37.704407,
          -117.670635
        ],
        "county_seat": null
      },
      {
        "county_name": "Eureka County",
        "state_fips": "32",
        "county_fips": "32011",
        "population": 1855,
        "land_area_sq_mi": 4175.688,
        "centroid": [
          39.946993,
          -116.209128
        ],
        "county_seat": null
      },
      {
        "county_name": "Humboldt County",
        "state_fips": "32",
        "county_fips": "32013",
        "population": 17285,
        "land_area_sq_mi": 9640.792,
        "centroid": [
          41.017558,
          -117.744296
        ],
        "county_seat": null
      },
      {
        "county_name": "Lander County",
        "state_fips": "32",
        "county_fips": "32015",
        "population": 5734,
        "land_area_sq_mi": 5519.247,
        "centroid": [
          40.49846,
          -116.949528
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "32",
        "county_fips": "32017",
        "population": 4499,
        "land_area_sq_mi": 10633.386,
        "centroid": [
          37.710093,
          -114.626444
        ],
        "county_seat": null
      },
      {
        "county_name": "Lyon County",
        "state_fips": "32",
        "county_fips": "32019",
        "population": 59235,
        "land_area_sq_mi": 2003.054,
        "centroid": [
          39.355756,
          -119.327152
        ],
        "county_seat": null
      },
      {
        "county_name": "Mineral County",
        "state_fips": "32",
        "county_fips": "32021",
        "population": 4554,
        "land_area_sq_mi": 3751.283,
        "centroid": [
          38.601613,
          -118.643399
        ],
        "county_seat": null
      },
      {
        "county_name": "Nye County",
        "state_fips": "32",
        "county_fips": "32023",
        "population": 51591,
        "land_area_sq_mi": 18181.914,
        "centroid": [
          36.414296,
          -116.125667
        ],
        "county_seat": null
      },
      {
        "county_name": "Pershing County",
        "state_fips": "32",
        "county_fips": "32027",
        "population": 6650,
        "land_area_sq_mi": 6036.589,
        "centroid": [
          40.334654,
          -118.294224
        ],
        "county_seat": null
      },
      {
        "county_name": "Storey County",
        "state_fips": "32",
        "county_fips": "32029",
        "population": 4104,
        "land_area_sq_mi": 263.8,
        "centroid": [
          39.389828,
          -119.622432
        ],
        "county_seat": null
      },
      {
        "county_name": "Washoe County",
        "state_fips": "32",
        "county_fips": "32031",
        "population": 486492,
        "land_area_sq_mi": 6315.873,
        "centroid": [
          39.534488,
          -119.793527
        ],
        "county_seat": null
      },
      {
        "county_name": "White Pine County",
        "state_fips": "32",
        "county_fips": "32033",
        "population": 9080,
        "land_area_sq_mi": 8886.665,
        "centroid": [
          39.278317,
          -114.875458
        ],
        "county_seat": null
      },
      {
        "county_name": "Carson City County",
        "state_fips": "32",
        "county_fips": "32510",
        "population": 58639,
        "land_area_sq_mi": 144.534,
        "centroid": [
          39.166096,
          -119.75408
        ],
        "county_seat": null
      }
    ]
