# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Accomack County",
        "state_fips": "51",
        "county_fips": "51001",
        "population": 33413,
        "land_area_sq_mi": 449.303,
        "centroid": [
          37.789059,
          -75.629449
        ],
        "county_seat": null
      },
      {
        "county_name": "Albemarle County",
        "state_fips": "51",
        "county_fips": "51003",
        "population": 112395,
        "land_area_sq_mi": 720.477,
        "centroid": [
          38.052435,
          -78.519241
        ],
        "county_seat": null
      },
      {
        "county_name": "Alleghany County",
        "state_fips": "51",
        "county_fips": "51005",
        "population": 15223,
        "land_area_sq_mi": 446.572,
        "centroid": [
          37.802458,
          -79.929858
        ],
        "county_seat": null
      },
      {
        "county_name": "Amelia County",
        "state_fips": "51",
        "county_fips": "51007",
        "population": 13265,
        "land_area_sq_mi": 355.36,
        "centroid": [
          37.34151,
          -77.973985
        ],
        "county_seat": null
      },
      {
        "county_name": "Amherst County",
        "state_fips": "51",
        "county_fips": "51009",
        "population": 31307,
        "land_area_sq_mi": 473.962,
        "centroid": [
          37.518911,
          -79.1035
        ],
        "county_seat": null
      },
      {
        "county_name": "Appomattox County",
        "state_fips": "51",
        "county_fips": "51011",
        "population": 16119,
        "land_area_sq_mi": 334.224,
        "centroid": [
          37.36019,
          -78.83702
        ],
        "county_seat": null
      },
      {
        "county_name": "Arlington County",
        "state_fips": "51",
        "county_fips": "51013",
        "population": 238643,
        "land_area_sq_mi": 25.997,
        "centroid": [
          38.874744,
          -77.099874
        ],
        "county_seat": null
      },
      {
        "county_name": "Augusta County",
        "state_fips": "51",
        "county_fips": "51015",
        "population": 77487,
        "land_area_sq_mi": 967.074,
        "centroid": [
          38.127146,
          -79.03105
        ],
        "county_seat": null
      },
      {
        "county_name": "Bath County",
        "state_fips": "51",
        "county_fips": "51017",
        "population": 4209,
        "land_area_sq_mi": 529.202,
        "centroid": [
          38.018911,
          -79.758923
        ],
        "county_seat": null
      },
      {
        "county_name": "Bedford County",
        "state_fips": "51",
        "county_fips": "51019",
        "population": 79462,
        "land_area_sq_mi": 760.116,
        "centroid": [
          37.320204,
          -79.485385
        ],
        "county_seat": null
      },
      {
        "county_name": "Bland County",
        "state_fips": "51",
        "county_fips": "51021",
        "population": 6270,
        "land_area_sq_mi": 357.645,
        "centroid": [
          37.150078,
          -81.087264
        ],
        "county_seat": null
      },
      {
        "county_name": "Botetourt County",
        "state_fips": "51",
        "county_fips": "51023",
        "population": 33596,
        "land_area_sq_mi": 541.276,
        "centroid": [
          37.446422,
          -79.853138
        ],
        "county_seat": null
      },
      {
        "county_name": "Brunswick County",
        "state_fips": "51",
        "county_fips": "51025",
        "population": 15849,
        "land_area_sq_mi": 566.351,
        "centroid": [
          36.758266,
          -77.863297
        ],
        "county_seat": null
      },
      {
        "county_name": "Buchanan County",
        "state_fips": "51",
        "county_fips": "51027",
        "population": 20355,
        "land_area_sq_mi": 502.855,
        "centroid": [
          37.264124,
          -82.059132
        ],
        "county_seat": null
      },
      {
        "county_name": "Buckingham County",
        "state_fips": "51",
        "county_fips": "51029",
        "population": 16824,
        "land_area_sq_mi": 579.623,
        "centroid": [
          37.580161,
          -78.485095
        ],
        "county_seat": null
      },
      {
        "county_name": "Campbell County",
        "state_fips": "51",
        "county_fips": "51031",
        "population": 55696,
        "land_area_sq_mi": 503.257,
        "centroid": [
          37.261518,
          -79.169047
        ],
        "county_seat": null
      },
      {
        "county_name": "Caroline County",
        "state_fips": "51",
        "county_fips": "51033",
        "population": 30887,
        "land_area_sq_mi": 527.365,
        "centroid": [
          38.0087,
          -77.438652
        ],
        "county_seat": null
      },
      {
        "county_name": "Carroll County",
        "state_fips": "51",
        "county_fips": "51035",
        "population": 29155,
        "land_area_sq_mi": 474.742,
        "centroid": [
          36.713036,
          -80.762136
        ],
        "county_seat": null
      },
      {
        "county_name": "Charles City County",
        "state_fips": "51",
        "county_fips": "51036",
        "population": 6773,
        "land_area_sq_mi": 182.901,
        "centroid": [
          37.383394,
          -77.101446
        ],
        "county_seat": null
      },
      {
        "county_name": "Charlotte County",
        "state_fips": "51",
        "county_fips": "51037",
        "population": 11529,
        "land_area_sq_mi": 475.296,
        "centroid": [
          37.02206,
          -78.630278
        ],
        "county_seat": null
      },
      {
        "county_name": "Chesterfield County",
        "state_fips": "51",
        "county_fips": "51041",
        "population": 364548,
        "land_area_sq_mi": 423.506,
        "centroid": [
          37.418312,
          -77.556155
        ],
        "county_seat": null
      },
      {
        "county_name": "Clarke County",
        "state_fips": "51",
        "county_fips": "51043",
        "population": 14783,
        "land_area_sq_mi": 175.958,
        "centroid": [
          39.129417,
          -77.987382
        ],
        "county_seat": null
      },
      {
        "county_name": "Craig County",
        "state_fips": "51",
        "county_fips": "51045",
        "population": 4892,
        "land_area_sq_mi": 328.098,
        "centroid": [
          37.47542,
          -80.173756
        ],
        "county_seat": null
      },
      {
        "county_name": "Culpeper County",
        "state_fips": "51",
        "county_fips": "51047",
        "population": 52552,
        "land_area_sq_mi": 379.179,
        "centroid": [
          38.498243,
          -77.999051
        ],
        "county_seat": null
      },
      {
        "county_name": "Cumberland County",
        "state_fips": "51",
        "county_fips": "51049",
        "population": 9675,
        "land_area_sq_mi": 297.474,
        "centroid": [
          37.481359,
          -78.258673
        ],
        "county_seat": null
      },
      {
        "county_name": "Dickenson County",
        "state_fips": "51",
        "county_fips": "51051",
        "population": 14124,
        "land_area_sq_mi": 330.442,
        "centroid": [
          37.143369,
          -82.378751
        ],
        "county_seat": null
      },
      {
        "county_name": "Dinwiddie County",
        "state_fips": "51",
        "county_fips": "51053",
        "population": 27947,
        "land_area_sq_mi": 503.826,
        "centroid": [
          37.135652,
          -77.56051
        ],
        "county_seat": null
      },
      {
        "county_name": "Essex County",
        "state_fips": "51",
        "county_fips": "51057",
        "population": 10599,
        "land_area_sq_mi": 257.354,
        "centroid": [
          37.908781,
          -76.901329
        ],
        "county_seat": null
      },
      {
        "county_name": "Fairfax County",
        "state_fips": "51",
        "county_fips": "51059",
        "population": 1150309,
        "land_area_sq_mi": 391.02,
        "centroid": [
          38.844726,
          -77.25911
        ],
        "county_seat": null
      },
      {
        "county_name": "Fauquier County",
        "state_fips": "51",
        "county_fips": "51061",
        "population": 72972,
        "land_area_sq_mi": 647.994,
        "centroid": [
          38.695515,
          -77.774094
        ],
        "county_seat": null
      },
      {
        "county_name": "Floyd County",
        "state_fips": "51",
        "county_fips": "51063",
        "population": 15476,
        "land_area_sq_mi": 380.923,
        "centroid": [
          36.943205,
          -80.342366
        ],
        "county_seat": null
      },
      {
        "county_name": "Fluvanna County",
        "state_fips": "51",
        "county_fips": "51065",
        "population": 27249,
        "land_area_sq_mi": 287.117,
        "centroid": [
          37.888642,
          -78.301835
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "51",
        "county_fips": "51067",
        "population": 54477,
        "land_area_sq_mi": 690.611,
        "centroid": [
          37.02094,
          -79.857581
        ],
        "county_seat": null
      },
      {
        "county_name": "Frederick County",
        "state_fips": "51",
        "county_fips": "51069",
        "population": 91419,
        "land_area_sq_mi": 413.135,
        "centroid": [
          39.166263,
          -78.188362
        ],
        "county_seat": null
      },
      {
        "county_name": "Giles County",
        "state_fips": "51",
        "county_fips": "51071",
        "population": 16787,
        "land_area_sq_mi": 357.225,
        "centroid": [
          37.318524,
          -80.717789
        ],
        "county_seat": null
      },
      {
        "county_name": "Gloucester County",
        "state_fips": "51",
        "county_fips": "51073",
        "population": 38711,
        "land_area_sq_mi": 217.81,
        "centroid": [
          37.37631,
          -76.529483
        ],
        "county_seat": null
      },
      {
        "county_name": "Goochland County",
        "state_fips": "51",
        "county_fips": "51075",
        "population": 24727,
        "land_area_sq_mi": 282.101,
        "centroid": [
          37.70005,
          -77.83757
        ],
        "county_seat": null
      },
      {
        "county_name": "Grayson County",
        "state_fips": "51",
        "county_fips": "51077",
        "population": 15333,
        "land_area_sq_mi": 441.785,
        "centroid": [
          36.645604,
          -81.114627
        ],
        "county_seat": null
      },
      {
        "county_name": "Greene County",
        "state_fips": "51",
        "county_fips": "51079",
        "population": 20552,
        "land_area_sq_mi": 155.947,
        "centroid": [
          38.250643,
          -78.419667
        ],
        "county_seat": null
      },
      {
        "county_name": "Greensville County",
        "state_fips": "51",
        "county_fips": "51081",
        "population": 11391,
        "land_area_sq_mi": 295.377,
        "centroid": [
          36.723794,
          -77.536797
        ],
        "county_seat": null
      },
      {
        "county_name": "Halifax County",
        "state_fips": "51",
        "county_fips": "51083",
        "population": 34022,
        "land_area_sq_mi": 817.731,
        "centroid": [
          36.748512,
          -78.926925
        ],
        "county_seat": null
      },
      {
        "county_name": "Hanover County",
        "state_fips": "51",
        "county_fips": "51085",
        "population": 109979,
        "land_area_sq_mi": 467.573,
        "centroid": [
          37.686944,
          -77.418063
        ],
        "county_seat": null
      },
      {
        "county_name": "Henrico County",
        "state_fips": "51",
        "county_fips": "51087",
        "population": 334389,
        "land_area_sq_mi": 233.699,
        "centroid": [
          37.604639,
          -77.498572
        ],
        "county_seat": null
      },
      {
        "county_name": "Henry County",
        "state_fips": "51",
        "county_fips": "51089",
        "population": 50948,
        "land_area_sq_mi": 382.351,
        "centroid": [
          36.6901,
          -79.902329
        ],
        "county_seat": null
      },
      {
        "county_name": "Highland County",
        "state_fips": "51",
        "county_fips": "51091",
        "population": 2232,
        "land_area_sq_mi": 415.163,
        "centroid": [
          38.386566,
          -79.570507
        ],
        "county_seat": null
      },
      {
        "county_name": "Isle of Wight County",
        "state_fips": "51",
        "county_fips": "51093",
        "population": 38606,
        "land_area_sq_mi": 315.685,
        "centroid": [
          36.92455,
          -76.644703
        ],
        "county_seat": null
      },
      {
        "county_name": "James City County",
        "state_fips": "51",
        "county_fips": "51095",
        "population": 78254,
        "land_area_sq_mi": 142.298,
        "centroid": [
          37.297936,
          -76.75988
        ],
        "county_seat": null
      },
      {
        "county_name": "King and Queen County",
        "state_fips": "51",
        "county_fips": "51097",
        "population": 6608,
        "land_area_sq_mi": 315.131,
        "centroid": [
          37.69798,
          -76.891199
        ],
        "county_seat": null
      },
      {
        "county_name": "King George County",
        "state_fips": "51",
        "county_fips": "51099",
        "population": 26723,
        "land_area_sq_mi": 179.628,
        "centroid": [
          38.290179,
          -77.163647
        ],
        "county_seat": null
      },
      {
        "county_name": "King William County",
        "state_fips": "51",
        "county_fips": "51101",
        "population": 17810,
        "land_area_sq_mi": 273.91,
        "centroid": [
          37.705655,
          -77.062634
        ],
        "county_seat": null
      },
      {
        "county_name": "Lancaster County",
        "state_fips": "51",
        "county_fips": "51103",
        "population": 10919,
        "land_area_sq_mi": 133.306,
        "centroid": [
          37.703954,
          -76.435886
        ],
        "county_seat": null
      },
      {
        "county_name": "Lee County",
        "state_fips": "51",
        "county_fips": "51105",
        "population": 22173,
        "land_area_sq_mi": 435.378,
        "centroid": [
          36.714437,
          -83.102612
        ],
        "county_seat": null
      },
      {
        "county_name": "Loudoun County",
        "state_fips": "51",
        "county_fips": "51107",
        "population": 420959,
        "land_area_sq_mi": 515.737,
        "centroid": [
          39.034341,
          -77.51754
        ],
        "county_seat": null
      },
      {
        "county_name": "Louisa County",
        "state_fips": "51",
        "county_fips": "51109",
        "population": 37596,
        "land_area_sq_mi": 495.006,
        "centroid": [
          37.982264,
          -77.971413
        ],
        "county_seat": null
      },
      {
        "county_name": "Lunenburg County",
        "state_fips": "51",
        "county_fips": "51111",
        "population": 11936,
        "land_area_sq_mi": 431.7,
        "centroid": [
          36.970037,
          -78.216617
        ],
        "county_seat": null
      },
      {
        "county_name": "Madison County",
        "state_fips": "51",
        "county_fips": "51113",
        "population": 13837,
        "land_area_sq_mi": 320.639,
        "centroid": [
          38.376095,
          -78.234462
        ],
        "county_seat": null
      },
      {
        "county_name": "Mathews County",
        "state_fips": "51",
        "county_fips": "51115",
        "population": 8533,
        "land_area_sq_mi": 85.911,
        "centroid": [
          37.445239,
          -76.342339
        ],
        "county_seat": null
      },
      {
        "county_name": "Mecklenburg County",
        "state_fips": "51",
        "county_fips": "51117",
        "population": 30319,
        "land_area_sq_mi": 625.31,
        "centroid": [
          36.690417,
          -78.318472
        ],
        "county_seat": null
      },
      {
        "county_name": "Middlesex County",
        "state_fips": "51",
        "county_fips": "51119",
        "population": 10625,
        "land_area_sq_mi": 130.33,
        "centroid": [
          37.601288,
          -76.503852
        ],
        "county_seat": null
      },
      {
        "county_name": "Montgomery County",
        "state_fips": "51",
        "county_fips": "51121",
        "population": 99721,
        "land_area_sq_mi": 386.848,
        "centroid": [
          37.189478,
          -80.413551
        ],
        "county_seat": null
      },
      {
        "county_name": "Nelson County",
        "state_fips": "51",
        "county_fips": "51125",
        "population": 14775,
        "land_area_sq_mi": 470.745,
        "centroid": [
          37.812328,
          -78.87302
        ],
        "county_seat": null
      },
      {
        "county_name": "New Kent County",
        "state_fips": "51",
        "county_fips": "51127",
        "population": 22945,
        "land_area_sq_mi": 210.031,
        "centroid": [
          37.497961,
          -77.041127
        ],
        "county_seat": null
      },
      {
        "county_name": "Northampton County",
        "state_fips": "51",
        "county_fips": "51131",
        "population": 12282,
        "land_area_sq_mi": 211.712,
        "centroid": [
          37.388365,
          -75.919193
        ],
        "county_seat": null
      },
      {
        "county_name": "Northumberland County",
        "state_fips": "51",
        "county_fips": "51133",
        "population": 11839,
        "land_area_sq_mi": 191.433,
        "centroid": [
          37.888285,
          -76.408327
        ],
        "county_seat": null
      },
      {
        "county_name": "Nottoway County",
        "state_fips": "51",
        "county_fips": "51135",
        "population": 15642,
        "land_area_sq_mi": 314.39,
        "centroid": [
          37.1463,
          -78.078841
        ],
        "county_seat": null
      },
      {
        "county_name": "Orange County",
        "state_fips": "51",
        "county_fips": "51137",
        "population": 36254,
        "land_area_sq_mi": 340.515,
        "centroid": [
          38.271901,
          -77.954737
        ],
        "county_seat": null
      },
      {
        "county_name": "Page County",
        "state_fips": "51",
        "county_fips": "51139",
        "population": 23709,
        "land_area_sq_mi": 310.017,
        "centroid": [
          38.60454,
          -78.500572
        ],
        "county_seat": null
      },
      {
        "county_name": "Patrick County",
        "state_fips": "51",
        "county_fips": "51141",
        "population": 17608,
        "land_area_sq_mi": 482.957,
        "centroid": [
          36.654401,
          -80.284499
        ],
        "county_seat": null
      },
      {
        "county_name": "Pittsylvania County",
        "state_fips": "51",
        "county_fips": "51143",
        "population": 60501,
        "land_area_sq_mi": 969.003,
        "centroid": [
          36.76981,
          -79.411183
        ],
        "county_seat": null
      },
      {
        "county_name": "Powhatan County",
        "state_fips": "51",
        "county_fips": "51145",
        "population": 30333,
        "land_area_sq_mi": 260.202,
        "centroid": [
          37.54288,
          -77.875784
        ],
        "county_seat": null
      },
      {
        "county_name": "Prince Edward County",
        "state_fips": "51",
        "county_fips": "51147",
        "population": 21849,
        "land_area_sq_mi": 349.946,
        "centroid": [
          37.257792,
          -78.422205
        ],
        "county_seat": null
      },
      {
        "county_name": "Prince George County",
        "state_fips": "51",
        "county_fips": "51149",
        "population": 43010,
        "land_area_sq_mi": 265.342,
        "centroid": [
          37.219071,
          -77.300134
        ],
        "county_seat": null
      },
      {
        "county_name": "Prince William County",
        "state_fips": "51",
        "county_fips": "51153",
        "population": 482204,
        "land_area_sq_mi": 335.255,
        "centroid": [
          38.691881,
          -77.411563
        ],
        "county_seat": null
      },
      {
        "county_name": "Pulaski County",
        "state_fips": "51",
        "county_fips": "51155",
        "population": 33800,
        "land_area_sq_mi": 319.84,
        "centroid": [
          37.082088,
          -80.703764
        ],
        "county_seat": null
      },
      {
        "county_name": "Rappahannock County",
        "state_fips": "51",
        "county_fips": "51157",
        "population": 7348,
        "land_area_sq_mi": 266.372,
        "centroid": [
          38.695715,
          -78.123809
        ],
        "county_seat": null
      },
      {
        "county_name": "Richmond County",
        "state_fips": "51",
        "county_fips": "51159",
        "population": 8923,
        "land_area_sq_mi": 191.478,
        "centroid": [
          37.947361,
          -76.716497
        ],
        "county_seat": null
      },
      {
        "county_name": "Roanoke County",
        "state_fips": "51",
        "county_fips": "51161",
        "population": 96929,
        "land_area_sq_mi": 250.548,
        "centroid": [
          37.270592,
          -79.990218
        ],
        "county_seat": null
      },
      {
        "county_name": "Rockbridge County",
        "state_fips": "51",
        "county_fips": "51163",
        "population": 22650,
        "land_area_sq_mi": 596.548,
        "centroid": [
          37.787711,
          -79.427154
        ],
        "county_seat": null
      },
      {
        "county_name": "Rockingham County",
        "state_fips": "51",
        "county_fips": "51165",
        "population": 83757,
        "land_area_sq_mi": 849.796,
        "centroid": [
          38.452246,
          -78.83815
        ],
        "county_seat": null
      },
      {
        "county_name": "Russell County",
        "state_fips": "51",
        "county_fips": "51167",
        "population": 25781,
        "land_area_sq_mi": 473.524,
        "centroid": [
          36.935321,
          -82.086825
        ],
        "county_seat": null
      },
      {
        "county_name": "Scott County",
        "state_fips": "51",
        "county_fips": "51169",
        "population": 21576,
        "land_area_sq_mi": 535.827,
        "centroid": [
          36.683147,
          -82.596616
        ],
        "county_seat": null
      },
      {
        "county_name": "Shenandoah County",
        "state_fips": "51",
        "county_fips": "51171",
        "population": 44186,
        "land_area_sq_mi": 508.08,
        "centroid": [
          38.870724,
          -78.526715
        ],
        "county_seat": null
      },
      {
        "county_name": "Smyth County",
        "state_fips": "51",
        "county_fips": "51173",
        "population": 29800,
        "land_area_sq_mi": 451.439,
        "centroid": [
          36.828217,
          -81.574516
        ],
        "county_seat": null
      },
      {
        "county_name": "Southampton County",
        "state_fips": "51",
        "county_fips": "51175",
        "population": 17996,
        "land_area_sq_mi": 599.249,
        "centroid": [
          36.717292,
          -77.067406
        ],
        "county_seat": null
      },
      {
        "county_name": "Spotsylvania County",
        "state_fips": "51",
        "county_fips": "51177",
        "population": 140032,
        "land_area_sq_mi": 401.968,
        "centroid": [
          38.238583,
          -77.569152
        ],
        "county_seat": null
      },
      {
        "county_name": "Stafford County",
        "state_fips": "51",
        "county_fips": "51179",
        "population": 156927,
        "land_area_sq_mi": 268.497,
        "centroid": [
          38.415146,
          -77.45027
        ],
        "county_seat": null
      },
      {
        "county_name": "Surry County",
        "state_fips": "51",
        "county_fips": "51181",
        "population": 6561,
        "land_area_sq_mi": 278.949,
        "centroid": [
          37.116405,
          -76.868309
        ],
        "county_seat": null
      },
      {
        "county_name": "Sussex County",
        "state_fips": "51",
        "county_fips": "51183",
        "population": 10829,
        "land_area_sq_mi": 490.244,
        "centroid": [
          36.973226,
          -77.212078
        ],
        "county_seat": null
      },
      {
        "county_name": "Tazewell County",
        "state_fips": "51",
        "county_fips": "51185",
        "population": 40429,
        "land_area_sq_mi": 518.791,
        "centroid": [
          37.146681,
          -81.564501
        ],
        "county_seat": null
      },
      {
        "county_name": "Warren County",
        "state_fips": "51",
        "county_fips": "51187",
        "population": 40727,
        "land_area_sq_mi": 214.572,
        "centroid": [
          38.927717,
          -78.178302
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "51",
        "county_fips": "51191",
        "population": 53935,
        "land_area_sq_mi": 561.193,
        "centroid": [
          36.702853,
          -81.972673
        ],
        "county_seat": null
      },
      {
        "county_name": "Westmoreland County",
        "state_fips": "51",
        "county_fips": "51193",
        "population": 18477,
        "land_area_sq_mi": 229.327,
        "centroid": [
          38.160791,
          -76.854228
        ],
        "county_seat": null
      },
      {
        "county_name": "Wise County",
        "state_fips": "51",
        "county_fips": "51195",
        "population": 36130,
        "land_area_sq_mi": 403.443,
        "centroid": [
          36.951164,
          -82.612989
        ],
        "county_seat": null
      },
      {
        "county_name": "Wythe County",
        "state_fips": "51",
        "county_fips": "51197",
        "population": 28290,
        "land_area_sq_mi": 461.952,
        "centroid": [
          36.919638,
          -81.06853
        ],
        "county_seat": null
      },
      {
        "county_name": "York County",
        "state_fips": "51",
        "county_fips": "51199",
        "population": 70045,
        "land_area_sq_mi": 104.701,
        "centroid": [
          37.174598,
          -76.495318
        ],
        "county_seat": null
      },
      {
        "county_name": "Alexandria County",
        "state_fips": "51",
        "county_fips": "51510",
        "population": 159467,
        "land_area_sq_mi": 14.935,
        "centroid": [
          38.819775,
          -77.091035
        ],
        "county_seat": null
      },
      {
        "county_name": "Bristol County",
        "state_fips": "51",
        "county_fips": "51520",
        "population": 17219,
        "land_area_sq_mi": 12.871,
        "centroid": [
          36.610521,
          -82.169169
        ],
        "county_seat": null
      },
      {
        "county_name": "Buena Vista County",
        "state_fips": "51",
        "county_fips": "51530",
        "population": 6641,
        "land_area_sq_mi": 6.438,
        "centroid": [
          37.733971,
          -79.352679
        ],
        "county_seat": null
      },
      {
        "county_name": "Charlottesville County",
        "state_fips": "51",
        "county_fips": "51540",
        "population": 46553,
        "land_area_sq_mi": 10.245,
        "centroid": [
          38.033197,
          -78.490351
        ],
        "county_seat": null
      },
      {
        "county_name": "Chesapeake County",
        "state_fips": "51",
        "county_fips": "51550",
        "population": 249422,
        "land_area_sq_mi": 338.456,
        "centroid": [
          36.755679,
          -76.282736
        ],
        "county_seat": null
      },
      {
        "county_name": "Colonial Heights County",
        "state_fips": "51",
        "county_fips": "51570",
        "population": 18170,
        "land_area_sq_mi": 7.519,
        "centroid": [
          37.264114,
          -77.401819
        ],
        "county_seat": null
      },
      {
        "county_name": "Covington County",
        "state_fips": "51",
        "county_fips": "51580",
        "population": 5737,
        "land_area_sq_mi": 5.469,
        "centroid": [
          37.781159,
          -79.989386
        ],
        "county_seat": null
      },
      {
        "county_name": "Danville County",
        "state_fips": "51",
        "county_fips": "51590",
        "population": 42590,
        "land_area_sq_mi": 42.803,
        "centroid": [
          36.591483,
          -79.409217
        ],
        "county_seat": null
      },
      {
        "county_name": "Emporia County",
        "state_fips": "51",
        "county_fips": "51595",
        "population": 5766,
        "land_area_sq_mi": 6.629,
        "centroid": [
          36.692193,
          -77.541334
        ],
        "county_seat": null
      },
      {
        "county_name": "Fairfax County",
        "state_fips": "51",
        "county_fips": "51600",
        "population": 24146,
        "land_area_sq_mi": 6.241,
        "centroid": [
          38.851844,
          -77.302407
        ],
        "county_seat": null
      },
      {
        "county_name": "Falls Church County",
        "state_fips": "51",
        "county_fips": "51610",
        "population": 14658,
        "land_area_sq_mi": 2.046,
        "centroid": [
          38.883587,
          -77.174338
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "51",
        "county_fips": "51620",
        "population": 8180,
        "land_area_sq_mi": 8.277,
        "centroid": [
          36.679019,
          -76.937037
        ],
        "county_seat": null
      },
      {
        "county_name": "Fredericksburg County",
        "state_fips": "51",
        "county_fips": "51630",
        "population": 27982,
        "land_area_sq_mi": 10.45,
        "centroid": [
          38.299101,
          -77.483494
        ],
        "county_seat": null
      },
      {
        "county_name": "Galax County",
        "state_fips": "51",
        "county_fips": "51640",
        "population": 6720,
        "land_area_sq_mi": 8.236,
        "centroid": [
          36.666194,
          -80.918852
        ],
        "county_seat": null
      },
      {
        "county_name": "Hampton County",
        "state_fips": "51",
        "county_fips": "51650",
        "population": 137148,
        "land_area_sq_mi": 51.461,
        "centroid": [
          37.043069,
          -76.367924
        ],
        "county_seat": null
      },
      {
        "county_name": "Harrisonburg County",
        "state_fips": "51",
        "county_fips": "51660",
        "population": 51814,
        "land_area_sq_mi": 17.336,
        "centroid": [
          38.4408,
          -78.868276
        ],
        "county_seat": null
      },
      {
        "county_name": "Hopewell County",
        "state_fips": "51",
        "county_fips": "51670",
        "population": 23033,
        "land_area_sq_mi": 10.354,
        "centroid": [
          37.289394,
          -77.305511
        ],
        "county_seat": null
      },
      {
        "county_name": "Lexington County",
        "state_fips": "51",
        "county_fips": "51678",
        "population": 7320,
        "land_area_sq_mi": 2.499,
        "centroid": [
          37.784392,
          -79.443722
        ],
        "county_seat": null
      },
      {
        "county_name": "Lynchburg County",
        "state_fips": "51",
        "county_fips": "51680",
        "population": 79009,
        "land_area_sq_mi": 48.917,
        "centroid": [
          37.39283,
          -79.190579
        ],
        "county_seat": null
      },
      {
        "county_name": "Manassas County",
        "state_fips": "51",
        "county_fips": "51683",
        "population": 42772,
        "land_area_sq_mi": 9.843,
        "centroid": [
          38.75274,
          -77.475101
        ],
        "county_seat": null
      },
      {
        "county_name": "Manassas Park County",
        "state_fips": "51",
        "county_fips": "51685",
        "population": 17219,
        "land_area_sq_mi": 3.034,
        "centroid": [
          38.772165,
          -77.448688
        ],
        "county_seat": null
      },
      {
        "county_name": "Martinsville County",
        "state_fips": "51",
        "county_fips": "51690",
        "population": 13485,
        "land_area_sq_mi": 10.956,
        "centroid": [
          36.682806,
          -79.863773
        ],
        "county_seat": null
      },
      {
        "county_name": "Newport News County",
        "state_fips": "51",
        "county_fips": "51700",
        "population": 186247,
        "land_area_sq_mi": 68.996,
        "centroid": [
          37.090511,
          -76.496261
        ],
        "county_seat": null
      },
      {
        "county_name": "Norfolk County",
        "state_fips": "51",
        "county_fips": "51710",
        "population": 238005,
        "land_area_sq_mi": 53.275,
        "centroid": [
          36.896214,
          -76.260623
        ],
        "county_seat": null
      },
      {
        "county_name": "Norton County",
        "state_fips": "51",
        "county_fips": "51720",
        "population": 3687,
        "land_area_sq_mi": 7.477,
        "centroid": [
          36.937981,
          -82.623258
        ],
        "county_seat": null
      },
      {
        "county_name": "Petersburg County",
        "state_fips": "51",
        "county_fips": "51730",
        "population": 33458,
        "land_area_sq_mi": 22.72,
        "centroid": [
          37.209954,
          -77.395423
        ],
        "county_seat": null
      },
      {
        "county_name": "Poquoson County",
        "state_fips": "51",
        "county_fips": "51735",
        "population": 12460,
        "land_area_sq_mi": 15.357,
        "centroid": [
          37.131572,
          -76.381528
        ],
        "county_seat": null
      },
      {
        "county_name": "Portsmouth County",
        "state_fips": "51",
        "county_fips": "51740",
        "population": 97915,
        "land_area_sq_mi": 33.301,
        "centroid": [
          36.833211,
          -76.35284
        ],
        "county_seat": null
      },
      {
        "county_name": "Radford County",
        "state_fips": "51",
        "county_fips": "51750",
        "population": 16070,
        "land_area_sq_mi": 9.676,
        "centroid": [
          37.128256,
          -80.559565
        ],
        "county_seat": null
      },
      {
        "county_name": "Richmond County",
        "state_fips": "51",
        "county_fips": "51760",
        "population": 226610,
        "land_area_sq_mi": 59.925,
        "centroid": [
          37.535453,
          -77.466456
        ],
        "county_seat": null
      },
      {
        "county_name": "Roanoke County",
        "state_fips": "51",
        "county_fips": "51770",
        "population": 100011,
        "land_area_sq_mi": 42.521,
        "centroid": [
          37.27853,
          -79.96024
        ],
        "county_seat": null
      },
      {
        "county_name": "Salem County",
        "state_fips": "51",
        "county_fips": "51775",
        "population": 25346,
        "land_area_sq_mi": 14.517,
        "centroid": [
          37.286907,
          -80.056262
        ],
        "county_seat": null
      },
      {
        "county_name": "Staunton County",
        "state_fips": "51",
        "county_fips": "51790",
        "population": 25750,
        "land_area_sq_mi": 19.92,
        "centroid": [
          38.157632,
          -79.07724
        ],
        "county_seat": null
      },
      {
        "county_name": "Suffolk County",
        "state_fips": "51",
        "county_fips": "51800",
        "population": 94324,
        "land_area_sq_mi": 399.167,
        "centroid": [
          36.781867,
          -76.551079
        ],
        "county_seat": null
      },
      {
        "county_name": "Virginia Beach County",
        "state_fips": "51",
        "county_fips": "51810",
        "population": 459470,
        "land_area_sq_mi": 244.72,
        "centroid": [
          36.821388,
          -76.100566
        ],
        "county_seat": null
      },
      {
        "county_name": "Waynesboro County",
        "state_fips": "51",
        "county_fips": "51820",
        "population": 22196,
        "land_area_sq_mi": 14.97,
        "centroid": [
          38.072102,
          -78.898326
        ],
        "county_seat": null
      },
      {
        "county_name": "Williamsburg County",
        "state_fips": "51",
        "county_fips": "51830",
        "population": 15425,
        "land_area_sq_mi": 8.938,
        "centroid": [
          37.275238,
          -76.710426
        ],
        "county_seat": null
      },
      {
        "county_name": "Winchester County",
        "state_fips": "51",
        "county_fips": "51840",
        "population": 28120,
        "land_area_sq_mi": 9.193,
        "centroid": [
          39.174971,
          -78.170677
        ],
        "county_seat": null
      }
    ]
