# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adair County",
        "state_fips": "40",
        "county_fips": "40001",
        "population": 19495,
        "land_area_sq_mi": 573.881,
        "centroid": [
          35.887468,
          -94.635683
        ],
        "county_seat": null
      },
      {
        "county_name": "Alfalfa County",
        "state_fips": "40",
        "county_fips": "40003",
        "population": 5699,
        "land_area_sq_mi": 866.565,
        "centroid": [
          36.658546,
          -98.317631
        ],
        "county_seat": null
      },
      {
        "county_name": "Atoka County",
        "state_fips": "40",
        "county_fips": "40005",
        "population": 14143,
        "land_area_sq_mi": 975.453,
        "centroid": [
          34.329959,
          -96.097526
        ],
        "county_seat": null
      },
      {
        "county_name": "Beaver County",
        "state_fips": "40",
        "county_fips": "40007",
        "population": 5049,
        "land_area_sq_mi": 1814.837,
        "centroid": [
          36.829383,
          -100.638158
        ],
        "county_seat": null
      },
      {
        "county_name": "Beckham County",
        "state_fips": "40",
        "county_fips": "40009",
        "population": 22410,
        "land_area_sq_mi": 901.675,
        "centroid": [
          35.361158,
          -99.511022
        ],
        "county_seat": null
      },
      {
        "county_name": "Blaine County",
        "state_fips": "40",
        "county_fips": "40011",
        "population": 8735,
        "land_area_sq_mi": 928.463,
        "centroid": [
          35.885203,
          -98.428177
        ],
        "county_seat": null
      },
      {
        "county_name": "Bryan County",
        "state_fips": "40",
        "county_fips": "40013",
        "population": 46067,
        "land_area_sq_mi": 904.348,
        "centroid": [
          33.980731,
          -96.386125
        ],
        "county_seat": null
      },
      {
        "county_name": "Caddo County",
        "state_fips": "40",
        "county_fips": "40015",
        "population": 26945,
        "land_area_sq_mi": 1277.754,
        "centroid": [
          35.175959,
          -98.339383
        ],
        "county_seat": null
      },
      {
        "county_name": "Canadian County",
        "state_fips": "40",
        "county_fips": "40017",
        "population": 154405,
        "land_area_sq_mi": 896.573,
        "centroid": [
          35.493359,
          -97.766177
        ],
        "county_seat": null
      },
      {
        "county_name": "Carter County",
        "state_fips": "40",
        "county_fips": "40019",
        "population": 48003,
        "land_area_sq_mi": 822.301,
        "centroid": [
          34.189514,
          -97.19745
        ],
        "county_seat": null
      },
      {
        "county_name": "Cherokee County",
        "state_fips": "40",
        "county_fips": "40021",
        "population": 47078,
        "land_area_sq_mi": 749.127,
        "centroid": [
          35.902314,
          -94.995607
        ],
        "county_seat": null
      },
      {
        "county_name": "Choctaw County",
        "state_fips": "40",
        "county_fips": "40023",
        "population": 14204,
        "land_area_sq_mi": 770.383,
        "centroid": [
          34.019064,
          -95.528308
        ],
        "county_seat": null
      },
      {
        "county_name": "Cimarron County",
        "state_fips": "40",
        "county_fips": "40025",
        "population": 2296,
        "land_area_sq_mi": 1834.808,
        "centroid": [
          36.734437,
          -102.496037
        ],
        "county_seat": null
      },
      {
        "county_name": "Cleveland County",
        "state_fips": "40",
        "county_fips": "40027",
        "population": 295528,
        "land_area_sq_mi": 538.908,
        "centroid": [
          35.269308,
          -97.450434
        ],
        "county_seat": null
      },
      {
        "county_name": "Coal County",
        "state_fips": "40",
        "county_fips": "40029",
        "population": 5266,
        "land_area_sq_mi": 516.772,
        "centroid": [
          34.548037,
          -96.278199
        ],
        "county_seat": null
      },
      {
        "county_name": "Comanche County",
        "state_fips": "40",
        "county_fips": "40031",
        "population": 121125,
        "land_area_sq_mi": 1069.322,
        "centroid": [
          34.633044,
          -98.419449
        ],
        "county_seat": null
      },
      {
        "county_name": "Cotton County",
        "state_fips": "40",
        "county_fips": "40033",
        "population": 5527,
        "land_area_sq_mi": 632.637,
        "centroid": [
          34.31257,
          -98.331491
        ],
        "county_seat": null
      },
      {
        "county_name": "Craig County",
        "state_fips": "40",
        "county_fips": "40035",
        "population": 14107,
        "land_area_sq_mi": 761.255,
        "centroid": [
          36.679216,
          -95.154588
        ],
        "county_seat": null
      },
      {
        "county_name": "Creek County",
        "state_fips": "40",
        "county_fips": "40037",
        "population": 71754,
        "land_area_sq_mi": 949.894,
        "centroid": [
          35.9754,
          -96.226043
        ],
        "county_seat": null
      },
      {
        "county_name": "Custer County",
        "state_fips": "40",
        "county_fips": "40039",
        "population": 28513,
        "land_area_sq_mi": 988.779,
        "centroid": [
          35.547694,
          -98.828737
        ],
        "county_seat": null
      },
      {
        "county_name": "Delaware County",
        "state_fips": "40",
        "county_fips": "40041",
        "population": 40397,
        "land_area_sq_mi": 737.754,
        "centroid": [
          36.468532,
          -94.793251
        ],
        "county_seat": null
      },
      {
        "county_name": "Dewey County",
        "state_fips": "40",
        "county_fips": "40043",
        "population": 4484,
        "land_area_sq_mi": 999.628,
        "centroid": [
          36.057055,
          -99.074156
        ],
        "county_seat": null
      },
      {
        "county_name": "Ellis County",
        "state_fips": "40",
        "county_fips": "40045",
        "population": 3749,
        "land_area_sq_mi": 1231.477,
        "centroid": [
          36.262513,
          -99.786963
        ],
        "county_seat": null
      },
      {
        "county_name": "Garfield County",
        "state_fips": "40",
        "county_fips": "40047",
        "population": 62846,
        "land_area_sq_mi": 1058.507,
        "centroid": [
          36.398481,
          -97.885455
        ],
        "county_seat": null
      },
      {
        "county_name": "Garvin County",
        "state_fips": "40",
        "county_fips": "40049",
        "population": 25656,
        "land_area_sq_mi": 802.146,
        "centroid": [
          34.737491,
          -97.28949
        ],
        "county_seat": null
      },
      {
        "county_name": "Grady County",
        "state_fips": "40",
        "county_fips": "40051",
        "population": 54795,
        "land_area_sq_mi": 1100.54,
        "centroid": [
          35.112409,
          -97.850428
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "40",
        "county_fips": "40053",
        "population": 4169,
        "land_area_sq_mi": 1000.74,
        "centroid": [
          36.761056,
          -97.779663
        ],
        "county_seat": null
      },
      {
        "county_name": "Greer County",
        "state_fips": "40",
        "county_fips": "40055",
        "population": 5491,
        "land_area_sq_mi": 639.285,
        "centroid": [
          34.912036,
          -99.464241
        ],
        "county_seat": null
      },
      {
        "county_name": "Harmon County",
        "state_fips": "40",
        "county_fips": "40057",
        "population": 2488,
        "land_area_sq_mi": 537.258,
        "centroid": [
          34.694548,
          -99.897391
        ],
        "county_seat": null
      },
      {
        "county_name": "Harper County",
        "state_fips": "40",
        "county_fips": "40059",
        "population": 3272,
        "land_area_sq_mi": 1038.584,
        "centroid": [
          36.768589,
          -99.761804
        ],
        "county_seat": null
      },
      {
        "county_name": "Haskell County",
        "state_fips": "40",
        "county_fips": "40061",
        "population": 11561,
        "land_area_sq_mi": 576.725,
        "centroid": [
          35.239002,
          -95.124795
        ],
        "county_seat": null
      },
      {
        "county_name": "Hughes County",
        "state_fips": "40",
        "county_fips": "40063",
        "population": 13367,
        "land_area_sq_mi": 804.473,
        "centroid": [
          35.079245,
          -96.326231
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "40",
        "county_fips": "40065",
        "population": 24785,
        "land_area_sq_mi": 802.653,
        "centroid": [
          34.657239,
          -99.331416
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "40",
        "county_fips": "40067",
        "population": 5337,
        "land_area_sq_mi": 758.956,
        "centroid": [
          34.132097,
          -97.871654
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnston County",
        "state_fips": "40",
        "county_fips": "40069",
        "population": 10272,
        "land_area_sq_mi": 643.05,
        "centroid": [
          34.262325,
          -96.650068
        ],
        "county_seat": null
      },
      {
        "county_name": "Kay County",
        "state_fips": "40",
        "county_fips": "40071",
        "population": 43700,
        "land_area_sq_mi": 919.61,
        "centroid": [
          36.744254,
          -97.125201
        ],
        "county_seat": null
      },
      {
        "county_name": "Kingfisher County",
        "state_fips": "40",
        "county_fips": "40073",
        "population": 15184,
        "land_area_sq_mi": 898.086,
        "centroid": [
          35.913869,
          -97.91096
        ],
        "county_seat": null
      },
      {
        "county_name": "Kiowa County",
        "state_fips": "40",
        "county_fips": "40075",
        "population": 8509,
        "land_area_sq_mi": 1015.078,
        "centroid": [
          34.936853,
          -99.017988
        ],
        "county_seat": null
      },
      {
        "county_name": "Latimer County",
        "state_fips": "40",
        "county_fips": "40077",
        "population": 9444,
        "land_area_sq_mi": 722.113,
        "centroid": [
          34.88202,
          -95.255214
        ],
        "county_seat": null
      },
      {
        "county_name": "Le Flore County",
        "state_fips": "40",
        "county_fips": "40079",
        "population": 48129,
        "land_area_sq_mi": 1589.416,
        "centroid": [
          35.065249,
          -94.639064
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "40",
        "county_fips": "40081",
        "population": 33458,
        "land_area_sq_mi": 952.372,
        "centroid": [
          35.656322,
          -96.882274
        ],
        "county_seat": null
      },
      {
        "county_name": "Logan County",
        "state_fips": "40",
        "county_fips": "40083",
        "population": 49555,
        "land_area_sq_mi": 743.736,
        "centroid": [
          35.822271,
          -97.442909
        ],
        "county_seat": null
      },
      {
        "county_name": "Love County",
        "state_fips": "40",
        "county_fips": "40085",
        "population": 10146,
        "land_area_sq_mi": 513.914,
        "centroid": [
          33.922696,
          -97.170128
        ],
        "county_seat": null
      },
      {
        "county_name": "McClain County",
        "state_fips": "40",
        "county_fips": "40087",
        "population": 41662,
        "land_area_sq_mi": 570.72,
        "centroid": [
          35.106328,
          -97.527577
        ],
        "county_seat": null
      },
      {
        "county_name": "McCurtain County",
        "state_fips": "40",
        "county_fips": "40089",
        "population": 30814,
        "land_area_sq_mi": 1850.782,
        "centroid": [
          33.999674,
          -94.814678
        ],
        "county_seat": null
      },
      {
        "county_name": "McIntosh County",
        "state_fips": "40",
        "county_fips": "40091",
        "population": 18941,
        "land_area_sq_mi": 618.29,
        "centroid": [
          35.385902,
          -95.581367
        ],
        "county_seat": null
      },
      {
        "county_name": "Major County",
        "state_fips": "40",
        "county_fips": "40093",
        "population": 7782,
        "land_area_sq_mi": 955.0,
        "centroid": [
          36.298864,
          -98.432369
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "40",
        "county_fips": "40095",
        "population": 15312,
        "land_area_sq_mi": 371.49,
        "centroid": [
          34.01809,
          -96.749333
        ],
        "county_seat": null
      },
      {
        "county_name": "Mayes County",
        "state_fips": "40",
        "county_fips": "40097",
        "population": 39046,
        "land_area_sq_mi": 655.326,
        "centroid": [
          36.292233,
          -95.243222
        ],
        "county_seat": null
      },
      {
        "county_name": "Murray County",
        "state_fips": "40",
        "county_fips": "40099",
        "population": 13904,
        "land_area_sq_mi": 416.375,
        "centroid": [
          34.507083,
          -97.027691
        ],
        "county_seat": null
      },
      {
        "county_name": "Muskogee County",
        "state_fips": "40",
        "county_fips": "40101",
        "population": 66339,
        "land_area_sq_mi": 810.64,
        "centroid": [
          35.71185,
          -95.366561
        ],
        "county_seat": null
      },
      {
        "county_name": "Noble County",
        "state_fips": "40",
        "county_fips": "40103",
        "population": 10924,
        "land_area_sq_mi": 731.712,
        "centroid": [
          36.324096,
          -97.233088
        ],
        "county_seat": null
      },
      {
        "county_name": "Nowata County",
        "state_fips": "40",
        "county_fips": "40105",
        "population": 9320,
        "land_area_sq_mi": 565.817,
        "centroid": [
          36.774995,
          -95.635237
        ],
        "county_seat": null
      },
      {
        "county_name": "Okfuskee County",
        "state_fips": "40",
        "county_fips": "40107",
        "population": 11310,
        "land_area_sq_mi": 618.458,
        "centroid": [
          35.451094,
          -96.337952
        ],
        "county_seat": null
      },
      {
        "county_name": "Oklahoma County",
        "state_fips": "40",
        "county_fips": "40109",
        "population": 796292,
        "land_area_sq_mi": 708.9,
        "centroid": [
          35.52553,
          -97.512375
        ],
        "county_seat": null
      },
      {
        "county_name": "Okmulgee County",
        "state_fips": "40",
        "county_fips": "40111",
        "population": 36706,
        "land_area_sq_mi": 697.443,
        "centroid": [
          35.617922,
          -95.969216
        ],
        "county_seat": null
      },
      {
        "county_name": "Osage County",
        "state_fips": "40",
        "county_fips": "40113",
        "population": 45818,
        "land_area_sq_mi": 2246.682,
        "centroid": [
          36.415208,
          -96.228583
        ],
        "county_seat": null
      },
      {
        "county_name": "Ottawa County",
        "state_fips": "40",
        "county_fips": "40115",
        "population": 30285,
        "land_area_sq_mi": 470.817,
        "centroid": [
          36.857439,
          -94.834841
        ],
        "county_seat": null
      },
      {
        "county_name": "Pawnee County",
        "state_fips": "40",
        "county_fips": "40117",
        "population": 15553,
        "land_area_sq_mi": 568.353,
        "centroid": [
          36.270375,
          -96.539216
        ],
        "county_seat": null
      },
      {
        "county_name": "Payne County",
        "state_fips": "40",
        "county_fips": "40119",
        "population": 81646,
        "land_area_sq_mi": 684.901,
        "centroid": [
          36.0913,
          -97.007049
        ],
        "county_seat": null
      },
      {
        "county_name": "Pittsburg County",
        "state_fips": "40",
        "county_fips": "40121",
        "population": 43773,
        "land_area_sq_mi": 1305.512,
        "centroid": [
          34.956346,
          -95.721263
        ],
        "county_seat": null
      },
      {
        "county_name": "Pontotoc County",
        "state_fips": "40",
        "county_fips": "40123",
        "population": 38065,
        "land_area_sq_mi": 720.353,
        "centroid": [
          34.774213,
          -96.67319
        ],
        "county_seat": null
      },
      {
        "county_name": "Pottawatomie County",
        "state_fips": "40",
        "county_fips": "40125",
        "population": 72454,
        "land_area_sq_mi": 787.793,
        "centroid": [
          35.321377,
          -96.952883
        ],
        "county_seat": null
      },
      {
        "county_name": "Pushmataha County",
        "state_fips": "40",
        "county_fips": "40127",
        "population": 10812,
        "land_area_sq_mi": 1395.54,
        "centroid": [
          34.327826,
          -95.482036
        ],
        "county_seat": null
      },
      {
        "county_name": "Roger Mills County",
        "state_fips": "40",
        "county_fips": "40129",
        "population": 3442,
        "land_area_sq_mi": 1141.135,
        "centroid": [
          35.628485,
          -99.659405
        ],
        "county_seat": null
      },
      {
        "county_name": "Rogers County",
        "state_fips": "40",
        "county_fips": "40131",
        "population": 95240,
        "land_area_sq_mi": 675.747,
        "centroid": [
          36.31533,
          -95.650597
        ],
        "county_seat": null
      },
      {
        "county_name": "Seminole County",
        "state_fips": "40",
        "county_fips": "40133",
        "population": 23556,
        "land_area_sq_mi": 632.819,
        "centroid": [
          35.186227,
          -96.631163
        ],
        "county_seat": null
      },
      {
        "county_name": "Sequoyah County",
        "state_fips": "40",
        "county_fips": "40135",
        "population": 39281,
        "land_area_sq_mi": 673.577,
        "centroid": [
          35.466206,
          -94.729702
        ],
        "county_seat": null
      },
      {
        "county_name": "Stephens County",
        "state_fips": "40",
        "county_fips": "40137",
        "population": 42848,
        "land_area_sq_mi": 870.212,
        "centroid": [
          34.518536,
          -97.946619
        ],
        "county_seat": null
      },
      {
        "county_name": "Texas County",
        "state_fips": "40",
        "county_fips": "40139",
        "population": 21384,
        "land_area_sq_mi": 2041.293,
        "centroid": [
          36.712185,
          -101.448408
        ],
        "county_seat": null
      },
      {
        "county_name": "Tillman County",
        "state_fips": "40",
        "county_fips": "40141",
        "population": 6968,
        "land_area_sq_mi": 871.134,
        "centroid": [
          34.382478,
          -98.971119
        ],
        "county_seat": null
      },
      {
        "county_name": "Tulsa County",
        "state_fips": "40",
        "county_fips": "40143",
        "population": 669279,
        "land_area_sq_mi": 570.242,
        "centroid": [
          36.1027,
          -95.91151
        ],
        "county_seat": null
      },
      {
        "county_name": "Wagoner County",
        "state_fips": "40",
        "county_fips": "40145",
        "population": 80981,
        "land_area_sq_mi": 561.916,
        "centroid": [
          36.015963,
          -95.627565
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "40",
        "county_fips": "40147",
        "population": 52455,
        "land_area_sq_mi": 415.524,
        "centroid": [
          36.728457,
          -95.937432
        ],
        "county_seat": null
      },
      {
        "county_name": "Washita County",
        "state_fips": "40",
        "county_fips": "40149",
        "population": 10924,
        "land_area_sq_mi": 1003.089,
        "centroid": [
          35.314336,
          -99.05353
        ],
        "county_seat": null
      },
      {
        "county_name": "Woods County",
        "state_fips": "40",
        "county_fips": "40151",
        "population": 8624,
        "land_area_sq_mi": 1286.482,
        "centroid": [
          36.767497,
          -98.708062
        ],
        "county_seat": null
      },
      {
        "county_name": "Woodward County",
        "state_fips": "40",
        "county_fips": "40153",
        "population": 20470,
        "land_area_sq_mi": 1242.786,
        "centroid": [
          36.423748,
          -99.383574
        ],
        "county_seat": null
      }
    ]
