# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adams County",
        "state_fips": "08",
        "county_fips": "08001",
        "population": 519572,
        "land_area_sq_mi": 1166.792,
        "centroid": [
          39.876949,
          -104.920943
        ],
        "county_seat": null
      },
      {
        "county_name": "Alamosa County",
        "state_fips": "08",
        "county_fips": "08003",
        "population": 16376,
        "land_area_sq_mi": 722.645,
        "centroid": [
          37.481888,
          -105.877629
        ],
        "county_seat": null
      },
      {
        "county_name": "Arapahoe County",
        "state_fips": "08",
        "county_fips": "08005",
        "population": 655070,
        "land_area_sq_mi": 797.887,
        "centroid": [
          39.646582,
          -104.838574
        ],
        "county_seat": null
      },
      {
        "county_name": "Archuleta County",
        "state_fips": "08",
        "county_fips": "08007",
        "population": 13359,
        "land_area_sq_mi": 1350.088,
        "centroid": [
          37.240274,
          -107.089808
        ],
        "county_seat": null
      },
      {
        "county_name": "Baca County",
        "state_fips": "08",
        "county_fips": "08009",
        "population": 3506,
        "land_area_sq_mi": 2554.993,
        "centroid": [
          37.368105,
          -102.53204
        ],
        "county_seat": null
      },
      {
        "county_name": "Bent County",
        "state_fips": "08",
        "county_fips": "08011",
        "population": 5650,
        "land_area_sq_mi": 1512.847,
        "centroid": [
          38.072919,
          -103.166006
        ],
        "county_seat": null
      },
      {
        "county_name": "Boulder County",
        "state_fips": "08",
        "county_fips": "08013",
        "population": 330758,
        "land_area_sq_mi": 726.408,
        "centroid": [
          40.062992,
          -105.180215
        ],
        "county_seat": null
      },
      {
        "county_name": "Broomfield County",
        "state_fips": "08",
        "county_fips": "08014",
        "population": 74112,
        "land_area_sq_mi": 32.968,
        "centroid": [
          39.939871,
          -105.058131
        ],
        "county_seat": null
      },
      {
        "county_name": "Chaffee County",
        "state_fips": "08",
        "county_fips": "08015",
        "population": 19476,
        "land_area_sq_mi": 1013.408,
        "centroid": [
          38.676811,
          -106.085131
        ],
        "county_seat": null
      },
      {
        "county_name": "Cheyenne County",
        "state_fips": "08",
        "county_fips": "08017",
        "population": 1748,
        "land_area_sq_mi": 1778.276,
        "centroid": [
          38.817655,
          -102.470052
        ],
        "county_seat": null
      },
      {
        "county_name": "Clear Creek County",
        "state_fips": "08",
        "county_fips": "08019",
        "population": 9397,
        "land_area_sq_mi": 395.073,
        "centroid": [
          39.713458,
          -105.532527
        ],
        "county_seat": null
      },
      {
        "county_name": "Conejos County",
        "state_fips": "08",
        "county_fips": "08021",
        "population": 7461,
        "land_area_sq_mi": 1287.428,
        "centroid": [
          37.199613,
          -105.987323
        ],
        "county_seat": null
      },
      {
        "county_name": "Costilla County",
        "state_fips": "08",
        "county_fips": "08023",
        "population": 3499,
        "land_area_sq_mi": 1227.593,
        "centroid": [
          37.29223,
          -105.444296
        ],
        "county_seat": null
      },
      {
        "county_name": "Crowley County",
        "state_fips": "08",
        "county_fips": "08025",
        "population": 5922,
        "land_area_sq_mi": 787.428,
        "centroid": [
          38.193783,
          -103.856387
        ],
        "county_seat": null
      },
      {
        "county_name": "Custer County",
        "state_fips": "08",
        "county_fips": "08027",
        "population": 4704,
        "land_area_sq_mi": 738.626,
        "centroid": [
          38.133198,
          -105.382527
        ],
        "county_seat": null
      },
      {
        "county_name": "Delta County",
        "state_fips": "08",
        "county_fips": "08029",
        "population": 31196,
        "land_area_sq_mi": 1142.125,
        "centroid": [
          38.798198,
          -107.913769
        ],
        "county_seat": null
      },
      {
        "county_name": "Denver County",
        "state_fips": "08",
        "county_fips": "08031",
        "population": 715522,
        "land_area_sq_mi": 153.074,
        "centroid": [
          39.72486,
          -104.950033
        ],
        "county_seat": null
      },
      {
        "county_name": "Dolores County",
        "state_fips": "08",
        "county_fips": "08033",
        "population": 2326,
        "land_area_sq_mi": 1067.17,
        "centroid": [
          37.746934,
          -108.758724
        ],
        "county_seat": null
      },
      {
        "county_name": "Douglas County",
        "state_fips": "08",
        "county_fips": "08035",
        "population": 357978,
        "land_area_sq_mi": 840.888,
        "centroid": [
          39.482023,
          -104.87357
        ],
        "county_seat": null
      },
      {
        "county_name": "Eagle County",
        "state_fips": "08",
        "county_fips": "08037",
        "population": 55731,
        "land_area_sq_mi": 1684.47,
        "centroid": [
          39.600516,
          -106.733421
        ],
        "county_seat": null
      },
      {
        "county_name": "Elbert County",
        "state_fips": "08",
        "county_fips": "08039",
        "population": 26062,
        "land_area_sq_mi": 1850.086,
        "centroid": [
          39.388552,
          -104.52311
        ],
        "county_seat": null
      },
      {
        "county_name": "El Paso County",
        "state_fips": "08",
        "county_fips": "08041",
        "population": 730395,
        "land_area_sq_mi": 2126.416,
        "centroid": [
          38.877314,
          -104.75212
        ],
        "county_seat": null
      },
      {
        "county_name": "Fremont County",
        "state_fips": "08",
        "county_fips": "08043",
        "population": 48939,
        "land_area_sq_mi": 1533.835,
        "centroid": [
          38.426941,
          -105.214303
        ],
        "county_seat": null
      },
      {
        "county_name": "Garfield County",
        "state_fips": "08",
        "county_fips": "08045",
        "population": 61685,
        "land_area_sq_mi": 2947.425,
        "centroid": [
          39.507103,
          -107.549019
        ],
        "county_seat": null
      },
      {
        "county_name": "Gilpin County",
        "state_fips": "08",
        "county_fips": "08047",
        "population": 5808,
        "land_area_sq_mi": 150.023,
        "centroid": [
          39.856062,
          -105.483217
        ],
        "county_seat": null
      },
      {
        "county_name": "Grand County",
        "state_fips": "08",
        "county_fips": "08049",
        "population": 15717,
        "land_area_sq_mi": 1846.447,
        "centroid": [
          40.051143,
          -105.978501
        ],
        "county_seat": null
      },
      {
        "county_name": "Gunnison County",
        "state_fips": "08",
        "county_fips": "08051",
        "population": 16918,
        "land_area_sq_mi": 3239.14,
        "centroid": [
          38.660002,
          -106.944384
        ],
        "county_seat": null
      },
      {
        "county_name": "Hinsdale County",
        "state_fips": "08",
        "county_fips": "08053",
        "population": 788,
        "land_area_sq_mi": 1117.231,
        "centroid": [
          38.002552,
          -107.29875
        ],
        "county_seat": null
      },
      {
        "county_name": "Huerfano County",
        "state_fips": "08",
        "county_fips": "08055",
        "population": 6820,
        "land_area_sq_mi": 1591.033,
        "centroid": [
          37.612538,
          -104.887584
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "08",
        "county_fips": "08057",
        "population": 1379,
        "land_area_sq_mi": 1613.726,
        "centroid": [
          40.690192,
          -106.295485
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "08",
        "county_fips": "08059",
        "population": 582910,
        "land_area_sq_mi": 764.39,
        "centroid": [
          39.72369,
          -105.130309
        ],
        "county_seat": null
      },
      {
        "county_name": "Kiowa County",
        "state_fips": "08",
        "county_fips": "08061",
        "population": 1446,
        "land_area_sq_mi": 1767.809,
        "centroid": [
          38.470085,
          -102.700966
        ],
        "county_seat": null
      },
      {
        "county_name": "Kit Carson County",
        "state_fips": "08",
        "county_fips": "08063",
        "population": 7087,
        "land_area_sq_mi": 2160.822,
        "centroid": [
          39.310418,
          -102.462031
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake County",
        "state_fips": "08",
        "county_fips": "08065",
        "population": 7436,
        "land_area_sq_mi": 376.919,
        "centroid": [
          39.244814,
          -106.30747
        ],
        "county_seat": null
      },
      {
        "county_name": "La Plata County",
        "state_fips": "08",
        "county_fips": "08067",
        "population": 55638,
        "land_area_sq_mi": 1689.682,
        "centroid": [
          37.266021,
          -107.803947
        ],
        "county_seat": null
      },
      {
        "county_name": "Larimer County",
        "state_fips": "08",
        "county_fips": "08069",
        "population": 359066,
        "land_area_sq_mi": 2595.746,
        "centroid": [
          40.504402,
          -105.089155
        ],
        "county_seat": null
      },
      {
        "county_name": "Las Animas County",
        "state_fips": "08",
        "county_fips": "08071",
        "population": 14555,
        "land_area_sq_mi": 4772.938,
        "centroid": [
          37.192053,
          -104.501324
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "08",
        "county_fips": "08073",
        "population": 5675,
        "land_area_sq_mi": 2577.73,
        "centroid": [
          39.180049,
          -103.614219
        ],
        "county_seat": null
      },
      {
        "county_name": "Logan County",
        "state_fips": "08",
        "county_fips": "08075",
        "population": 21528,
        "land_area_sq_mi": 1838.599,
        "centroid": [
          40.64034,
          -103.185977
        ],
        "county_seat": null
      },
      {
        "county_name": "Mesa County",
        "state_fips": "08",
        "county_fips": "08077",
        "population": 155703,
        "land_area_sq_mi": 3328.721,
        "centroid": [
          39.092942,
          -108.546673
        ],
        "county_seat": null
      },
      {
        "county_name": "Mineral County",
        "state_fips": "08",
        "county_fips": "08079",
        "population": 865,
        "land_area_sq_mi": 875.76,
        "centroid": [
          37.779142,
          -106.942063
        ],
        "county_seat": null
      },
      {
        "county_name": "Moffat County",
        "state_fips": "08",
        "county_fips": "08081",
        "population": 13292,
        "land_area_sq_mi": 4743.244,
        "centroid": [
          40.51606,
          -107.613977
        ],
        "county_seat": null
      },
      {
        "county_name": "Montezuma County",
        "state_fips": "08",
        "county_fips": "08083",
        "population": 25849,
        "land_area_sq_mi": 2029.349,
        "centroid": [
          37.371913,
          -108.554458
        ],
        "county_seat": null
      },
      {
        "county_name": "Montrose County",
        "state_fips": "08",
        "county_fips": "08085",
        "population": 42679,
        "land_area_sq_mi": 2240.946,
        "centroid": [
          38.481301,
          -107.922349
        ],
        "county_seat": null
      },
      {
        "county_name": "Morgan County",
        "state_fips": "08",
        "county_fips": "08087",
        "population": 29111,
        "land_area_sq_mi": 1280.485,
        "centroid": [
          40.254229,
          -103.789071
        ],
        "county_seat": null
      },
      {
        "county_name": "Otero County",
        "state_fips": "08",
        "county_fips": "08089",
        "population": 18690,
        "land_area_sq_mi": 1261.946,
        "centroid": [
          38.023236,
          -103.655776
        ],
        "county_seat": null
      },
      {
        "county_name": "Ouray County",
        "state_fips": "08",
        "county_fips": "08091",
        "population": 4874,
        "land_area_sq_mi": 540.671,
        "centroid": [
          38.146044,
          -107.751894
        ],
        "county_seat": null
      },
      {
        "county_name": "Park County",
        "state_fips": "08",
        "county_fips": "08093",
        "population": 17390,
        "land_area_sq_mi": 2193.51,
        "centroid": [
          39.305737,
          -105.625362
        ],
        "county_seat": null
      },
      {
        "county_name": "Phillips County",
        "state_fips": "08",
        "county_fips": "08095",
        "population": 4530,
        "land_area_sq_mi": 687.928,
        "centroid": [
          40.599356,
          -102.385877
        ],
        "county_seat": null
      },
      {
        "county_name": "Pitkin County",
        "state_fips": "08",
        "county_fips": "08097",
        "population": 17358,
        "land_area_sq_mi": 970.701,
        "centroid": [
          39.231757,
          -106.908716
        ],
        "county_seat": null
      },
      {
        "county_name": "Prowers County",
        "state_fips": "08",
        "county_fips": "08099",
        "population": 11999,
        "land_area_sq_mi": 1638.407,
        "centroid": [
          38.083029,
          -102.548624
        ],
        "county_seat": null
      },
      {
        "county_name": "Pueblo County",
        "state_fips": "08",
        "county_fips": "08101",
        "population": 168162,
        "land_area_sq_mi": 2386.591,
        "centroid": [
          38.265773,
          -104.646976
        ],
        "county_seat": null
      },
      {
        "county_name": "Rio Blanco County",
        "state_fips": "08",
        "county_fips": "08103",
        "population": 6529,
        "land_area_sq_mi": 3220.971,
        "centroid": [
          40.05108,
          -108.268744
        ],
        "county_seat": null
      },
      {
        "county_name": "Rio Grande County",
        "state_fips": "08",
        "county_fips": "08105",
        "population": 11539,
        "land_area_sq_mi": 911.956,
        "centroid": [
          37.61185,
          -106.242067
        ],
        "county_seat": null
      },
      {
        "county_name": "Routt County",
        "state_fips": "08",
        "county_fips": "08107",
        "population": 24829,
        "land_area_sq_mi": 2362.02,
        "centroid": [
          40.455504,
          -106.89741
        ],
        "county_seat": null
      },
      {
        "county_name": "Saguache County",
        "state_fips": "08",
        "county_fips": "08109",
        "population": 6368,
        "land_area_sq_mi": 3168.566,
        "centroid": [
          37.925349,
          -106.006105
        ],
        "county_seat": null
      },
      {
        "county_name": "San Juan County",
        "state_fips": "08",
        "county_fips": "08111",
        "population": 705,
        "land_area_sq_mi": 387.516,
        "centroid": [
          37.801877,
          -107.673598
        ],
        "county_seat": null
      },
      {
        "county_name": "San Miguel County",
        "state_fips": "08",
        "county_fips": "08113",
        "population": 8072,
        "land_area_sq_mi": 1286.725,
        "centroid": [
          37.971818,
          -107.958108
        ],
        "county_seat": null
      },
      {
        "county_name": "Sedgwick County",
        "state_fips": "08",
        "county_fips": "08115",
        "population": 2404,
        "land_area_sq_mi": 548.041,
        "centroid": [
          40.962161,
          -102.325673
        ],
        "county_seat": null
      },
      {
        "county_name": "Summit County",
        "state_fips": "08",
        "county_fips": "08117",
        "population": 31055,
        "land_area_sq_mi": 608.328,
        "centroid": [
          39.572383,
          -106.055673
        ],
        "county_seat": null
      },
      {
        "county_name": "Teller County",
        "state_fips": "08",
        "county_fips": "08119",
        "population": 24710,
        "land_area_sq_mi": 557.141,
        "centroid": [
          38.944782,
          -105.139899
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "08",
        "county_fips": "08121",
        "population": 4817,
        "land_area_sq_mi": 2518.084,
        "centroid": [
          40.098312,
          -103.157119
        ],
        "county_seat": null
      },
      {
        "county_name": "Weld County",
        "state_fips": "08",
        "county_fips": "08123",
        "population": 328981,
        "land_area_sq_mi": 3984.958,
        "centroid": [
          40.322426,
          -104.807009
        ],
        "county_seat": null
      },
      {
        "county_name": "Yuma County",
        "state_fips": "08",
        "county_fips": "08125",
        "population": 9988,
        "land_area_sq_mi": 2364.399,
        "centroid": [
          40.065848,
          -102.480825
        ],
        "county_seat": null
      }
    ]
