# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adjuntas County",
        "state_fips": "72",
        "county_fips": "72001",
        "population": 18020,
        "land_area_sq_mi": 66.683,
        "centroid": [
          18.173646,
          -66.740925
        ],
        "county_seat": null
      },
      {
        "county_name": "Aguada County",
        "state_fips": "72",
        "county_fips": "72003",
        "population": 38136,
        "land_area_sq_mi": 30.859,
        "centroid": [
          18.362557,
          -67.176449
        ],
        "county_seat": null
      },
      {
        "county_name": "Aguadilla County",
        "state_fips": "72",
        "county_fips": "72005",
        "population": 55101,
        "land_area_sq_mi": 36.542,
        "centroid": [
          18.459888,
          -67.12633
        ],
        "county_seat": null
      },
      {
        "county_name": "Aguas Buenas County",
        "state_fips": "72",
        "county_fips": "72007",
        "population": 24223,
        "land_area_sq_mi": 30.085,
        "centroid": [
          18.24874,
          -66.122947
        ],
        "county_seat": null
      },
      {
        "county_name": "Aibonito County",
        "state_fips": "72",
        "county_fips": "72009",
        "population": 24637,
        "land_area_sq_mi": 31.312,
        "centroid": [
          18.137305,
          -66.268687
        ],
        "county_seat": null
      },
      {
        "county_name": "A\u00f1asco County",
        "state_fips": "72",
        "county_fips": "72011",
        "population": 25596,
        "land_area_sq_mi": 39.293,
        "centroid": [
          18.290392,
          -67.139988
        ],
        "county_seat": null
      },
      {
        "county_name": "Arecibo County",
        "state_fips": "72",
        "county_fips": "72013",
        "population": 87754,
        "land_area_sq_mi": 126.04,
        "centroid": [
          18.439048,
          -66.69096
        ],
        "county_seat": null
      },
      {
        "county_name": "Arroyo County",
        "state_fips": "72",
        "county_fips": "72015",
        "population": 15843,
        "land_area_sq_mi": 15.009,
        "centroid": [
          17.984834,
          -66.054877
        ],
        "county_seat": null
      },
      {
        "county_name": "Barceloneta County",
        "state_fips": "72",
        "county_fips": "72017",
        "population": 22657,
        "land_area_sq_mi": 18.684,
        "centroid": [
          18.444507,
          -66.5587
        ],
        "county_seat": null
      },
      {
        "county_name": "Barranquitas County",
        "state_fips": "72",
        "county_fips": "72019",
        "population": 28983,
        "land_area_sq_mi": 34.253,
        "centroid": [
          18.203009,
          -66.311406
        ],
        "county_seat": null
      },
      {
        "county_name": "Bayam\u00f3n County",
        "state_fips": "72",
        "county_fips": "72021",
        "population": 185187,
        "land_area_sq_mi": 44.439,
        "centroid": [
          18.37294,
          -66.168187
        ],
        "county_seat": null
      },
      {
        "county_name": "Cabo Rojo County",
        "state_fips": "72",
        "county_fips": "72023",
        "population": 47158,
        "land_area_sq_mi": 70.366,
        "centroid": [
          18.070386,
          -67.156738
        ],
        "county_seat": null
      },
      {
        "county_name": "Caguas County",
        "state_fips": "72",
        "county_fips": "72025",
        "population": 127244,
        "land_area_sq_mi": 58.604,
        "centroid": [
          18.226891,
          -66.045972
        ],
        "county_seat": null
      },
      {
        "county_name": "Camuy County",
        "state_fips": "72",
        "county_fips": "72027",
        "population": 32827,
        "land_area_sq_mi": 46.432,
        "centroid": [
          18.444506,
          -66.863259
        ],
        "county_seat": null
      },
      {
        "county_name": "Can\u00f3vanas County",
        "state_fips": "72",
        "county_fips": "72029",
        "population": 42337,
        "land_area_sq_mi": 32.869,
        "centroid": [
          18.359601,
          -65.895249
        ],
        "county_seat": null
      },
      {
        "county_name": "Carolina County",
        "state_fips": "72",
        "county_fips": "72031",
        "population": 154815,
        "land_area_sq_mi": 45.378,
        "centroid": [
          18.392727,
          -65.971732
        ],
        "county_seat": null
      },
      {
        "county_name": "Cata\u00f1o County",
        "state_fips": "72",
        "county_fips": "72033",
        "population": 23155,
        "land_area_sq_mi": 4.832,
        "centroid": [
          18.436657,
          -66.141417
        ],
        "county_seat": null
      },
      {
        "county_name": "Cayey County",
        "state_fips": "72",
        "county_fips": "72035",
        "population": 41652,
        "land_area_sq_mi": 51.935,
        "centroid": [
          18.119389,
          -66.150454
        ],
        "county_seat": null
      },
      {
        "county_name": "Ceiba County",
        "state_fips": "72",
        "county_fips": "72037",
        "population": 11307,
        "land_area_sq_mi": 29.036,
        "centroid": [
          18.262878,
          -65.656285
        ],
        "county_seat": null
      },
      {
        "county_name": "Ciales County",
        "state_fips": "72",
        "county_fips": "72039",
        "population": 16984,
        "land_area_sq_mi": 66.529,
        "centroid": [
          18.314892,
          -66.493664
        ],
        "county_seat": null
      },
      {
        "county_name": "Cidra County",
        "state_fips": "72",
        "county_fips": "72041",
        "population": 39970,
        "land_area_sq_mi": 36.023,
        "centroid": [
          18.171979,
          -66.151298
        ],
        "county_seat": null
      },
      {
        "county_name": "Coamo County",
        "state_fips": "72",
        "county_fips": "72043",
        "population": 34668,
        "land_area_sq_mi": 78.013,
        "centroid": [
          18.078888,
          -66.361654
        ],
        "county_seat": null
      },
      {
        "county_name": "Comer\u00edo County",
        "state_fips": "72",
        "county_fips": "72045",
        "population": 18883,
        "land_area_sq_mi": 28.401,
        "centroid": [
          18.226917,
          -66.223805
        ],
        "county_seat": null
      },
      {
        "county_name": "Corozal County",
        "state_fips": "72",
        "county_fips": "72047",
        "population": 34571,
        "land_area_sq_mi": 42.565,
        "centroid": [
          18.31652,
          -66.322897
        ],
        "county_seat": null
      },
      {
        "county_name": "Culebra County",
        "state_fips": "72",
        "county_fips": "72049",
        "population": 1792,
        "land_area_sq_mi": 11.647,
        "centroid": [
          18.311911,
          -65.301885
        ],
        "county_seat": null
      },
      {
        "county_name": "Dorado County",
        "state_fips": "72",
        "county_fips": "72051",
        "population": 35879,
        "land_area_sq_mi": 23.116,
        "centroid": [
          18.440335,
          -66.284058
        ],
        "county_seat": null
      },
      {
        "county_name": "Fajardo County",
        "state_fips": "72",
        "county_fips": "72053",
        "population": 32124,
        "land_area_sq_mi": 29.907,
        "centroid": [
          18.327234,
          -65.656969
        ],
        "county_seat": null
      },
      {
        "county_name": "Florida County",
        "state_fips": "72",
        "county_fips": "72054",
        "population": 11692,
        "land_area_sq_mi": 15.224,
        "centroid": [
          18.368416,
          -66.563073
        ],
        "county_seat": null
      },
      {
        "county_name": "Gu\u00e1nica County",
        "state_fips": "72",
        "county_fips": "72055",
        "population": 13787,
        "land_area_sq_mi": 37.075,
        "centroid": [
          17.985564,
          -66.912035
        ],
        "county_seat": null
      },
      {
        "county_name": "Guayama County",
        "state_fips": "72",
        "county_fips": "72057",
        "population": 36614,
        "land_area_sq_mi": 65.038,
        "centroid": [
          17.981079,
          -66.120144
        ],
        "county_seat": null
      },
      {
        "county_name": "Guayanilla County",
        "state_fips": "72",
        "county_fips": "72059",
        "population": 17784,
        "land_area_sq_mi": 42.248,
        "centroid": [
          18.03273,
          -66.793032
        ],
        "county_seat": null
      },
      {
        "county_name": "Guaynabo County",
        "state_fips": "72",
        "county_fips": "72061",
        "population": 89780,
        "land_area_sq_mi": 27.585,
        "centroid": [
          18.366345,
          -66.113295
        ],
        "county_seat": null
      },
      {
        "county_name": "Gurabo County",
        "state_fips": "72",
        "county_fips": "72063",
        "population": 40622,
        "land_area_sq_mi": 27.885,
        "centroid": [
          18.253807,
          -65.979538
        ],
        "county_seat": null
      },
      {
        "county_name": "Hatillo County",
        "state_fips": "72",
        "county_fips": "72065",
        "population": 38486,
        "land_area_sq_mi": 41.744,
        "centroid": [
          18.440804,
          -66.797657
        ],
        "county_seat": null
      },
      {
        "county_name": "Hormigueros County",
        "state_fips": "72",
        "county_fips": "72067",
        "population": 15654,
        "land_area_sq_mi": 11.346,
        "centroid": [
          18.141179,
          -67.120847
        ],
        "county_seat": null
      },
      {
        "county_name": "Humacao County",
        "state_fips": "72",
        "county_fips": "72069",
        "population": 50896,
        "land_area_sq_mi": 44.719,
        "centroid": [
          18.141972,
          -65.816921
        ],
        "county_seat": null
      },
      {
        "county_name": "Isabela County",
        "state_fips": "72",
        "county_fips": "72071",
        "population": 42943,
        "land_area_sq_mi": 55.311,
        "centroid": [
          18.473708,
          -67.018163
        ],
        "county_seat": null
      },
      {
        "county_name": "Jayuya County",
        "state_fips": "72",
        "county_fips": "72073",
        "population": 14779,
        "land_area_sq_mi": 44.53,
        "centroid": [
          18.21663,
          -66.593669
        ],
        "county_seat": null
      },
      {
        "county_name": "Juana D\u00edaz County",
        "state_fips": "72",
        "county_fips": "72075",
        "population": 46538,
        "land_area_sq_mi": 60.355,
        "centroid": [
          18.040776,
          -66.503885
        ],
        "county_seat": null
      },
      {
        "county_name": "Juncos County",
        "state_fips": "72",
        "county_fips": "72077",
        "population": 37012,
        "land_area_sq_mi": 26.49,
        "centroid": [
          18.223898,
          -65.913785
        ],
        "county_seat": null
      },
      {
        "county_name": "Lajas County",
        "state_fips": "72",
        "county_fips": "72079",
        "population": 23334,
        "land_area_sq_mi": 59.961,
        "centroid": [
          18.032554,
          -67.046992
        ],
        "county_seat": null
      },
      {
        "county_name": "Lares County",
        "state_fips": "72",
        "county_fips": "72081",
        "population": 28105,
        "land_area_sq_mi": 61.455,
        "centroid": [
          18.293906,
          -66.870739
        ],
        "county_seat": null
      },
      {
        "county_name": "Las Mar\u00edas County",
        "state_fips": "72",
        "county_fips": "72083",
        "population": 8874,
        "land_area_sq_mi": 46.36,
        "centroid": [
          18.242125,
          -66.993323
        ],
        "county_seat": null
      },
      {
        "county_name": "Las Piedras County",
        "state_fips": "72",
        "county_fips": "72085",
        "population": 35180,
        "land_area_sq_mi": 33.88,
        "centroid": [
          18.180422,
          -65.873796
        ],
        "county_seat": null
      },
      {
        "county_name": "Lo\u00edza County",
        "state_fips": "72",
        "county_fips": "72087",
        "population": 23693,
        "land_area_sq_mi": 19.374,
        "centroid": [
          18.418901,
          -65.869088
        ],
        "county_seat": null
      },
      {
        "county_name": "Luquillo County",
        "state_fips": "72",
        "county_fips": "72089",
        "population": 17781,
        "land_area_sq_mi": 25.811,
        "centroid": [
          18.361491,
          -65.723304
        ],
        "county_seat": null
      },
      {
        "county_name": "Manat\u00ed County",
        "state_fips": "72",
        "county_fips": "72091",
        "population": 39492,
        "land_area_sq_mi": 45.14,
        "centroid": [
          18.427989,
          -66.482736
        ],
        "county_seat": null
      },
      {
        "county_name": "Maricao County",
        "state_fips": "72",
        "county_fips": "72093",
        "population": 4755,
        "land_area_sq_mi": 36.623,
        "centroid": [
          18.176418,
          -66.955125
        ],
        "county_seat": null
      },
      {
        "county_name": "Maunabo County",
        "state_fips": "72",
        "county_fips": "72095",
        "population": 10589,
        "land_area_sq_mi": 21.165,
        "centroid": [
          18.010392,
          -65.90469
        ],
        "county_seat": null
      },
      {
        "county_name": "Mayag\u00fcez County",
        "state_fips": "72",
        "county_fips": "72097",
        "population": 73077,
        "land_area_sq_mi": 77.589,
        "centroid": [
          18.200407,
          -67.132661
        ],
        "county_seat": null
      },
      {
        "county_name": "Moca County",
        "state_fips": "72",
        "county_fips": "72099",
        "population": 37460,
        "land_area_sq_mi": 50.341,
        "centroid": [
          18.380886,
          -67.083785
        ],
        "county_seat": null
      },
      {
        "county_name": "Morovis County",
        "state_fips": "72",
        "county_fips": "72101",
        "population": 28727,
        "land_area_sq_mi": 38.871,
        "centroid": [
          18.328822,
          -66.412994
        ],
        "county_seat": null
      },
      {
        "county_name": "Naguabo County",
        "state_fips": "72",
        "county_fips": "72103",
        "population": 23386,
        "land_area_sq_mi": 51.661,
        "centroid": [
          18.218695,
          -65.749375
        ],
        "county_seat": null
      },
      {
        "county_name": "Naranjito County",
        "state_fips": "72",
        "county_fips": "72105",
        "population": 29241,
        "land_area_sq_mi": 27.401,
        "centroid": [
          18.292637,
          -66.251108
        ],
        "county_seat": null
      },
      {
        "county_name": "Orocovis County",
        "state_fips": "72",
        "county_fips": "72107",
        "population": 21434,
        "land_area_sq_mi": 63.616,
        "centroid": [
          18.222018,
          -66.406737
        ],
        "county_seat": null
      },
      {
        "county_name": "Patillas County",
        "state_fips": "72",
        "county_fips": "72109",
        "population": 15985,
        "land_area_sq_mi": 46.604,
        "centroid": [
          18.007498,
          -66.00459
        ],
        "county_seat": null
      },
      {
        "county_name": "Pe\u00f1uelas County",
        "state_fips": "72",
        "county_fips": "72111",
        "population": 20399,
        "land_area_sq_mi": 44.65,
        "centroid": [
          18.058586,
          -66.722282
        ],
        "county_seat": null
      },
      {
        "county_name": "Ponce County",
        "state_fips": "72",
        "county_fips": "72113",
        "population": 137491,
        "land_area_sq_mi": 114.912,
        "centroid": [
          18.02175,
          -66.616993
        ],
        "county_seat": null
      },
      {
        "county_name": "Quebradillas County",
        "state_fips": "72",
        "county_fips": "72115",
        "population": 23638,
        "land_area_sq_mi": 22.668,
        "centroid": [
          18.45455,
          -66.92736
        ],
        "county_seat": null
      },
      {
        "county_name": "Rinc\u00f3n County",
        "state_fips": "72",
        "county_fips": "72117",
        "population": 15187,
        "land_area_sq_mi": 14.288,
        "centroid": [
          18.334123,
          -67.233645
        ],
        "county_seat": null
      },
      {
        "county_name": "R\u00edo Grande County",
        "state_fips": "72",
        "county_fips": "72119",
        "population": 47060,
        "land_area_sq_mi": 60.621,
        "centroid": [
          18.367271,
          -65.827512
        ],
        "county_seat": null
      },
      {
        "county_name": "Sabana Grande County",
        "state_fips": "72",
        "county_fips": "72121",
        "population": 22729,
        "land_area_sq_mi": 36.298,
        "centroid": [
          18.070416,
          -66.950547
        ],
        "county_seat": null
      },
      {
        "county_name": "Salinas County",
        "state_fips": "72",
        "county_fips": "72123",
        "population": 25789,
        "land_area_sq_mi": 69.404,
        "centroid": [
          17.991105,
          -66.260357
        ],
        "county_seat": null
      },
      {
        "county_name": "San Germ\u00e1n County",
        "state_fips": "72",
        "county_fips": "72125",
        "population": 31879,
        "land_area_sq_mi": 54.497,
        "centroid": [
          18.096123,
          -67.041209
        ],
        "county_seat": null
      },
      {
        "county_name": "San Juan County",
        "state_fips": "72",
        "county_fips": "72127",
        "population": 342259,
        "land_area_sq_mi": 47.886,
        "centroid": [
          18.401963,
          -66.056207
        ],
        "county_seat": null
      },
      {
        "county_name": "San Lorenzo County",
        "state_fips": "72",
        "county_fips": "72129",
        "population": 37693,
        "land_area_sq_mi": 53.108,
        "centroid": [
          18.171583,
          -65.972121
        ],
        "county_seat": null
      },
      {
        "county_name": "San Sebasti\u00e1n County",
        "state_fips": "72",
        "county_fips": "72131",
        "population": 39345,
        "land_area_sq_mi": 70.426,
        "centroid": [
          18.335187,
          -66.982212
        ],
        "county_seat": null
      },
      {
        "county_name": "Santa Isabel County",
        "state_fips": "72",
        "county_fips": "72133",
        "population": 20281,
        "land_area_sq_mi": 34.05,
        "centroid": [
          17.98922,
          -66.394622
        ],
        "county_seat": null
      },
      {
        "county_name": "Toa Alta County",
        "state_fips": "72",
        "county_fips": "72135",
        "population": 66852,
        "land_area_sq_mi": 27.021,
        "centroid": [
          18.367369,
          -66.229556
        ],
        "county_seat": null
      },
      {
        "county_name": "Toa Baja County",
        "state_fips": "72",
        "county_fips": "72137",
        "population": 75293,
        "land_area_sq_mi": 23.244,
        "centroid": [
          18.429333,
          -66.201719
        ],
        "county_seat": null
      },
      {
        "county_name": "Trujillo Alto County",
        "state_fips": "72",
        "county_fips": "72139",
        "population": 67740,
        "land_area_sq_mi": 20.758,
        "centroid": [
          18.35072,
          -66.008142
        ],
        "county_seat": null
      },
      {
        "county_name": "Utuado County",
        "state_fips": "72",
        "county_fips": "72141",
        "population": 28287,
        "land_area_sq_mi": 113.54,
        "centroid": [
          18.268678,
          -66.707197
        ],
        "county_seat": null
      },
      {
        "county_name": "Vega Alta County",
        "state_fips": "72",
        "county_fips": "72143",
        "population": 35395,
        "land_area_sq_mi": 27.726,
        "centroid": [
          18.423353,
          -66.331592
        ],
        "county_seat": null
      },
      {
        "county_name": "Vega Baja County",
        "state_fips": "72",
        "county_fips": "72145",
        "population": 54414,
        "land_area_sq_mi": 45.848,
        "centroid": [
          18.439692,
          -66.399082
        ],
        "county_seat": null
      },
      {
        "county_name": "Vieques County",
        "state_fips": "72",
        "county_fips": "72147",
        "population": 8249,
        "land_area_sq_mi": 50.788,
        "centroid": [
          18.134221,
          -65.448953
        ],
        "county_seat": null
      },
      {
        "county_name": "Villalba County",
        "state_fips": "72",
        "county_fips": "72149",
        "population": 22093,
        "land_area_sq_mi": 35.599,
        "centroid": [
          18.123806,
          -66.486557
        ],
        "county_seat": null
      },
      {
        "county_name": "Yabucoa County",
        "state_fips": "72",
        "county_fips": "72151",
        "population": 30426,
        "land_area_sq_mi": 55.215,
        "centroid": [
          18.068957,
          -65.885852
        ],
        "county_seat": null
      },
      {
        "county_name": "Yauco County",
        "state_fips": "72",
        "county_fips": "72153",
        "population": 34172,
        "land_area_sq_mi": 67.737,
        "centroid": [
          18.043328,
          -66.859541
        ],
        "county_seat": null
      }
    ]
