# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Baker County",
        "state_fips": "41",
        "county_fips": "41001",
        "population": 16668,
        "land_area_sq_mi": 3067.967,
        "centroid": [
          44.780021,
          -117.762087
        ],
        "county_seat": null
      },
      {
        "county_name": "Benton County",
        "state_fips": "41",
        "county_fips": "41003",
        "population": 95184,
        "land_area_sq_mi": 675.208,
        "centroid": [
          44.573123,
          -123.275062
        ],
        "county_seat": null
      },
      {
        "county_name": "Clackamas County",
        "state_fips": "41",
        "county_fips": "41005",
        "population": 421401,
        "land_area_sq_mi": 1870.711,
        "centroid": [
          45.363411,
          -122.575016
        ],
        "county_seat": null
      },
      {
        "county_name": "Clatsop County",
        "state_fips": "41",
        "county_fips": "41007",
        "population": 41072,
        "land_area_sq_mi": 828.239,
        "centroid": [
          46.098894,
          -123.841041
        ],
        "county_seat": null
      },
      {
        "county_name": "Columbia County",
        "state_fips": "41",
        "county_fips": "41009",
        "population": 52589,
        "land_area_sq_mi": 658.684,
        "centroid": [
          45.889969,
          -122.929381
        ],
        "county_seat": null
      },
      {
        "county_name": "Coos County",
        "state_fips": "41",
        "county_fips": "41011",
        "population": 64929,
        "land_area_sq_mi": 1596.044,
        "centroid": [
          43.305461,
          -124.232445
        ],
        "county_seat": null
      },
      {
        "county_name": "Crook County",
        "state_fips": "41",
        "county_fips": "41013",
        "population": 24738,
        "land_area_sq_mi": 2978.929,
        "centroid": [
          44.283564,
          -120.843605
        ],
        "county_seat": null
      },
      {
        "county_name": "Curry County",
        "state_fips": "41",
        "county_fips": "41015",
        "population": 23446,
        "land_area_sq_mi": 1628.395,
        "centroid": [
          42.251867,
          -124.327962
        ],
        "county_seat": null
      },
      {
        "county_name": "Deschutes County",
        "state_fips": "41",
        "county_fips": "41017",
        "population": 198253,
        "land_area_sq_mi": 3017.61,
        "centroid": [
          44.090954,
          -121.306213
        ],
        "county_seat": null
      },
      {
        "county_name": "Douglas County",
        "state_fips": "41",
        "county_fips": "41019",
        "population": 111201,
        "land_area_sq_mi": 5035.676,
        "centroid": [
          43.239963,
          -123.388771
        ],
        "county_seat": null
      },
      {
        "county_name": "Gilliam County",
        "state_fips": "41",
        "county_fips": "41021",
        "population": 1995,
        "land_area_sq_mi": 1204.721,
        "centroid": [
          45.449592,
          -120.197022
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "41",
        "county_fips": "41023",
        "population": 7233,
        "land_area_sq_mi": 4527.792,
        "centroid": [
          44.451525,
          -119.003559
        ],
        "county_seat": null
      },
      {
        "county_name": "Harney County",
        "state_fips": "41",
        "county_fips": "41025",
        "population": 7495,
        "land_area_sq_mi": 10134.438,
        "centroid": [
          43.521602,
          -118.986891
        ],
        "county_seat": null
      },
      {
        "county_name": "Hood River County",
        "state_fips": "41",
        "county_fips": "41027",
        "population": 23977,
        "land_area_sq_mi": 522.194,
        "centroid": [
          45.658959,
          -121.565661
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "41",
        "county_fips": "41029",
        "population": 223259,
        "land_area_sq_mi": 2783.251,
        "centroid": [
          42.347769,
          -122.858631
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "41",
        "county_fips": "41031",
        "population": 24502,
        "land_area_sq_mi": 1781.696,
        "centroid": [
          44.591478,
          -121.190361
        ],
        "county_seat": null
      },
      {
        "county_name": "Josephine County",
        "state_fips": "41",
        "county_fips": "41033",
        "population": 88090,
        "land_area_sq_mi": 1638.649,
        "centroid": [
          42.404433,
          -123.38517
        ],
        "county_seat": null
      },
      {
        "county_name": "Klamath County",
        "state_fips": "41",
        "county_fips": "41035",
        "population": 69413,
        "land_area_sq_mi": 5949.897,
        "centroid": [
          42.285893,
          -121.726802
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake County",
        "state_fips": "41",
        "county_fips": "41037",
        "population": 8160,
        "land_area_sq_mi": 8138.61,
        "centroid": [
          42.478434,
          -120.476422
        ],
        "county_seat": null
      },
      {
        "county_name": "Lane County",
        "state_fips": "41",
        "county_fips": "41039",
        "population": 382971,
        "land_area_sq_mi": 4554.092,
        "centroid": [
          44.039563,
          -123.119235
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "41",
        "county_fips": "41041",
        "population": 50395,
        "land_area_sq_mi": 980.983,
        "centroid": [
          44.713731,
          -124.002001
        ],
        "county_seat": null
      },
      {
        "county_name": "Linn County",
        "state_fips": "41",
        "county_fips": "41043",
        "population": 128610,
        "land_area_sq_mi": 2289.508,
        "centroid": [
          44.556336,
          -122.959471
        ],
        "county_seat": null
      },
      {
        "county_name": "Malheur County",
        "state_fips": "41",
        "county_fips": "41045",
        "population": 31571,
        "land_area_sq_mi": 9887.707,
        "centroid": [
          43.975358,
          -117.06114
        ],
        "county_seat": null
      },
      {
        "county_name": "Marion County",
        "state_fips": "41",
        "county_fips": "41047",
        "population": 345920,
        "land_area_sq_mi": 1180.84,
        "centroid": [
          44.960149,
          -122.955907
        ],
        "county_seat": null
      },
      {
        "county_name": "Morrow County",
        "state_fips": "41",
        "county_fips": "41049",
        "population": 12186,
        "land_area_sq_mi": 2030.529,
        "centroid": [
          45.739056,
          -119.617276
        ],
        "county_seat": null
      },
      {
        "county_name": "Multnomah County",
        "state_fips": "41",
        "county_fips": "41051",
        "population": 815428,
        "land_area_sq_mi": 431.019,
        "centroid": [
          45.517904,
          -122.591156
        ],
        "county_seat": null
      },
      {
        "county_name": "Polk County",
        "state_fips": "41",
        "county_fips": "41053",
        "population": 87433,
        "land_area_sq_mi": 740.924,
        "centroid": [
          44.920857,
          -123.20811
        ],
        "county_seat": null
      },
      {
        "county_name": "Sherman County",
        "state_fips": "41",
        "county_fips": "41055",
        "population": 1870,
        "land_area_sq_mi": 823.614,
        "centroid": [
          45.518367,
          -120.72146
        ],
        "county_seat": null
      },
      {
        "county_name": "Tillamook County",
        "state_fips": "41",
        "county_fips": "41057",
        "population": 27390,
        "land_area_sq_mi": 1103.183,
        "centroid": [
          45.469525,
          -123.858484
        ],
        "county_seat": null
      },
      {
        "county_name": "Umatilla County",
        "state_fips": "41",
        "county_fips": "41059",
        "population": 80075,
        "land_area_sq_mi": 3215.45,
        "centroid": [
          45.801243,
          -118.967455
        ],
        "county_seat": null
      },
      {
        "county_name": "Union County",
        "state_fips": "41",
        "county_fips": "41061",
        "population": 26196,
        "land_area_sq_mi": 2036.941,
        "centroid": [
          45.341591,
          -118.018208
        ],
        "county_seat": null
      },
      {
        "county_name": "Wallowa County",
        "state_fips": "41",
        "county_fips": "41063",
        "population": 7391,
        "land_area_sq_mi": 3145.897,
        "centroid": [
          45.443336,
          -117.305634
        ],
        "county_seat": null
      },
      {
        "county_name": "Wasco County",
        "state_fips": "41",
        "county_fips": "41065",
        "population": 26670,
        "land_area_sq_mi": 2381.119,
        "centroid": [
          45.541482,
          -121.204066
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "41",
        "county_fips": "41067",
        "population": 600372,
        "land_area_sq_mi": 724.272,
        "centroid": [
          45.486067,
          -122.87092
        ],
        "county_seat": null
      },
      {
        "county_name": "Wheeler County",
        "state_fips": "41",
        "county_fips": "41069",
        "population": 1451,
        "land_area_sq_mi": 1716.021,
        "centroid": [
          44.837096,
          -120.088844
        ],
        "county_seat": null
      },
      {
        "county_name": "Yamhill County",
        "state_fips": "41",
        "county_fips": "41071",
        "population": 107722,
        "land_area_sq_mi": 715.938,
        "centroid": [
          45.239528,
          -123.136974
        ],
        "county_seat": null
      }
    ]
