# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adams County",
        "state_fips": "55",
        "county_fips": "55001",
        "population": 20654,
        "land_area_sq_mi": 645.646,
        "centroid": [
          43.946194,
          -89.78312
        ],
        "county_seat": null
      },
      {
        "county_name": "Ashland County",
        "state_fips": "55",
        "county_fips": "55003",
        "population": 16027,
        "land_area_sq_mi": 1044.97,
        "centroid": [
          46.475919,
          -90.785419
        ],
        "county_seat": null
      },
      {
        "county_name": "Barron County",
        "state_fips": "55",
        "county_fips": "55005",
        "population": 46711,
        "land_area_sq_mi": 863.054,
        "centroid": [
          45.437002,
          -91.815142
        ],
        "county_seat": null
      },
      {
        "county_name": "Bayfield County",
        "state_fips": "55",
        "county_fips": "55007",
        "population": 16220,
        "land_area_sq_mi": 1477.881,
        "centroid": [
          46.594106,
          -91.104441
        ],
        "county_seat": null
      },
      {
        "county_name": "Brown County",
        "state_fips": "55",
        "county_fips": "55009",
        "population": 268740,
        "land_area_sq_mi": 530.092,
        "centroid": [
          44.497155,
          -88.034145
        ],
        "county_seat": null
      },
      {
        "county_name": "Buffalo County",
        "state_fips": "55",
        "county_fips": "55011",
        "population": 13317,
        "land_area_sq_mi": 675.791,
        "centroid": [
          44.380158,
          -91.74144
        ],
        "county_seat": null
      },
      {
        "county_name": "Burnett County",
        "state_fips": "55",
        "county_fips": "55013",
        "population": 16526,
        "land_area_sq_mi": 821.596,
        "centroid": [
          45.836891,
          -92.403811
        ],
        "county_seat": null
      },
      {
        "county_name": "Calumet County",
        "state_fips": "55",
        "county_fips": "55015",
        "population": 52442,
        "land_area_sq_mi": 318.25,
        "centroid": [
          44.152617,
          -88.262936
        ],
        "county_seat": null
      },
      {
        "county_name": "Chippewa County",
        "state_fips": "55",
        "county_fips": "55017",
        "population": 66297,
        "land_area_sq_mi": 1008.355,
        "centroid": [
          44.984928,
          -91.328087
        ],
        "county_seat": null
      },
      {
        "county_name": "Clark County",
        "state_fips": "55",
        "county_fips": "55019",
        "population": 34659,
        "land_area_sq_mi": 1209.698,
        "centroid": [
          44.78814,
          -90.550998
        ],
        "county_seat": null
      },
      {
        "county_name": "Columbia County",
        "state_fips": "55",
        "county_fips": "55021",
        "population": 58490,
        "land_area_sq_mi": 765.6,
        "centroid": [
          43.460151,
          -89.366154
        ],
        "county_seat": null
      },
      {
        "county_name": "Crawford County",
        "state_fips": "55",
        "county_fips": "55023",
        "population": 16113,
        "land_area_sq_mi": 570.805,
        "centroid": [
          43.165384,
          -91.005118
        ],
        "county_seat": null
      },
      {
        "county_name": "Dane County",
        "state_fips": "55",
        "county_fips": "55025",
        "population": 561504,
        "land_area_sq_mi": 1196.497,
        "centroid": [
          43.07564,
          -89.395501
        ],
        "county_seat": null
      },
      {
        "county_name": "Dodge County",
        "state_fips": "55",
        "county_fips": "55027",
        "population": 89396,
        "land_area_sq_mi": 875.699,
        "centroid": [
          43.435904,
          -88.713062
        ],
        "county_seat": null
      },
      {
        "county_name": "Door County",
        "state_fips": "55",
        "county_fips": "55029",
        "population": 30066,
        "land_area_sq_mi": 481.936,
        "centroid": [
          44.915074,
          -87.335769
        ],
        "county_seat": null
      },
      {
        "county_name": "Douglas County",
        "state_fips": "55",
        "county_fips": "55031",
        "population": 44295,
        "land_area_sq_mi": 1304.272,
        "centroid": [
          46.628582,
          -92.01483
        ],
        "county_seat": null
      },
      {
        "county_name": "Dunn County",
        "state_fips": "55",
        "county_fips": "55033",
        "population": 45440,
        "land_area_sq_mi": 850.159,
        "centroid": [
          44.914658,
          -91.892915
        ],
        "county_seat": null
      },
      {
        "county_name": "Eau Claire County",
        "state_fips": "55",
        "county_fips": "55035",
        "population": 105710,
        "land_area_sq_mi": 637.922,
        "centroid": [
          44.790208,
          -91.454792
        ],
        "county_seat": null
      },
      {
        "county_name": "Florence County",
        "state_fips": "55",
        "county_fips": "55037",
        "population": 4558,
        "land_area_sq_mi": 488.024,
        "centroid": [
          45.853651,
          -88.244316
        ],
        "county_seat": null
      },
      {
        "county_name": "Fond du Lac County",
        "state_fips": "55",
        "county_fips": "55039",
        "population": 104154,
        "land_area_sq_mi": 719.566,
        "centroid": [
          43.765547,
          -88.487004
        ],
        "county_seat": null
      },
      {
        "county_name": "Forest County",
        "state_fips": "55",
        "county_fips": "55041",
        "population": 9179,
        "land_area_sq_mi": 1014.266,
        "centroid": [
          45.563411,
          -88.812092
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "55",
        "county_fips": "55043",
        "population": 51938,
        "land_area_sq_mi": 1147.604,
        "centroid": [
          42.827213,
          -90.612643
        ],
        "county_seat": null
      },
      {
        "county_name": "Green County",
        "state_fips": "55",
        "county_fips": "55045",
        "population": 37093,
        "land_area_sq_mi": 584.044,
        "centroid": [
          42.673838,
          -89.575106
        ],
        "county_seat": null
      },
      {
        "county_name": "Green Lake County",
        "state_fips": "55",
        "county_fips": "55047",
        "population": 19018,
        "land_area_sq_mi": 349.541,
        "centroid": [
          43.845067,
          -89.014675
        ],
        "county_seat": null
      },
      {
        "county_name": "Iowa County",
        "state_fips": "55",
        "county_fips": "55049",
        "population": 23709,
        "land_area_sq_mi": 762.698,
        "centroid": [
          42.981998,
          -90.12223
        ],
        "county_seat": null
      },
      {
        "county_name": "Iron County",
        "state_fips": "55",
        "county_fips": "55051",
        "population": 6137,
        "land_area_sq_mi": 758.214,
        "centroid": [
          46.343183,
          -90.189954
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "55",
        "county_fips": "55053",
        "population": 21145,
        "land_area_sq_mi": 987.915,
        "centroid": [
          44.320677,
          -90.903038
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "55",
        "county_fips": "55055",
        "population": 84900,
        "land_area_sq_mi": 556.493,
        "centroid": [
          43.040342,
          -88.785594
        ],
        "county_seat": null
      },
      {
        "county_name": "Juneau County",
        "state_fips": "55",
        "county_fips": "55057",
        "population": 26718,
        "land_area_sq_mi": 767.081,
        "centroid": [
          43.843115,
          -90.09764
        ],
        "county_seat": null
      },
      {
        "county_name": "Kenosha County",
        "state_fips": "55",
        "county_fips": "55059",
        "population": 169151,
        "land_area_sq_mi": 271.833,
        "centroid": [
          42.572393,
          -87.924047
        ],
        "county_seat": null
      },
      {
        "county_name": "Kewaunee County",
        "state_fips": "55",
        "county_fips": "55061",
        "population": 20563,
        "land_area_sq_mi": 342.454,
        "centroid": [
          44.527818,
          -87.591703
        ],
        "county_seat": null
      },
      {
        "county_name": "La Crosse County",
        "state_fips": "55",
        "county_fips": "55063",
        "population": 120784,
        "land_area_sq_mi": 451.803,
        "centroid": [
          43.861018,
          -91.208863
        ],
        "county_seat": null
      },
      {
        "county_name": "Lafayette County",
        "state_fips": "55",
        "county_fips": "55065",
        "population": 16611,
        "land_area_sq_mi": 633.588,
        "centroid": [
          42.663323,
          -90.140565
        ],
        "county_seat": null
      },
      {
        "county_name": "Langlade County",
        "state_fips": "55",
        "county_fips": "55067",
        "population": 19491,
        "land_area_sq_mi": 870.69,
        "centroid": [
          45.185054,
          -89.104985
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "55",
        "county_fips": "55069",
        "population": 28415,
        "land_area_sq_mi": 878.71,
        "centroid": [
          45.288548,
          -89.686454
        ],
        "county_seat": null
      },
      {
        "county_name": "Manitowoc County",
        "state_fips": "55",
        "county_fips": "55071",
        "population": 81359,
        "land_area_sq_mi": 589.309,
        "centroid": [
          44.10361,
          -87.724344
        ],
        "county_seat": null
      },
      {
        "county_name": "Marathon County",
        "state_fips": "55",
        "county_fips": "55073",
        "population": 138013,
        "land_area_sq_mi": 1545.238,
        "centroid": [
          44.907455,
          -89.707823
        ],
        "county_seat": null
      },
      {
        "county_name": "Marinette County",
        "state_fips": "55",
        "county_fips": "55075",
        "population": 41872,
        "land_area_sq_mi": 1399.468,
        "centroid": [
          45.219097,
          -87.848007
        ],
        "county_seat": null
      },
      {
        "county_name": "Marquette County",
        "state_fips": "55",
        "county_fips": "55077",
        "population": 15592,
        "land_area_sq_mi": 455.713,
        "centroid": [
          43.810948,
          -89.407897
        ],
        "county_seat": null
      },
      {
        "county_name": "Menominee County",
        "state_fips": "55",
        "county_fips": "55078",
        "population": 4255,
        "land_area_sq_mi": 357.615,
        "centroid": [
          44.912634,
          -88.635691
        ],
        "county_seat": null
      },
      {
        "county_name": "Milwaukee County",
        "state_fips": "55",
        "county_fips": "55079",
        "population": 939489,
        "land_area_sq_mi": 241.457,
        "centroid": [
          43.031416,
          -87.959526
        ],
        "county_seat": null
      },
      {
        "county_name": "Monroe County",
        "state_fips": "55",
        "county_fips": "55081",
        "population": 46274,
        "land_area_sq_mi": 900.904,
        "centroid": [
          43.942578,
          -90.644211
        ],
        "county_seat": null
      },
      {
        "county_name": "Oconto County",
        "state_fips": "55",
        "county_fips": "55083",
        "population": 38965,
        "land_area_sq_mi": 997.477,
        "centroid": [
          44.895367,
          -88.146318
        ],
        "county_seat": null
      },
      {
        "county_name": "Oneida County",
        "state_fips": "55",
        "county_fips": "55085",
        "population": 37845,
        "land_area_sq_mi": 1113.944,
        "centroid": [
          45.71099,
          -89.493946
        ],
        "county_seat": null
      },
      {
        "county_name": "Outagamie County",
        "state_fips": "55",
        "county_fips": "55087",
        "population": 190705,
        "land_area_sq_mi": 637.557,
        "centroid": [
          44.308666,
          -88.401368
        ],
        "county_seat": null
      },
      {
        "county_name": "Ozaukee County",
        "state_fips": "55",
        "county_fips": "55089",
        "population": 91503,
        "land_area_sq_mi": 233.011,
        "centroid": [
          43.31881,
          -87.950093
        ],
        "county_seat": null
      },
      {
        "county_name": "Pepin County",
        "state_fips": "55",
        "county_fips": "55091",
        "population": 7318,
        "land_area_sq_mi": 232.008,
        "centroid": [
          44.591768,
          -91.987424
        ],
        "county_seat": null
      },
      {
        "county_name": "Pierce County",
        "state_fips": "55",
        "county_fips": "55093",
        "population": 42212,
        "land_area_sq_mi": 574.018,
        "centroid": [
          44.77335,
          -92.547747
        ],
        "county_seat": null
      },
      {
        "county_name": "Polk County",
        "state_fips": "55",
        "county_fips": "55095",
        "population": 44977,
        "land_area_sq_mi": 914.32,
        "centroid": [
          45.404946,
          -92.481404
        ],
        "county_seat": null
      },
      {
        "county_name": "Portage County",
        "state_fips": "55",
        "county_fips": "55097",
        "population": 70377,
        "land_area_sq_mi": 800.874,
        "centroid": [
          44.498026,
          -89.526076
        ],
        "county_seat": null
      },
      {
        "county_name": "Price County",
        "state_fips": "55",
        "county_fips": "55099",
        "population": 14054,
        "land_area_sq_mi": 1254.057,
        "centroid": [
          45.724359,
          -90.39805
        ],
        "county_seat": null
      },
      {
        "county_name": "Racine County",
        "state_fips": "55",
        "county_fips": "55101",
        "population": 197727,
        "land_area_sq_mi": 332.611,
        "centroid": [
          42.735037,
          -87.928046
        ],
        "county_seat": null
      },
      {
        "county_name": "Richland County",
        "state_fips": "55",
        "county_fips": "55103",
        "population": 17304,
        "land_area_sq_mi": 586.15,
        "centroid": [
          43.350268,
          -90.390394
        ],
        "county_seat": null
      },
      {
        "county_name": "Rock County",
        "state_fips": "55",
        "county_fips": "55105",
        "population": 163687,
        "land_area_sq_mi": 718.168,
        "centroid": [
          42.65481,
          -89.037935
        ],
        "county_seat": null
      },
      {
        "county_name": "Rusk County",
        "state_fips": "55",
        "county_fips": "55107",
        "population": 14188,
        "land_area_sq_mi": 913.511,
        "centroid": [
          45.44497,
          -91.130594
        ],
        "county_seat": null
      },
      {
        "county_name": "St. Croix County",
        "state_fips": "55",
        "county_fips": "55109",
        "population": 93536,
        "land_area_sq_mi": 722.158,
        "centroid": [
          45.017968,
          -92.580626
        ],
        "county_seat": null
      },
      {
        "county_name": "Sauk County",
        "state_fips": "55",
        "county_fips": "55111",
        "population": 65763,
        "land_area_sq_mi": 831.587,
        "centroid": [
          43.449264,
          -89.868041
        ],
        "county_seat": null
      },
      {
        "county_name": "Sawyer County",
        "state_fips": "55",
        "county_fips": "55113",
        "population": 18074,
        "land_area_sq_mi": 1257.6,
        "centroid": [
          45.938054,
          -91.345247
        ],
        "county_seat": null
      },
      {
        "county_name": "Shawano County",
        "state_fips": "55",
        "county_fips": "55115",
        "population": 40881,
        "land_area_sq_mi": 893.225,
        "centroid": [
          44.786908,
          -88.681002
        ],
        "county_seat": null
      },
      {
        "county_name": "Sheboygan County",
        "state_fips": "55",
        "county_fips": "55117",
        "population": 118034,
        "land_area_sq_mi": 511.519,
        "centroid": [
          43.733622,
          -87.819076
        ],
        "county_seat": null
      },
      {
        "county_name": "Taylor County",
        "state_fips": "55",
        "county_fips": "55119",
        "population": 19913,
        "land_area_sq_mi": 975.052,
        "centroid": [
          45.172334,
          -90.408593
        ],
        "county_seat": null
      },
      {
        "county_name": "Trempealeau County",
        "state_fips": "55",
        "county_fips": "55121",
        "population": 30760,
        "land_area_sq_mi": 732.966,
        "centroid": [
          44.287418,
          -91.363458
        ],
        "county_seat": null
      },
      {
        "county_name": "Vernon County",
        "state_fips": "55",
        "county_fips": "55123",
        "population": 30714,
        "land_area_sq_mi": 791.563,
        "centroid": [
          43.605271,
          -90.835696
        ],
        "county_seat": null
      },
      {
        "county_name": "Vilas County",
        "state_fips": "55",
        "county_fips": "55125",
        "population": 23047,
        "land_area_sq_mi": 857.71,
        "centroid": [
          45.988218,
          -89.496963
        ],
        "county_seat": null
      },
      {
        "county_name": "Walworth County",
        "state_fips": "55",
        "county_fips": "55127",
        "population": 106478,
        "land_area_sq_mi": 555.433,
        "centroid": [
          42.662934,
          -88.540338
        ],
        "county_seat": null
      },
      {
        "county_name": "Washburn County",
        "state_fips": "55",
        "county_fips": "55129",
        "population": 16623,
        "land_area_sq_mi": 797.114,
        "centroid": [
          45.848159,
          -91.835392
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "55",
        "county_fips": "55131",
        "population": 136761,
        "land_area_sq_mi": 430.644,
        "centroid": [
          43.345574,
          -88.216407
        ],
        "county_seat": null
      },
      {
        "county_name": "Waukesha County",
        "state_fips": "55",
        "county_fips": "55133",
        "population": 406978,
        "land_area_sq_mi": 549.725,
        "centroid": [
          43.03596,
          -88.236186
        ],
        "county_seat": null
      },
      {
        "county_name": "Waupaca County",
        "state_fips": "55",
        "county_fips": "55135",
        "population": 51812,
        "land_area_sq_mi": 747.702,
        "centroid": [
          44.432697,
          -88.937028
        ],
        "county_seat": null
      },
      {
        "county_name": "Waushara County",
        "state_fips": "55",
        "county_fips": "55137",
        "population": 24520,
        "land_area_sq_mi": 626.161,
        "centroid": [
          44.101477,
          -89.225784
        ],
        "county_seat": null
      },
      {
        "county_name": "Winnebago County",
        "state_fips": "55",
        "county_fips": "55139",
        "population": 171730,
        "land_area_sq_mi": 434.697,
        "centroid": [
          44.101514,
          -88.540906
        ],
        "county_seat": null
      },
      {
        "county_name": "Wood County",
        "state_fips": "55",
        "county_fips": "55141",
        "population": 74207,
        "land_area_sq_mi": 793.02,
        "centroid": [
          44.478457,
          -89.962546
        ],
        "county_seat": null
      }
    ]
