# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adams County",
        "state_fips": "18",
        "county_fips": "18001",
        "population": 35809,
        "land_area_sq_mi": 338.925,
        "centroid": [
          40.749532,
          -84.934318
        ],
        "county_seat": null
      },
      {
        "county_name": "Allen County",
        "state_fips": "18",
        "county_fips": "18003",
        "population": 385410,
        "land_area_sq_mi": 657.146,
        "centroid": [
          41.100842,
          -85.125233
        ],
        "county_seat": null
      },
      {
        "county_name": "Bartholomew County",
        "state_fips": "18",
        "county_fips": "18005",
        "population": 82208,
        "land_area_sq_mi": 406.94,
        "centroid": [
          39.215015,
          -85.905294
        ],
        "county_seat": null
      },
      {
        "county_name": "Benton County",
        "state_fips": "18",
        "county_fips": "18007",
        "population": 8719,
        "land_area_sq_mi": 406.418,
        "centroid": [
          40.576258,
          -87.291866
        ],
        "county_seat": null
      },
      {
        "county_name": "Blackford County",
        "state_fips": "18",
        "county_fips": "18009",
        "population": 12112,
        "land_area_sq_mi": 165.082,
        "centroid": [
          40.468109,
          -85.345621
        ],
        "county_seat": null
      },
      {
        "county_name": "Boone County",
        "state_fips": "18",
        "county_fips": "18011",
        "population": 70812,
        "land_area_sq_mi": 422.882,
        "centroid": [
          40.004643,
          -86.383249
        ],
        "county_seat": null
      },
      {
        "county_name": "Brown County",
        "state_fips": "18",
        "county_fips": "18013",
        "population": 15475,
        "land_area_sq_mi": 311.987,
        "centroid": [
          39.236665,
          -86.208688
        ],
        "county_seat": null
      },
      {
        "county_name": "Carroll County",
        "state_fips": "18",
        "county_fips": "18015",
        "population": 20306,
        "land_area_sq_mi": 372.225,
        "centroid": [
          40.579184,
          -86.601213
        ],
        "county_seat": null
      },
      {
        "county_name": "Cass County",
        "state_fips": "18",
        "county_fips": "18017",
        "population": 37870,
        "land_area_sq_mi": 412.144,
        "centroid": [
          40.747129,
          -86.338974
        ],
        "county_seat": null
      },
      {
        "county_name": "Clark County",
        "state_fips": "18",
        "county_fips": "18019",
        "population": 121093,
        "land_area_sq_mi": 372.487,
        "centroid": [
          38.373412,
          -85.732548
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "18",
        "county_fips": "18021",
        "population": 26466,
        "land_area_sq_mi": 357.6,
        "centroid": [
          39.469332,
          -87.123964
        ],
        "county_seat": null
      },
      {
        "county_name": "Clinton County",
        "state_fips": "18",
        "county_fips": "18023",
        "population": 33190,
        "land_area_sq_mi": 405.067,
        "centroid": [
          40.297795,
          -86.513556
        ],
        "county_seat": null
      },
      {
        "county_name": "Crawford County",
        "state_fips": "18",
        "county_fips": "18025",
        "population": 10526,
        "land_area_sq_mi": 305.613,
        "centroid": [
          38.315739,
          -86.422116
        ],
        "county_seat": null
      },
      {
        "county_name": "Daviess County",
        "state_fips": "18",
        "county_fips": "18027",
        "population": 33381,
        "land_area_sq_mi": 429.514,
        "centroid": [
          38.697526,
          -87.096158
        ],
        "county_seat": null
      },
      {
        "county_name": "Dearborn County",
        "state_fips": "18",
        "county_fips": "18029",
        "population": 50679,
        "land_area_sq_mi": 305.087,
        "centroid": [
          39.14676,
          -84.920533
        ],
        "county_seat": null
      },
      {
        "county_name": "Decatur County",
        "state_fips": "18",
        "county_fips": "18031",
        "population": 26472,
        "land_area_sq_mi": 372.568,
        "centroid": [
          39.320693,
          -85.493081
        ],
        "county_seat": null
      },
      {
        "county_name": "DeKalb County",
        "state_fips": "18",
        "county_fips": "18033",
        "population": 43265,
        "land_area_sq_mi": 362.834,
        "centroid": [
          41.377157,
          -85.034535
        ],
        "county_seat": null
      },
      {
        "county_name": "Delaware County",
        "state_fips": "18",
        "county_fips": "18035",
        "population": 111903,
        "land_area_sq_mi": 392.109,
        "centroid": [
          40.20524,
          -85.402908
        ],
        "county_seat": null
      },
      {
        "county_name": "Dubois County",
        "state_fips": "18",
        "county_fips": "18037",
        "population": 43637,
        "land_area_sq_mi": 427.267,
        "centroid": [
          38.35868,
          -86.915674
        ],
        "county_seat": null
      },
      {
        "county_name": "Elkhart County",
        "state_fips": "18",
        "county_fips": "18039",
        "population": 207047,
        "land_area_sq_mi": 463.158,
        "centroid": [
          41.637245,
          -85.905688
        ],
        "county_seat": null
      },
      {
        "county_name": "Fayette County",
        "state_fips": "18",
        "county_fips": "18041",
        "population": 23398,
        "land_area_sq_mi": 215.021,
        "centroid": [
          39.64037,
          -85.147252
        ],
        "county_seat": null
      },
      {
        "county_name": "Floyd County",
        "state_fips": "18",
        "county_fips": "18043",
        "population": 80484,
        "land_area_sq_mi": 148.486,
        "centroid": [
          38.32223,
          -85.857888
        ],
        "county_seat": null
      },
      {
        "county_name": "Fountain County",
        "state_fips": "18",
        "county_fips": "18045",
        "population": 16479,
        "land_area_sq_mi": 395.668,
        "centroid": [
          40.14941,
          -87.274375
        ],
        "county_seat": null
      },
      {
        "county_name": "Franklin County",
        "state_fips": "18",
        "county_fips": "18047",
        "population": 22785,
        "land_area_sq_mi": 384.426,
        "centroid": [
          39.398519,
          -85.070967
        ],
        "county_seat": null
      },
      {
        "county_name": "Fulton County",
        "state_fips": "18",
        "county_fips": "18049",
        "population": 20480,
        "land_area_sq_mi": 368.393,
        "centroid": [
          41.059339,
          -86.217151
        ],
        "county_seat": null
      },
      {
        "county_name": "Gibson County",
        "state_fips": "18",
        "county_fips": "18051",
        "population": 33011,
        "land_area_sq_mi": 487.378,
        "centroid": [
          38.305848,
          -87.549447
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "18",
        "county_fips": "18053",
        "population": 66674,
        "land_area_sq_mi": 414.089,
        "centroid": [
          40.525256,
          -85.644184
        ],
        "county_seat": null
      },
      {
        "county_name": "Greene County",
        "state_fips": "18",
        "county_fips": "18055",
        "population": 30803,
        "land_area_sq_mi": 542.467,
        "centroid": [
          39.052523,
          -86.994152
        ],
        "county_seat": null
      },
      {
        "county_name": "Hamilton County",
        "state_fips": "18",
        "county_fips": "18057",
        "population": 347467,
        "land_area_sq_mi": 394.388,
        "centroid": [
          40.001506,
          -86.057612
        ],
        "county_seat": null
      },
      {
        "county_name": "Hancock County",
        "state_fips": "18",
        "county_fips": "18059",
        "population": 79840,
        "land_area_sq_mi": 305.957,
        "centroid": [
          39.815247,
          -85.829626
        ],
        "county_seat": null
      },
      {
        "county_name": "Harrison County",
        "state_fips": "18",
        "county_fips": "18061",
        "population": 39654,
        "land_area_sq_mi": 484.081,
        "centroid": [
          38.234174,
          -86.098168
        ],
        "county_seat": null
      },
      {
        "county_name": "Hendricks County",
        "state_fips": "18",
        "county_fips": "18063",
        "population": 174788,
        "land_area_sq_mi": 406.894,
        "centroid": [
          39.773147,
          -86.41108
        ],
        "county_seat": null
      },
      {
        "county_name": "Henry County",
        "state_fips": "18",
        "county_fips": "18065",
        "population": 48914,
        "land_area_sq_mi": 391.877,
        "centroid": [
          39.928844,
          -85.403738
        ],
        "county_seat": null
      },
      {
        "county_name": "Howard County",
        "state_fips": "18",
        "county_fips": "18067",
        "population": 83658,
        "land_area_sq_mi": 293.074,
        "centroid": [
          40.470296,
          -86.133562
        ],
        "county_seat": null
      },
      {
        "county_name": "Huntington County",
        "state_fips": "18",
        "county_fips": "18069",
        "population": 36662,
        "land_area_sq_mi": 382.639,
        "centroid": [
          40.869855,
          -85.486182
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "18",
        "county_fips": "18071",
        "population": 46428,
        "land_area_sq_mi": 509.978,
        "centroid": [
          38.928711,
          -85.936294
        ],
        "county_seat": null
      },
      {
        "county_name": "Jasper County",
        "state_fips": "18",
        "county_fips": "18073",
        "population": 32918,
        "land_area_sq_mi": 559.68,
        "centroid": [
          41.082454,
          -87.150606
        ],
        "county_seat": null
      },
      {
        "county_name": "Jay County",
        "state_fips": "18",
        "county_fips": "18075",
        "population": 20478,
        "land_area_sq_mi": 383.905,
        "centroid": [
          40.430767,
          -85.028696
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "18",
        "county_fips": "18077",
        "population": 33147,
        "land_area_sq_mi": 360.699,
        "centroid": [
          38.758699,
          -85.433151
        ],
        "county_seat": null
      },
      {
        "county_name": "Jennings County",
        "state_fips": "18",
        "county_fips": "18079",
        "population": 27613,
        "land_area_sq_mi": 376.597,
        "centroid": [
          39.005508,
          -85.649705
        ],
        "county_seat": null
      },
      {
        "county_name": "Johnson County",
        "state_fips": "18",
        "county_fips": "18081",
        "population": 161765,
        "land_area_sq_mi": 320.415,
        "centroid": [
          39.555913,
          -86.115187
        ],
        "county_seat": null
      },
      {
        "county_name": "Knox County",
        "state_fips": "18",
        "county_fips": "18083",
        "population": 36282,
        "land_area_sq_mi": 515.831,
        "centroid": [
          38.699306,
          -87.454832
        ],
        "county_seat": null
      },
      {
        "county_name": "Kosciusko County",
        "state_fips": "18",
        "county_fips": "18085",
        "population": 80240,
        "land_area_sq_mi": 531.446,
        "centroid": [
          41.267835,
          -85.830509
        ],
        "county_seat": null
      },
      {
        "county_name": "LaGrange County",
        "state_fips": "18",
        "county_fips": "18087",
        "population": 40446,
        "land_area_sq_mi": 379.632,
        "centroid": [
          41.632874,
          -85.467264
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake County",
        "state_fips": "18",
        "county_fips": "18089",
        "population": 498700,
        "land_area_sq_mi": 498.89,
        "centroid": [
          41.518998,
          -87.407505
        ],
        "county_seat": null
      },
      {
        "county_name": "LaPorte County",
        "state_fips": "18",
        "county_fips": "18091",
        "population": 112417,
        "land_area_sq_mi": 598.288,
        "centroid": [
          41.632279,
          -86.791226
        ],
        "county_seat": null
      },
      {
        "county_name": "Lawrence County",
        "state_fips": "18",
        "county_fips": "18093",
        "population": 45011,
        "land_area_sq_mi": 449.146,
        "centroid": [
          38.847818,
          -86.495942
        ],
        "county_seat": null
      },
      {
        "county_name": "Madison County",
        "state_fips": "18",
        "county_fips": "18095",
        "population": 130129,
        "land_area_sq_mi": 451.921,
        "centroid": [
          40.113496,
          -85.7088
        ],
        "county_seat": null
      },
      {
        "county_name": "Marion County",
        "state_fips": "18",
        "county_fips": "18097",
        "population": 977203,
        "land_area_sq_mi": 395.996,
        "centroid": [
          39.788896,
          -86.136268
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "18",
        "county_fips": "18099",
        "population": 46095,
        "land_area_sq_mi": 443.618,
        "centroid": [
          41.347653,
          -86.272256
        ],
        "county_seat": null
      },
      {
        "county_name": "Martin County",
        "state_fips": "18",
        "county_fips": "18101",
        "population": 9812,
        "land_area_sq_mi": 335.761,
        "centroid": [
          38.679659,
          -86.850513
        ],
        "county_seat": null
      },
      {
        "county_name": "Miami County",
        "state_fips": "18",
        "county_fips": "18103",
        "population": 35962,
        "land_area_sq_mi": 373.842,
        "centroid": [
          40.729384,
          -86.076111
        ],
        "county_seat": null
      },
      {
        "county_name": "Monroe County",
        "state_fips": "18",
        "county_fips": "18105",
        "population": 139718,
        "land_area_sq_mi": 394.523,
        "centroid": [
          39.162275,
          -86.53857
        ],
        "county_seat": null
      },
      {
        "county_name": "Montgomery County",
        "state_fips": "18",
        "county_fips": "18107",
        "population": 37936,
        "land_area_sq_mi": 504.652,
        "centroid": [
          40.034526,
          -86.90058
        ],
        "county_seat": null
      },
      {
        "county_name": "Morgan County",
        "state_fips": "18",
        "county_fips": "18109",
        "population": 71780,
        "land_area_sq_mi": 403.831,
        "centroid": [
          39.512934,
          -86.399124
        ],
        "county_seat": null
      },
      {
        "county_name": "Newton County",
        "state_fips": "18",
        "county_fips": "18111",
        "population": 13830,
        "land_area_sq_mi": 401.755,
        "centroid": [
          40.999168,
          -87.38049
        ],
        "county_seat": null
      },
      {
        "county_name": "Noble County",
        "state_fips": "18",
        "county_fips": "18113",
        "population": 47457,
        "land_area_sq_mi": 410.843,
        "centroid": [
          41.415849,
          -85.388959
        ],
        "county_seat": null
      },
      {
        "county_name": "Ohio County",
        "state_fips": "18",
        "county_fips": "18115",
        "population": 5940,
        "land_area_sq_mi": 86.15,
        "centroid": [
          38.954376,
          -84.909987
        ],
        "county_seat": null
      },
      {
        "county_name": "Orange County",
        "state_fips": "18",
        "county_fips": "18117",
        "population": 19867,
        "land_area_sq_mi": 398.379,
        "centroid": [
          38.562253,
          -86.495955
        ],
        "county_seat": null
      },
      {
        "county_name": "Owen County",
        "state_fips": "18",
        "county_fips": "18119",
        "population": 21321,
        "land_area_sq_mi": 385.295,
        "centroid": [
          39.314578,
          -86.798175
        ],
        "county_seat": null
      },
      {
        "county_name": "Parke County",
        "state_fips": "18",
        "county_fips": "18121",
        "population": 16156,
        "land_area_sq_mi": 444.725,
        "centroid": [
          39.757908,
          -87.225163
        ],
        "county_seat": null
      },
      {
        "county_name": "Perry County",
        "state_fips": "18",
        "county_fips": "18123",
        "population": 19170,
        "land_area_sq_mi": 381.74,
        "centroid": [
          38.008616,
          -86.705505
        ],
        "county_seat": null
      },
      {
        "county_name": "Pike County",
        "state_fips": "18",
        "county_fips": "18125",
        "population": 12250,
        "land_area_sq_mi": 334.351,
        "centroid": [
          38.427019,
          -87.233088
        ],
        "county_seat": null
      },
      {
        "county_name": "Porter County",
        "state_fips": "18",
        "county_fips": "18127",
        "population": 173215,
        "land_area_sq_mi": 418.113,
        "centroid": [
          41.513979,
          -87.104333
        ],
        "county_seat": null
      },
      {
        "county_name": "Posey County",
        "state_fips": "18",
        "county_fips": "18129",
        "population": 25222,
        "land_area_sq_mi": 409.385,
        "centroid": [
          38.012717,
          -87.819868
        ],
        "county_seat": null
      },
      {
        "county_name": "Pulaski County",
        "state_fips": "18",
        "county_fips": "18131",
        "population": 12514,
        "land_area_sq_mi": 433.678,
        "centroid": [
          41.051366,
          -86.684796
        ],
        "county_seat": null
      },
      {
        "county_name": "Putnam County",
        "state_fips": "18",
        "county_fips": "18133",
        "population": 36726,
        "land_area_sq_mi": 480.536,
        "centroid": [
          39.646449,
          -86.834304
        ],
        "county_seat": null
      },
      {
        "county_name": "Randolph County",
        "state_fips": "18",
        "county_fips": "18135",
        "population": 24502,
        "land_area_sq_mi": 452.379,
        "centroid": [
          40.169491,
          -84.996903
        ],
        "county_seat": null
      },
      {
        "county_name": "Ripley County",
        "state_fips": "18",
        "county_fips": "18137",
        "population": 28995,
        "land_area_sq_mi": 446.431,
        "centroid": [
          39.160663,
          -85.219308
        ],
        "county_seat": null
      },
      {
        "county_name": "Rush County",
        "state_fips": "18",
        "county_fips": "18139",
        "population": 16752,
        "land_area_sq_mi": 408.137,
        "centroid": [
          39.62209,
          -85.475672
        ],
        "county_seat": null
      },
      {
        "county_name": "St. Joseph County",
        "state_fips": "18",
        "county_fips": "18141",
        "population": 272912,
        "land_area_sq_mi": 457.781,
        "centroid": [
          41.67642,
          -86.227079
        ],
        "county_seat": null
      },
      {
        "county_name": "Scott County",
        "state_fips": "18",
        "county_fips": "18143",
        "population": 24384,
        "land_area_sq_mi": 190.403,
        "centroid": [
          38.697942,
          -85.764092
        ],
        "county_seat": null
      },
      {
        "county_name": "Shelby County",
        "state_fips": "18",
        "county_fips": "18145",
        "population": 45055,
        "land_area_sq_mi": 411.136,
        "centroid": [
          39.535011,
          -85.790065
        ],
        "county_seat": null
      },
      {
        "county_name": "Spencer County",
        "state_fips": "18",
        "county_fips": "18147",
        "population": 19810,
        "land_area_sq_mi": 396.888,
        "centroid": [
          38.019216,
          -87.009078
        ],
        "county_seat": null
      },
      {
        "county_name": "Starke County",
        "state_fips": "18",
        "county_fips": "18149",
        "population": 23371,
        "land_area_sq_mi": 309.144,
        "centroid": [
          41.281734,
          -86.632742
        ],
        "county_seat": null
      },
      {
        "county_name": "Steuben County",
        "state_fips": "18",
        "county_fips": "18151",
        "population": 34435,
        "land_area_sq_mi": 308.782,
        "centroid": [
          41.650003,
          -85.010961
        ],
        "county_seat": null
      },
      {
        "county_name": "Sullivan County",
        "state_fips": "18",
        "county_fips": "18153",
        "population": 20817,
        "land_area_sq_mi": 447.196,
        "centroid": [
          39.103793,
          -87.393185
        ],
        "county_seat": null
      },
      {
        "county_name": "Switzerland County",
        "state_fips": "18",
        "county_fips": "18155",
        "population": 9737,
        "land_area_sq_mi": 220.668,
        "centroid": [
          38.816976,
          -85.023673
        ],
        "county_seat": null
      },
      {
        "county_name": "Tippecanoe County",
        "state_fips": "18",
        "county_fips": "18157",
        "population": 186251,
        "land_area_sq_mi": 498.898,
        "centroid": [
          40.418699,
          -86.886959
        ],
        "county_seat": null
      },
      {
        "county_name": "Tipton County",
        "state_fips": "18",
        "county_fips": "18159",
        "population": 15359,
        "land_area_sq_mi": 260.541,
        "centroid": [
          40.307543,
          -86.051278
        ],
        "county_seat": null
      },
      {
        "county_name": "Union County",
        "state_fips": "18",
        "county_fips": "18161",
        "population": 7087,
        "land_area_sq_mi": 161.191,
        "centroid": [
          39.618364,
          -84.919464
        ],
        "county_seat": null
      },
      {
        "county_name": "Vanderburgh County",
        "state_fips": "18",
        "county_fips": "18163",
        "population": 180136,
        "land_area_sq_mi": 233.402,
        "centroid": [
          37.998233,
          -87.549603
        ],
        "county_seat": null
      },
      {
        "county_name": "Vermillion County",
        "state_fips": "18",
        "county_fips": "18165",
        "population": 15439,
        "land_area_sq_mi": 256.894,
        "centroid": [
          39.759924,
          -87.439022
        ],
        "county_seat": null
      },
      {
        "county_name": "Vigo County",
        "state_fips": "18",
        "county_fips": "18167",
        "population": 106153,
        "land_area_sq_mi": 403.631,
        "centroid": [
          39.460456,
          -87.386916
        ],
        "county_seat": null
      },
      {
        "county_name": "Wabash County",
        "state_fips": "18",
        "county_fips": "18169",
        "population": 30976,
        "land_area_sq_mi": 412.539,
        "centroid": [
          40.855768,
          -85.80421
        ],
        "county_seat": null
      },
      {
        "county_name": "Warren County",
        "state_fips": "18",
        "county_fips": "18171",
        "population": 8440,
        "land_area_sq_mi": 364.69,
        "centroid": [
          40.312721,
          -87.325412
        ],
        "county_seat": null
      },
      {
        "county_name": "Warrick County",
        "state_fips": "18",
        "county_fips": "18173",
        "population": 63898,
        "land_area_sq_mi": 384.63,
        "centroid": [
          38.011051,
          -87.355616
        ],
        "county_seat": null
      },
      {
        "county_name": "Washington County",
        "state_fips": "18",
        "county_fips": "18175",
        "population": 28182,
        "land_area_sq_mi": 513.689,
        "centroid": [
          38.573362,
          -86.084553
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "18",
        "county_fips": "18177",
        "population": 66553,
        "land_area_sq_mi": 401.755,
        "centroid": [
          39.843304,
          -84.948672
        ],
        "county_seat": null
      },
      {
        "county_name": "Wells County",
        "state_fips": "18",
        "county_fips": "18179",
        "population": 28180,
        "land_area_sq_mi": 368.087,
        "centroid": [
          40.770773,
          -85.192988
        ],
        "county_seat": null
      },
      {
        "county_name": "White County",
        "state_fips": "18",
        "county_fips": "18181",
        "population": 24688,
        "land_area_sq_mi": 505.14,
        "centroid": [
          40.753581,
          -86.809953
        ],
        "county_seat": null
      },
      {
        "county_name": "Whitley County",
        "state_fips": "18",
        "county_fips": "18183",
        "population": 34191,
        "land_area_sq_mi": 335.622,
        "centroid": [
          41.16305,
          -85.478007
        ],
        "county_seat": null
      }
    ]
