# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Barbour County",
        "state_fips": "54",
        "county_fips": "54001",
        "population": 15465,
        "land_area_sq_mi": 341.059,
        "centroid": [
          39.110076,
          -80.004391
        ],
        "county_seat": null
      },
      {
        "county_name": "Berkeley County",
        "state_fips": "54",
        "county_fips": "54003",
        "population": 122076,
        "land_area_sq_mi": 321.149,
        "centroid": [
          39.458843,
          -77.98117
        ],
        "county_seat": null
      },
      {
        "county_name": "Boone County",
        "state_fips": "54",
        "county_fips": "54005",
        "population": 21809,
        "land_area_sq_mi": 502.37,
        "centroid": [
          38.05644,
          -81.757507
        ],
        "county_seat": null
      },
      {
        "county_name": "Braxton County",
        "state_fips": "54",
        "county_fips": "54007",
        "population": 12447,
        "land_area_sq_mi": 510.735,
        "centroid": [
          38.691905,
          -80.723592
        ],
        "county_seat": null
      },
      {
        "county_name": "Brooke County",
        "state_fips": "54",
        "county_fips": "54009",
        "population": 22559,
        "land_area_sq_mi": 89.196,
        "centroid": [
          40.309452,
          -80.585926
        ],
        "county_seat": null
      },
      {
        "county_name": "Cabell County",
        "state_fips": "54",
        "county_fips": "54011",
        "population": 94350,
        "land_area_sq_mi": 281.024,
        "centroid": [
          38.413593,
          -82.335182
        ],
        "county_seat": null
      },
      {
        "county_name": "Calhoun County",
        "state_fips": "54",
        "county_fips": "54013",
        "population": 6229,
        "land_area_sq_mi": 279.263,
        "centroid": [
          38.852608,
          -81.104396
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "54",
        "county_fips": "54015",
        "population": 8051,
        "land_area_sq_mi": 341.939,
        "centroid": [
          38.471941,
          -81.09932
        ],
        "county_seat": null
      },
      {
        "county_name": "Doddridge County",
        "state_fips": "54",
        "county_fips": "54017",
        "population": 7808,
        "land_area_sq_mi": 319.723,
        "centroid": [
          39.285261,
          -80.721305
        ],
        "county_seat": null
      },
      {
        "county_name": "Fayette County",
        "state_fips": "54",
        "county_fips": "54019",
        "population": 40488,
        "land_area_sq_mi": 661.957,
        "centroid": [
          38.032534,
          -81.129034
        ],
        "county_seat": null
      },
      {
        "county_name": "Gilmer County",
        "state_fips": "54",
        "county_fips": "54021",
        "population": 7408,
        "land_area_sq_mi": 338.503,
        "centroid": [
          38.923122,
          -80.826516
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "54",
        "county_fips": "54023",
        "population": 10976,
        "land_area_sq_mi": 477.372,
        "centroid": [
          39.058737,
          -79.16103
        ],
        "county_seat": null
      },
      {
        "county_name": "Greenbrier County",
        "state_fips": "54",
        "county_fips": "54025",
        "population": 32977,
        "land_area_sq_mi": 1019.819,
        "centroid": [
          37.854476,
          -80.490891
        ],
        "county_seat": null
      },
      {
        "county_name": "Hampshire County",
        "state_fips": "54",
        "county_fips": "54027",
        "population": 23093,
        "land_area_sq_mi": 640.402,
        "centroid": [
          39.329412,
          -78.610531
        ],
        "county_seat": null
      },
      {
        "county_name": "Hancock County",
        "state_fips": "54",
        "county_fips": "54029",
        "population": 29095,
        "land_area_sq_mi": 82.61,
        "centroid": [
          40.477168,
          -80.568865
        ],
        "county_seat": null
      },
      {
        "county_name": "Hardy County",
        "state_fips": "54",
        "county_fips": "54031",
        "population": 14299,
        "land_area_sq_mi": 582.315,
        "centroid": [
          39.039184,
          -78.88137
        ],
        "county_seat": null
      },
      {
        "county_name": "Harrison County",
        "state_fips": "54",
        "county_fips": "54033",
        "population": 65921,
        "land_area_sq_mi": 416.01,
        "centroid": [
          39.287852,
          -80.338827
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "54",
        "county_fips": "54035",
        "population": 27791,
        "land_area_sq_mi": 464.36,
        "centroid": [
          38.83984,
          -81.713096
        ],
        "county_seat": null
      },
      {
        "county_name": "Jefferson County",
        "state_fips": "54",
        "county_fips": "54037",
        "population": 57701,
        "land_area_sq_mi": 209.296,
        "centroid": [
          39.313836,
          -77.847631
        ],
        "county_seat": null
      },
      {
        "county_name": "Kanawha County",
        "state_fips": "54",
        "county_fips": "54039",
        "population": 180745,
        "land_area_sq_mi": 901.737,
        "centroid": [
          38.363316,
          -81.658246
        ],
        "county_seat": null
      },
      {
        "county_name": "Lewis County",
        "state_fips": "54",
        "county_fips": "54041",
        "population": 17033,
        "land_area_sq_mi": 386.93,
        "centroid": [
          39.034218,
          -80.4678
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "54",
        "county_fips": "54043",
        "population": 20463,
        "land_area_sq_mi": 437.093,
        "centroid": [
          38.201811,
          -82.066388
        ],
        "county_seat": null
      },
      {
        "county_name": "Logan County",
        "state_fips": "54",
        "county_fips": "54045",
        "population": 32567,
        "land_area_sq_mi": 452.904,
        "centroid": [
          37.856159,
          -81.972493
        ],
        "county_seat": null
      },
      {
        "county_name": "McDowell County",
        "state_fips": "54",
        "county_fips": "54047",
        "population": 19111,
        "land_area_sq_mi": 533.458,
        "centroid": [
          37.396396,
          -81.656256
        ],
        "county_seat": null
      },
      {
        "county_name": "Marion County",
        "state_fips": "54",
        "county_fips": "54049",
        "population": 56205,
        "land_area_sq_mi": 308.785,
        "centroid": [
          39.484338,
          -80.178811
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "54",
        "county_fips": "54051",
        "population": 30591,
        "land_area_sq_mi": 305.431,
        "centroid": [
          39.928298,
          -80.704828
        ],
        "county_seat": null
      },
      {
        "county_name": "Mason County",
        "state_fips": "54",
        "county_fips": "54053",
        "population": 25453,
        "land_area_sq_mi": 430.768,
        "centroid": [
          38.827547,
          -82.058308
        ],
        "county_seat": null
      },
      {
        "county_name": "Mercer County",
        "state_fips": "54",
        "county_fips": "54055",
        "population": 59664,
        "land_area_sq_mi": 418.962,
        "centroid": [
          37.352588,
          -81.138228
        ],
        "county_seat": null
      },
      {
        "county_name": "Mineral County",
        "state_fips": "54",
        "county_fips": "54057",
        "population": 26938,
        "land_area_sq_mi": 327.882,
        "centroid": [
          39.46477,
          -78.909653
        ],
        "county_seat": null
      },
      {
        "county_name": "Mingo County",
        "state_fips": "54",
        "county_fips": "54059",
        "population": 23568,
        "land_area_sq_mi": 423.113,
        "centroid": [
          37.704029,
          -82.153272
        ],
        "county_seat": null
      },
      {
        "county_name": "Monongalia County",
        "state_fips": "54",
        "county_fips": "54061",
        "population": 105822,
        "land_area_sq_mi": 360.093,
        "centroid": [
          39.636527,
          -79.956836
        ],
        "county_seat": null
      },
      {
        "county_name": "Monroe County",
        "state_fips": "54",
        "county_fips": "54063",
        "population": 12376,
        "land_area_sq_mi": 472.754,
        "centroid": [
          37.524766,
          -80.641965
        ],
        "county_seat": null
      },
      {
        "county_name": "Morgan County",
        "state_fips": "54",
        "county_fips": "54065",
        "population": 17063,
        "land_area_sq_mi": 229.073,
        "centroid": [
          39.580983,
          -78.223029
        ],
        "county_seat": null
      },
      {
        "county_name": "Nicholas County",
        "state_fips": "54",
        "county_fips": "54067",
        "population": 24604,
        "land_area_sq_mi": 646.842,
        "centroid": [
          38.278413,
          -80.77232
        ],
        "county_seat": null
      },
      {
        "county_name": "Ohio County",
        "state_fips": "54",
        "county_fips": "54069",
        "population": 42425,
        "land_area_sq_mi": 105.831,
        "centroid": [
          40.078539,
          -80.672291
        ],
        "county_seat": null
      },
      {
        "county_name": "Pendleton County",
        "state_fips": "54",
        "county_fips": "54071",
        "population": 6143,
        "land_area_sq_mi": 696.05,
        "centroid": [
          38.672348,
          -79.337977
        ],
        "county_seat": null
      },
      {
        "county_name": "Pleasants County",
        "state_fips": "54",
        "county_fips": "54073",
        "population": 7653,
        "land_area_sq_mi": 130.119,
        "centroid": [
          39.383391,
          -81.192758
        ],
        "county_seat": null
      },
      {
        "county_name": "Pocahontas County",
        "state_fips": "54",
        "county_fips": "54075",
        "population": 7869,
        "land_area_sq_mi": 940.239,
        "centroid": [
          38.286975,
          -80.021443
        ],
        "county_seat": null
      },
      {
        "county_name": "Preston County",
        "state_fips": "54",
        "county_fips": "54077",
        "population": 34216,
        "land_area_sq_mi": 648.814,
        "centroid": [
          39.50551,
          -79.669791
        ],
        "county_seat": null
      },
      {
        "county_name": "Putnam County",
        "state_fips": "54",
        "county_fips": "54079",
        "population": 57440,
        "land_area_sq_mi": 345.677,
        "centroid": [
          38.474402,
          -81.929372
        ],
        "county_seat": null
      },
      {
        "county_name": "Raleigh County",
        "state_fips": "54",
        "county_fips": "54081",
        "population": 74591,
        "land_area_sq_mi": 604.968,
        "centroid": [
          37.77054,
          -81.200033
        ],
        "county_seat": null
      },
      {
        "county_name": "Randolph County",
        "state_fips": "54",
        "county_fips": "54083",
        "population": 27932,
        "land_area_sq_mi": 1039.7,
        "centroid": [
          38.870878,
          -79.872452
        ],
        "county_seat": null
      },
      {
        "county_name": "Ritchie County",
        "state_fips": "54",
        "county_fips": "54085",
        "population": 8444,
        "land_area_sq_mi": 451.99,
        "centroid": [
          39.217711,
          -81.041532
        ],
        "county_seat": null
      },
      {
        "county_name": "Roane County",
        "state_fips": "54",
        "county_fips": "54087",
        "population": 14028,
        "land_area_sq_mi": 483.563,
        "centroid": [
          38.728527,
          -81.345745
        ],
        "county_seat": null
      },
      {
        "county_name": "Summers County",
        "state_fips": "54",
        "county_fips": "54089",
        "population": 11959,
        "land_area_sq_mi": 360.588,
        "centroid": [
          37.665228,
          -80.849424
        ],
        "county_seat": null
      },
      {
        "county_name": "Taylor County",
        "state_fips": "54",
        "county_fips": "54091",
        "population": 16705,
        "land_area_sq_mi": 172.771,
        "centroid": [
          39.33862,
          -80.066874
        ],
        "county_seat": null
      },
      {
        "county_name": "Tucker County",
        "state_fips": "54",
        "county_fips": "54093",
        "population": 6762,
        "land_area_sq_mi": 419.042,
        "centroid": [
          39.110662,
          -79.602086
        ],
        "county_seat": null
      },
      {
        "county_name": "Tyler County",
        "state_fips": "54",
        "county_fips": "54095",
        "population": 8313,
        "land_area_sq_mi": 256.302,
        "centroid": [
          39.51456,
          -80.930534
        ],
        "county_seat": null
      },
      {
        "county_name": "Upshur County",
        "state_fips": "54",
        "county_fips": "54097",
        "population": 23816,
        "land_area_sq_mi": 354.638,
        "centroid": [
          38.954081,
          -80.228505
        ],
        "county_seat": null
      },
      {
        "county_name": "Wayne County",
        "state_fips": "54",
        "county_fips": "54099",
        "population": 38982,
        "land_area_sq_mi": 506.005,
        "centroid": [
          38.267338,
          -82.494193
        ],
        "county_seat": null
      },
      {
        "county_name": "Webster County",
        "state_fips": "54",
        "county_fips": "54101",
        "population": 8378,
        "land_area_sq_mi": 553.47,
        "centroid": [
          38.469754,
          -80.476189
        ],
        "county_seat": null
      },
      {
        "county_name": "Wetzel County",
        "state_fips": "54",
        "county_fips": "54103",
        "population": 14442,
        "land_area_sq_mi": 358.067,
        "centroid": [
          39.630012,
          -80.768843
        ],
        "county_seat": null
      },
      {
        "county_name": "Wirt County",
        "state_fips": "54",
        "county_fips": "54105",
        "population": 5194,
        "land_area_sq_mi": 232.511,
        "centroid": [
          39.05422,
          -81.394474
        ],
        "county_seat": null
      },
      {
        "county_name": "Wood County",
        "state_fips": "54",
        "county_fips": "54107",
        "population": 84296,
        "land_area_sq_mi": 366.5,
        "centroid": [
          39.266981,
          -81.530587
        ],
        "county_seat": null
      },
      {
        "county_name": "Wyoming County",
        "state_fips": "54",
        "county_fips": "54109",
        "population": 21382,
        "land_area_sq_mi": 499.47,
        "centroid": [
          37.628585,
          -81.567271
        ],
        "county_seat": null
      }
    ]
