#!/usr/bin/env python3
"""
build_county_data.py

• Reads:
    CenPop2020_Mean_CO.txt          (population, centroid)
    2024_Gaz_counties_national.txt  (land area, water area, USPS code, etc.)

• Produces:
    states/<State>/counties.py  – one file per state containing:
        counties = [{county_name, state_fips, county_fips, population,
                     land_area_sq_mi, centroid}, …]

Add more attributes later (e.g., county seat) by extending the 'record'
dict before writing.

Run once, then commit the generated files to GitHub.
"""

from pathlib import Path
import pandas as pd
import json
import textwrap
from typing import Any

ROOT       = Path(__file__).resolve().parent
STATE_DIR  = ROOT / "states"

CENPOP_TXT = ROOT / "CenPop2020_Mean_CO.txt"
GAZ_TXT    = ROOT / "2024_Gaz_counties_national.txt"

# ---------------------------------------------------------------------
# 1.  Load the two source tables
# ---------------------------------------------------------------------
cenpop = pd.read_csv(
    CENPOP_TXT,
    names=["STATEFP", "COUNTYFP", "COUNTYNAME", "STNAME",
           "POPULATION", "LATITUDE", "LONGITUDE"],
    dtype=str,
    skiprows=1          # <─ add this
)
cenpop["POPULATION"] = cenpop["POPULATION"].astype(int)
cenpop["GEOID"] = cenpop["STATEFP"].str.zfill(2) + cenpop["COUNTYFP"].str.zfill(3)

print("Loading Gazetteer file …")
gaz = pd.read_csv(
    GAZ_TXT,
    sep="\t",
    dtype=str
)
gaz["ALAND_SQMI"] = gaz["ALAND_SQMI"].astype(float)

# The Gazetteer GEOID is already 5-digit county FIPS
merged = cenpop.merge(
    gaz[["GEOID", "USPS", "ALAND_SQMI"]],
    on="GEOID",
    how="left",
    validate="one_to_one"
)

# ---------------------------------------------------------------------
# 2.  Build the counties_data dict  {state_name: [county_dicts]}
# ---------------------------------------------------------------------
counties_data: dict[str, list[dict[str, Any]]] = {}

for _, row in merged.iterrows():
    state_name = row["STNAME"]
    county_dict = {
        "county_name": f"{row['COUNTYNAME']} County",
        "state_fips": row["STATEFP"].zfill(2),
        "county_fips": row["GEOID"],
        "population":  int(row["POPULATION"]),
        "land_area_sq_mi": float(row["ALAND_SQMI"]) if pd.notna(row["ALAND_SQMI"]) else None,
        "centroid":  (float(row["LATITUDE"]), float(row["LONGITUDE"])),
        "county_seat": None,            # fill later if you want
    }
    counties_data.setdefault(state_name, []).append(county_dict)

print(f"Built dictionary with {len(counties_data)} states "
      f"and {sum(len(v) for v in counties_data.values())} counties.")

# ---------------------------------------------------------------------
# 3.  Writer – one counties.py per state
# ---------------------------------------------------------------------
def write_python(state: str, county_list: list[dict[str, Any]]) -> None:
    folder = STATE_DIR / state
    folder.mkdir(parents=True, exist_ok=True)     # make sure directory exists
    
    target = folder / "counties.py"
    body = textwrap.indent(json.dumps(county_list, indent=2), " " * 4)
    target.write_text(
        "# Auto-generated by build_county_data.py\n"
        f"counties = {body}\n",
        encoding="utf-8"
    )
    print(f"✓ {state:<20} → {target.relative_to(ROOT)} "
          f"({len(county_list):3} counties)")

for state, clist in counties_data.items():
    write_python(state, clist)

print("Done.")