# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Kent County",
        "state_fips": "10",
        "county_fips": "10001",
        "population": 181851,
        "land_area_sq_mi": 586.061,
        "centroid": [
          39.127081,
          -75.55913
        ],
        "county_seat": null
      },
      {
        "county_name": "New Castle County",
        "state_fips": "10",
        "county_fips": "10003",
        "population": 570719,
        "land_area_sq_mi": 426.338,
        "centroid": [
          39.678852,
          -75.63529
        ],
        "county_seat": null
      },
      {
        "county_name": "Sussex County",
        "state_fips": "10",
        "county_fips": "10005",
        "population": 237378,
        "land_area_sq_mi": 936.14,
        "centroid": [
          38.661794,
          -75.331473
        ],
        "county_seat": null
      }
    ]
