# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Adams County",
        "state_fips": "38",
        "county_fips": "38001",
        "population": 2200,
        "land_area_sq_mi": 987.547,
        "centroid": [
          46.035876,
          -102.621818
        ],
        "county_seat": null
      },
      {
        "county_name": "Barnes County",
        "state_fips": "38",
        "county_fips": "38003",
        "population": 10853,
        "land_area_sq_mi": 1491.559,
        "centroid": [
          46.926891,
          -98.030382
        ],
        "county_seat": null
      },
      {
        "county_name": "Benson County",
        "state_fips": "38",
        "county_fips": "38005",
        "population": 5964,
        "land_area_sq_mi": 1388.555,
        "centroid": [
          48.022233,
          -99.148961
        ],
        "county_seat": null
      },
      {
        "county_name": "Billings County",
        "state_fips": "38",
        "county_fips": "38007",
        "population": 945,
        "land_area_sq_mi": 1148.488,
        "centroid": [
          47.00341,
          -103.306329
        ],
        "county_seat": null
      },
      {
        "county_name": "Bottineau County",
        "state_fips": "38",
        "county_fips": "38009",
        "population": 6379,
        "land_area_sq_mi": 1668.858,
        "centroid": [
          48.818996,
          -100.635057
        ],
        "county_seat": null
      },
      {
        "county_name": "Bowman County",
        "state_fips": "38",
        "county_fips": "38011",
        "population": 2993,
        "land_area_sq_mi": 1161.809,
        "centroid": [
          46.17101,
          -103.389737
        ],
        "county_seat": null
      },
      {
        "county_name": "Burke County",
        "state_fips": "38",
        "county_fips": "38013",
        "population": 2201,
        "land_area_sq_mi": 1103.619,
        "centroid": [
          48.760535,
          -102.539257
        ],
        "county_seat": null
      },
      {
        "county_name": "Burleigh County",
        "state_fips": "38",
        "county_fips": "38015",
        "population": 98458,
        "land_area_sq_mi": 1632.694,
        "centroid": [
          46.823125,
          -100.761269
        ],
        "county_seat": null
      },
      {
        "county_name": "Cass County",
        "state_fips": "38",
        "county_fips": "38017",
        "population": 184525,
        "land_area_sq_mi": 1764.935,
        "centroid": [
          46.853248,
          -96.866085
        ],
        "county_seat": null
      },
      {
        "county_name": "Cavalier County",
        "state_fips": "38",
        "county_fips": "38019",
        "population": 3704,
        "land_area_sq_mi": 1489.125,
        "centroid": [
          48.756287,
          -98.408736
        ],
        "county_seat": null
      },
      {
        "county_name": "Dickey County",
        "state_fips": "38",
        "county_fips": "38021",
        "population": 4999,
        "land_area_sq_mi": 1131.493,
        "centroid": [
          46.090319,
          -98.316828
        ],
        "county_seat": null
      },
      {
        "county_name": "Divide County",
        "state_fips": "38",
        "county_fips": "38023",
        "population": 2195,
        "land_area_sq_mi": 1261.13,
        "centroid": [
          48.873168,
          -103.340573
        ],
        "county_seat": null
      },
      {
        "county_name": "Dunn County",
        "state_fips": "38",
        "county_fips": "38025",
        "population": 4095,
        "land_area_sq_mi": 2008.492,
        "centroid": [
          47.337232,
          -102.638185
        ],
        "county_seat": null
      },
      {
        "county_name": "Eddy County",
        "state_fips": "38",
        "county_fips": "38027",
        "population": 2347,
        "land_area_sq_mi": 630.239,
        "centroid": [
          47.705809,
          -99.056923
        ],
        "county_seat": null
      },
      {
        "county_name": "Emmons County",
        "state_fips": "38",
        "county_fips": "38029",
        "population": 3301,
        "land_area_sq_mi": 1508.401,
        "centroid": [
          46.26697,
          -100.221494
        ],
        "county_seat": null
      },
      {
        "county_name": "Foster County",
        "state_fips": "38",
        "county_fips": "38031",
        "population": 3397,
        "land_area_sq_mi": 634.08,
        "centroid": [
          47.460553,
          -99.032312
        ],
        "county_seat": null
      },
      {
        "county_name": "Golden Valley County",
        "state_fips": "38",
        "county_fips": "38033",
        "population": 1736,
        "land_area_sq_mi": 1000.885,
        "centroid": [
          46.891037,
          -103.959283
        ],
        "county_seat": null
      },
      {
        "county_name": "Grand Forks County",
        "state_fips": "38",
        "county_fips": "38035",
        "population": 73170,
        "land_area_sq_mi": 1436.216,
        "centroid": [
          47.904107,
          -97.114067
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "38",
        "county_fips": "38037",
        "population": 2301,
        "land_area_sq_mi": 1659.233,
        "centroid": [
          46.39358,
          -101.709905
        ],
        "county_seat": null
      },
      {
        "county_name": "Griggs County",
        "state_fips": "38",
        "county_fips": "38039",
        "population": 2306,
        "land_area_sq_mi": 708.685,
        "centroid": [
          47.45152,
          -98.184378
        ],
        "county_seat": null
      },
      {
        "county_name": "Hettinger County",
        "state_fips": "38",
        "county_fips": "38041",
        "population": 2489,
        "land_area_sq_mi": 1132.239,
        "centroid": [
          46.452752,
          -102.563748
        ],
        "county_seat": null
      },
      {
        "county_name": "Kidder County",
        "state_fips": "38",
        "county_fips": "38043",
        "population": 2394,
        "land_area_sq_mi": 1351.062,
        "centroid": [
          46.913782,
          -99.803211
        ],
        "county_seat": null
      },
      {
        "county_name": "LaMoure County",
        "state_fips": "38",
        "county_fips": "38045",
        "population": 4093,
        "land_area_sq_mi": 1146.005,
        "centroid": [
          46.405038,
          -98.531088
        ],
        "county_seat": null
      },
      {
        "county_name": "Logan County",
        "state_fips": "38",
        "county_fips": "38047",
        "population": 1876,
        "land_area_sq_mi": 992.599,
        "centroid": [
          46.497157,
          -99.553732
        ],
        "county_seat": null
      },
      {
        "county_name": "McHenry County",
        "state_fips": "38",
        "county_fips": "38049",
        "population": 5345,
        "land_area_sq_mi": 1873.942,
        "centroid": [
          48.179669,
          -100.700743
        ],
        "county_seat": null
      },
      {
        "county_name": "McIntosh County",
        "state_fips": "38",
        "county_fips": "38051",
        "population": 2530,
        "land_area_sq_mi": 974.563,
        "centroid": [
          46.146072,
          -99.492968
        ],
        "county_seat": null
      },
      {
        "county_name": "McKenzie County",
        "state_fips": "38",
        "county_fips": "38053",
        "population": 14704,
        "land_area_sq_mi": 2760.133,
        "centroid": [
          47.815379,
          -103.249949
        ],
        "county_seat": null
      },
      {
        "county_name": "McLean County",
        "state_fips": "38",
        "county_fips": "38055",
        "population": 9771,
        "land_area_sq_mi": 2110.272,
        "centroid": [
          47.524037,
          -101.227016
        ],
        "county_seat": null
      },
      {
        "county_name": "Mercer County",
        "state_fips": "38",
        "county_fips": "38057",
        "population": 8350,
        "land_area_sq_mi": 1042.781,
        "centroid": [
          47.300979,
          -101.712049
        ],
        "county_seat": null
      },
      {
        "county_name": "Morton County",
        "state_fips": "38",
        "county_fips": "38059",
        "population": 33291,
        "land_area_sq_mi": 1925.888,
        "centroid": [
          46.82084,
          -100.987436
        ],
        "county_seat": null
      },
      {
        "county_name": "Mountrail County",
        "state_fips": "38",
        "county_fips": "38061",
        "population": 9809,
        "land_area_sq_mi": 1825.163,
        "centroid": [
          48.134813,
          -102.385064
        ],
        "county_seat": null
      },
      {
        "county_name": "Nelson County",
        "state_fips": "38",
        "county_fips": "38063",
        "population": 3015,
        "land_area_sq_mi": 981.815,
        "centroid": [
          47.914125,
          -98.211495
        ],
        "county_seat": null
      },
      {
        "county_name": "Oliver County",
        "state_fips": "38",
        "county_fips": "38065",
        "population": 1877,
        "land_area_sq_mi": 722.404,
        "centroid": [
          47.120347,
          -101.30705
        ],
        "county_seat": null
      },
      {
        "county_name": "Pembina County",
        "state_fips": "38",
        "county_fips": "38067",
        "population": 6844,
        "land_area_sq_mi": 1118.535,
        "centroid": [
          48.786353,
          -97.583136
        ],
        "county_seat": null
      },
      {
        "county_name": "Pierce County",
        "state_fips": "38",
        "county_fips": "38069",
        "population": 3990,
        "land_area_sq_mi": 1018.285,
        "centroid": [
          48.327982,
          -99.985438
        ],
        "county_seat": null
      },
      {
        "county_name": "Ramsey County",
        "state_fips": "38",
        "county_fips": "38071",
        "population": 11605,
        "land_area_sq_mi": 1185.367,
        "centroid": [
          48.129972,
          -98.834617
        ],
        "county_seat": null
      },
      {
        "county_name": "Ransom County",
        "state_fips": "38",
        "county_fips": "38073",
        "population": 5703,
        "land_area_sq_mi": 862.472,
        "centroid": [
          46.473332,
          -97.654107
        ],
        "county_seat": null
      },
      {
        "county_name": "Renville County",
        "state_fips": "38",
        "county_fips": "38075",
        "population": 2282,
        "land_area_sq_mi": 877.244,
        "centroid": [
          48.71223,
          -101.513019
        ],
        "county_seat": null
      },
      {
        "county_name": "Richland County",
        "state_fips": "38",
        "county_fips": "38077",
        "population": 16529,
        "land_area_sq_mi": 1435.674,
        "centroid": [
          46.265439,
          -96.76508
        ],
        "county_seat": null
      },
      {
        "county_name": "Rolette County",
        "state_fips": "38",
        "county_fips": "38079",
        "population": 12187,
        "land_area_sq_mi": 903.042,
        "centroid": [
          48.837585,
          -99.815657
        ],
        "county_seat": null
      },
      {
        "county_name": "Sargent County",
        "state_fips": "38",
        "county_fips": "38081",
        "population": 3862,
        "land_area_sq_mi": 858.483,
        "centroid": [
          46.166223,
          -97.587859
        ],
        "county_seat": null
      },
      {
        "county_name": "Sheridan County",
        "state_fips": "38",
        "county_fips": "38083",
        "population": 1265,
        "land_area_sq_mi": 972.226,
        "centroid": [
          47.581765,
          -100.333635
        ],
        "county_seat": null
      },
      {
        "county_name": "Sioux County",
        "state_fips": "38",
        "county_fips": "38085",
        "population": 3898,
        "land_area_sq_mi": 1094.052,
        "centroid": [
          46.166774,
          -100.727458
        ],
        "county_seat": null
      },
      {
        "county_name": "Slope County",
        "state_fips": "38",
        "county_fips": "38087",
        "population": 706,
        "land_area_sq_mi": 1215.264,
        "centroid": [
          46.418394,
          -103.416249
        ],
        "county_seat": null
      },
      {
        "county_name": "Stark County",
        "state_fips": "38",
        "county_fips": "38089",
        "population": 33646,
        "land_area_sq_mi": 1334.913,
        "centroid": [
          46.883324,
          -102.784958
        ],
        "county_seat": null
      },
      {
        "county_name": "Steele County",
        "state_fips": "38",
        "county_fips": "38091",
        "population": 1798,
        "land_area_sq_mi": 712.143,
        "centroid": [
          47.459852,
          -97.75048
        ],
        "county_seat": null
      },
      {
        "county_name": "Stutsman County",
        "state_fips": "38",
        "county_fips": "38093",
        "population": 21593,
        "land_area_sq_mi": 2221.904,
        "centroid": [
          46.917429,
          -98.73948
        ],
        "county_seat": null
      },
      {
        "county_name": "Towner County",
        "state_fips": "38",
        "county_fips": "38095",
        "population": 2162,
        "land_area_sq_mi": 1025.113,
        "centroid": [
          48.575593,
          -99.232995
        ],
        "county_seat": null
      },
      {
        "county_name": "Traill County",
        "state_fips": "38",
        "county_fips": "38097",
        "population": 7997,
        "land_area_sq_mi": 861.871,
        "centroid": [
          47.489414,
          -97.221419
        ],
        "county_seat": null
      },
      {
        "county_name": "Walsh County",
        "state_fips": "38",
        "county_fips": "38099",
        "population": 10563,
        "land_area_sq_mi": 1281.607,
        "centroid": [
          48.392384,
          -97.55615
        ],
        "county_seat": null
      },
      {
        "county_name": "Ward County",
        "state_fips": "38",
        "county_fips": "38101",
        "population": 69919,
        "land_area_sq_mi": 2013.029,
        "centroid": [
          48.251003,
          -101.324255
        ],
        "county_seat": null
      },
      {
        "county_name": "Wells County",
        "state_fips": "38",
        "county_fips": "38103",
        "population": 3982,
        "land_area_sq_mi": 1270.533,
        "centroid": [
          47.673531,
          -99.776162
        ],
        "county_seat": null
      },
      {
        "county_name": "Williams County",
        "state_fips": "38",
        "county_fips": "38105",
        "population": 40950,
        "land_area_sq_mi": 2077.6,
        "centroid": [
          48.198161,
          -103.581969
        ],
        "county_seat": null
      }
    ]
