# Auto-generated by build_county_data.py
counties =     [
      {
        "county_name": "Aurora County",
        "state_fips": "46",
        "county_fips": "46003",
        "population": 2747,
        "land_area_sq_mi": 708.46,
        "centroid": [
          43.693726,
          -98.529708
        ],
        "county_seat": null
      },
      {
        "county_name": "Beadle County",
        "state_fips": "46",
        "county_fips": "46005",
        "population": 19149,
        "land_area_sq_mi": 1258.698,
        "centroid": [
          44.367306,
          -98.2277
        ],
        "county_seat": null
      },
      {
        "county_name": "Bennett County",
        "state_fips": "46",
        "county_fips": "46007",
        "population": 3381,
        "land_area_sq_mi": 1184.642,
        "centroid": [
          43.210572,
          -101.785879
        ],
        "county_seat": null
      },
      {
        "county_name": "Bon Homme County",
        "state_fips": "46",
        "county_fips": "46009",
        "population": 7003,
        "land_area_sq_mi": 563.549,
        "centroid": [
          42.966147,
          -97.859901
        ],
        "county_seat": null
      },
      {
        "county_name": "Brookings County",
        "state_fips": "46",
        "county_fips": "46011",
        "population": 34375,
        "land_area_sq_mi": 792.217,
        "centroid": [
          44.31091,
          -96.785884
        ],
        "county_seat": null
      },
      {
        "county_name": "Brown County",
        "state_fips": "46",
        "county_fips": "46013",
        "population": 38301,
        "land_area_sq_mi": 1713.03,
        "centroid": [
          45.475353,
          -98.451669
        ],
        "county_seat": null
      },
      {
        "county_name": "Brule County",
        "state_fips": "46",
        "county_fips": "46015",
        "population": 5247,
        "land_area_sq_mi": 817.222,
        "centroid": [
          43.762674,
          -99.191362
        ],
        "county_seat": null
      },
      {
        "county_name": "Buffalo County",
        "state_fips": "46",
        "county_fips": "46017",
        "population": 1948,
        "land_area_sq_mi": 471.405,
        "centroid": [
          44.059088,
          -99.371007
        ],
        "county_seat": null
      },
      {
        "county_name": "Butte County",
        "state_fips": "46",
        "county_fips": "46019",
        "population": 10243,
        "land_area_sq_mi": 2250.01,
        "centroid": [
          44.669688,
          -103.766262
        ],
        "county_seat": null
      },
      {
        "county_name": "Campbell County",
        "state_fips": "46",
        "county_fips": "46021",
        "population": 1377,
        "land_area_sq_mi": 733.677,
        "centroid": [
          45.801272,
          -100.100553
        ],
        "county_seat": null
      },
      {
        "county_name": "Charles Mix County",
        "state_fips": "46",
        "county_fips": "46023",
        "population": 9373,
        "land_area_sq_mi": 1097.141,
        "centroid": [
          43.175337,
          -98.527816
        ],
        "county_seat": null
      },
      {
        "county_name": "Clark County",
        "state_fips": "46",
        "county_fips": "46025",
        "population": 3837,
        "land_area_sq_mi": 957.512,
        "centroid": [
          44.825614,
          -97.709207
        ],
        "county_seat": null
      },
      {
        "county_name": "Clay County",
        "state_fips": "46",
        "county_fips": "46027",
        "population": 14967,
        "land_area_sq_mi": 412.022,
        "centroid": [
          42.808955,
          -96.936772
        ],
        "county_seat": null
      },
      {
        "county_name": "Codington County",
        "state_fips": "46",
        "county_fips": "46029",
        "population": 28325,
        "land_area_sq_mi": 687.585,
        "centroid": [
          44.91407,
          -97.129856
        ],
        "county_seat": null
      },
      {
        "county_name": "Corson County",
        "state_fips": "46",
        "county_fips": "46031",
        "population": 3902,
        "land_area_sq_mi": 2469.694,
        "centroid": [
          45.758065,
          -100.912373
        ],
        "county_seat": null
      },
      {
        "county_name": "Custer County",
        "state_fips": "46",
        "county_fips": "46033",
        "population": 8318,
        "land_area_sq_mi": 1556.943,
        "centroid": [
          43.740721,
          -103.514861
        ],
        "county_seat": null
      },
      {
        "county_name": "Davison County",
        "state_fips": "46",
        "county_fips": "46035",
        "population": 19956,
        "land_area_sq_mi": 435.633,
        "centroid": [
          43.706382,
          -98.040431
        ],
        "county_seat": null
      },
      {
        "county_name": "Day County",
        "state_fips": "46",
        "county_fips": "46037",
        "population": 5449,
        "land_area_sq_mi": 1028.49,
        "centroid": [
          45.369062,
          -97.519215
        ],
        "county_seat": null
      },
      {
        "county_name": "Deuel County",
        "state_fips": "46",
        "county_fips": "46039",
        "population": 4295,
        "land_area_sq_mi": 622.739,
        "centroid": [
          44.738673,
          -96.660949
        ],
        "county_seat": null
      },
      {
        "county_name": "Dewey County",
        "state_fips": "46",
        "county_fips": "46041",
        "population": 5239,
        "land_area_sq_mi": 2302.376,
        "centroid": [
          45.116562,
          -101.110107
        ],
        "county_seat": null
      },
      {
        "county_name": "Douglas County",
        "state_fips": "46",
        "county_fips": "46043",
        "population": 2835,
        "land_area_sq_mi": 431.801,
        "centroid": [
          43.377636,
          -98.369735
        ],
        "county_seat": null
      },
      {
        "county_name": "Edmunds County",
        "state_fips": "46",
        "county_fips": "46045",
        "population": 3986,
        "land_area_sq_mi": 1125.98,
        "centroid": [
          45.453421,
          -99.148719
        ],
        "county_seat": null
      },
      {
        "county_name": "Fall River County",
        "state_fips": "46",
        "county_fips": "46047",
        "population": 6973,
        "land_area_sq_mi": 1739.889,
        "centroid": [
          43.387361,
          -103.513072
        ],
        "county_seat": null
      },
      {
        "county_name": "Faulk County",
        "state_fips": "46",
        "county_fips": "46049",
        "population": 2125,
        "land_area_sq_mi": 981.713,
        "centroid": [
          45.061037,
          -99.099318
        ],
        "county_seat": null
      },
      {
        "county_name": "Grant County",
        "state_fips": "46",
        "county_fips": "46051",
        "population": 7556,
        "land_area_sq_mi": 681.446,
        "centroid": [
          45.206943,
          -96.658721
        ],
        "county_seat": null
      },
      {
        "county_name": "Gregory County",
        "state_fips": "46",
        "county_fips": "46053",
        "population": 3994,
        "land_area_sq_mi": 1014.95,
        "centroid": [
          43.183504,
          -99.27955
        ],
        "county_seat": null
      },
      {
        "county_name": "Haakon County",
        "state_fips": "46",
        "county_fips": "46055",
        "population": 1872,
        "land_area_sq_mi": 1810.541,
        "centroid": [
          44.133291,
          -101.572693
        ],
        "county_seat": null
      },
      {
        "county_name": "Hamlin County",
        "state_fips": "46",
        "county_fips": "46057",
        "population": 6164,
        "land_area_sq_mi": 507.068,
        "centroid": [
          44.646162,
          -97.148245
        ],
        "county_seat": null
      },
      {
        "county_name": "Hand County",
        "state_fips": "46",
        "county_fips": "46059",
        "population": 3145,
        "land_area_sq_mi": 1436.633,
        "centroid": [
          44.525472,
          -98.991594
        ],
        "county_seat": null
      },
      {
        "county_name": "Hanson County",
        "state_fips": "46",
        "county_fips": "46061",
        "population": 3461,
        "land_area_sq_mi": 434.582,
        "centroid": [
          43.656069,
          -97.771709
        ],
        "county_seat": null
      },
      {
        "county_name": "Harding County",
        "state_fips": "46",
        "county_fips": "46063",
        "population": 1311,
        "land_area_sq_mi": 2671.57,
        "centroid": [
          45.605864,
          -103.520304
        ],
        "county_seat": null
      },
      {
        "county_name": "Hughes County",
        "state_fips": "46",
        "county_fips": "46065",
        "population": 17765,
        "land_area_sq_mi": 741.527,
        "centroid": [
          44.38283,
          -100.305301
        ],
        "county_seat": null
      },
      {
        "county_name": "Hutchinson County",
        "state_fips": "46",
        "county_fips": "46067",
        "population": 7427,
        "land_area_sq_mi": 813.013,
        "centroid": [
          43.336978,
          -97.745451
        ],
        "county_seat": null
      },
      {
        "county_name": "Hyde County",
        "state_fips": "46",
        "county_fips": "46069",
        "population": 1262,
        "land_area_sq_mi": 860.629,
        "centroid": [
          44.519687,
          -99.455271
        ],
        "county_seat": null
      },
      {
        "county_name": "Jackson County",
        "state_fips": "46",
        "county_fips": "46071",
        "population": 2806,
        "land_area_sq_mi": 1863.883,
        "centroid": [
          43.649678,
          -101.665063
        ],
        "county_seat": null
      },
      {
        "county_name": "Jerauld County",
        "state_fips": "46",
        "county_fips": "46073",
        "population": 1663,
        "land_area_sq_mi": 526.133,
        "centroid": [
          44.09101,
          -98.537954
        ],
        "county_seat": null
      },
      {
        "county_name": "Jones County",
        "state_fips": "46",
        "county_fips": "46075",
        "population": 917,
        "land_area_sq_mi": 969.668,
        "centroid": [
          43.89534,
          -100.695148
        ],
        "county_seat": null
      },
      {
        "county_name": "Kingsbury County",
        "state_fips": "46",
        "county_fips": "46077",
        "population": 5187,
        "land_area_sq_mi": 832.237,
        "centroid": [
          44.377105,
          -97.408777
        ],
        "county_seat": null
      },
      {
        "county_name": "Lake County",
        "state_fips": "46",
        "county_fips": "46079",
        "population": 11059,
        "land_area_sq_mi": 562.891,
        "centroid": [
          44.001466,
          -97.095038
        ],
        "county_seat": null
      },
      {
        "county_name": "Lawrence County",
        "state_fips": "46",
        "county_fips": "46081",
        "population": 25768,
        "land_area_sq_mi": 800.053,
        "centroid": [
          44.453405,
          -103.805876
        ],
        "county_seat": null
      },
      {
        "county_name": "Lincoln County",
        "state_fips": "46",
        "county_fips": "46083",
        "population": 65161,
        "land_area_sq_mi": 577.293,
        "centroid": [
          43.441142,
          -96.744487
        ],
        "county_seat": null
      },
      {
        "county_name": "Lyman County",
        "state_fips": "46",
        "county_fips": "46085",
        "population": 3718,
        "land_area_sq_mi": 1642.285,
        "centroid": [
          43.953669,
          -99.716961
        ],
        "county_seat": null
      },
      {
        "county_name": "McCook County",
        "state_fips": "46",
        "county_fips": "46087",
        "population": 5682,
        "land_area_sq_mi": 574.205,
        "centroid": [
          43.661486,
          -97.348311
        ],
        "county_seat": null
      },
      {
        "county_name": "McPherson County",
        "state_fips": "46",
        "county_fips": "46089",
        "population": 2411,
        "land_area_sq_mi": 1136.668,
        "centroid": [
          45.766155,
          -99.243067
        ],
        "county_seat": null
      },
      {
        "county_name": "Marshall County",
        "state_fips": "46",
        "county_fips": "46091",
        "population": 4306,
        "land_area_sq_mi": 838.081,
        "centroid": [
          45.757886,
          -97.628902
        ],
        "county_seat": null
      },
      {
        "county_name": "Meade County",
        "state_fips": "46",
        "county_fips": "46093",
        "population": 29852,
        "land_area_sq_mi": 3470.934,
        "centroid": [
          44.281372,
          -103.280064
        ],
        "county_seat": null
      },
      {
        "county_name": "Mellette County",
        "state_fips": "46",
        "county_fips": "46095",
        "population": 1918,
        "land_area_sq_mi": 1307.311,
        "centroid": [
          43.54937,
          -100.809211
        ],
        "county_seat": null
      },
      {
        "county_name": "Miner County",
        "state_fips": "46",
        "county_fips": "46097",
        "population": 2298,
        "land_area_sq_mi": 570.17,
        "centroid": [
          44.01131,
          -97.551535
        ],
        "county_seat": null
      },
      {
        "county_name": "Minnehaha County",
        "state_fips": "46",
        "county_fips": "46099",
        "population": 197214,
        "land_area_sq_mi": 806.847,
        "centroid": [
          43.558266,
          -96.731507
        ],
        "county_seat": null
      },
      {
        "county_name": "Moody County",
        "state_fips": "46",
        "county_fips": "46101",
        "population": 6336,
        "land_area_sq_mi": 519.379,
        "centroid": [
          44.018445,
          -96.663373
        ],
        "county_seat": null
      },
      {
        "county_name": "Oglala Lakota County",
        "state_fips": "46",
        "county_fips": "46102",
        "population": 13672,
        "land_area_sq_mi": 2093.601,
        "centroid": [
          43.183372,
          -102.47964
        ],
        "county_seat": null
      },
      {
        "county_name": "Pennington County",
        "state_fips": "46",
        "county_fips": "46103",
        "population": 109222,
        "land_area_sq_mi": 2776.765,
        "centroid": [
          44.064853,
          -103.210935
        ],
        "county_seat": null
      },
      {
        "county_name": "Perkins County",
        "state_fips": "46",
        "county_fips": "46105",
        "population": 2835,
        "land_area_sq_mi": 2870.46,
        "centroid": [
          45.70961,
          -102.331006
        ],
        "county_seat": null
      },
      {
        "county_name": "Potter County",
        "state_fips": "46",
        "county_fips": "46107",
        "population": 2472,
        "land_area_sq_mi": 861.138,
        "centroid": [
          45.070399,
          -99.951949
        ],
        "county_seat": null
      },
      {
        "county_name": "Roberts County",
        "state_fips": "46",
        "county_fips": "46109",
        "population": 10280,
        "land_area_sq_mi": 1101.055,
        "centroid": [
          45.611156,
          -96.959096
        ],
        "county_seat": null
      },
      {
        "county_name": "Sanborn County",
        "state_fips": "46",
        "county_fips": "46111",
        "population": 2330,
        "land_area_sq_mi": 569.242,
        "centroid": [
          44.005619,
          -98.14513
        ],
        "county_seat": null
      },
      {
        "county_name": "Spink County",
        "state_fips": "46",
        "county_fips": "46115",
        "population": 6361,
        "land_area_sq_mi": 1503.499,
        "centroid": [
          44.904738,
          -98.412881
        ],
        "county_seat": null
      },
      {
        "county_name": "Stanley County",
        "state_fips": "46",
        "county_fips": "46117",
        "population": 2980,
        "land_area_sq_mi": 1444.436,
        "centroid": [
          44.372239,
          -100.448102
        ],
        "county_seat": null
      },
      {
        "county_name": "Sully County",
        "state_fips": "46",
        "county_fips": "46119",
        "population": 1446,
        "land_area_sq_mi": 1006.727,
        "centroid": [
          44.703108,
          -100.135851
        ],
        "county_seat": null
      },
      {
        "county_name": "Todd County",
        "state_fips": "46",
        "county_fips": "46121",
        "population": 9319,
        "land_area_sq_mi": 1388.593,
        "centroid": [
          43.24927,
          -100.780183
        ],
        "county_seat": null
      },
      {
        "county_name": "Tripp County",
        "state_fips": "46",
        "county_fips": "46123",
        "population": 5624,
        "land_area_sq_mi": 1612.289,
        "centroid": [
          43.350237,
          -99.846955
        ],
        "county_seat": null
      },
      {
        "county_name": "Turner County",
        "state_fips": "46",
        "county_fips": "46125",
        "population": 8673,
        "land_area_sq_mi": 617.064,
        "centroid": [
          43.304408,
          -97.112768
        ],
        "county_seat": null
      },
      {
        "county_name": "Union County",
        "state_fips": "46",
        "county_fips": "46127",
        "population": 16811,
        "land_area_sq_mi": 460.757,
        "centroid": [
          42.681007,
          -96.592222
        ],
        "county_seat": null
      },
      {
        "county_name": "Walworth County",
        "state_fips": "46",
        "county_fips": "46129",
        "population": 5315,
        "land_area_sq_mi": 707.455,
        "centroid": [
          45.518483,
          -100.311806
        ],
        "county_seat": null
      },
      {
        "county_name": "Yankton County",
        "state_fips": "46",
        "county_fips": "46135",
        "population": 23310,
        "land_area_sq_mi": 521.189,
        "centroid": [
          42.90126,
          -97.396931
        ],
        "county_seat": null
      },
      {
        "county_name": "Ziebach County",
        "state_fips": "46",
        "county_fips": "46137",
        "population": 2413,
        "land_area_sq_mi": 1961.248,
        "centroid": [
          44.929817,
          -101.530161
        ],
        "county_seat": null
      }
    ]
